### ISSUE TITLE
 Auto-update functionality for the AWS CLI MSI installer for Windows (64-bit)

### ISSUE THREAD

**Issue by visit1985** [aws/aws-cli#8645] opened 2024-04-22 16:42 UTC
### Describe the feature

Provide some auto-update functionality for the AWS CLI MSI installer for Windows (64-bit).

### Use Case

Some companies, relying on Windows, provide locked down devices without admin permissions to employees, and have highly regulated and slow software packaging cycles. At the same time users are always requiring the latest AWS CLI update to make use of new features. AWS CLI version 1 fulfills this need by allowing users to upgrade without admin permissions using Python pip.

### Proposed Solution

While this could obviously be solved on organizational level, providing some form of auto-update functionality could help to speed up adoption of AWS CLI version 2.

### Other Information

/v2

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

aws-cli/1.32.88 Python/3.9.1 Windows/10 botocore/1.34.88

### Environment details (OS name and version, etc.)

Windows 10 Enterprise (64-bit)

**Comment by tim-finnigan** [comment] 2024-04-23 18:38
Thanks for the feature request. We do recommend migrating to v2 if possible (documentation here for guidance: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-instructions.html). 

The request to make the AWS CLI available in package managers like pip is being tracked in https://github.com/aws/aws-cli/issues/4947 but not under consideration at this time for reasons explained in the issue. However, it appears that the issue here is essentially a duplicate of https://github.com/aws/aws-cli/issues/4633, requesting the ability to install on Windows without admin privileges. I think this can be closed for consolidation, but please feel free to 👍 those issues and add any relevant comments there, or let us know if there are any other details you wanted to share regarding your use case.

**Closed by tim-finnigan** 2024-04-23 18:38 UTC
Labels: investigating, feature-request
