### ISSUE TITLE
aws s3 cp results in [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] error

### ISSUE THREAD

**Issue by robcole** [aws/aws-cli#5840] opened 2020-12-23 19:05 UTC
This has been happening for a few weeks now - it's a nondeterministic error, so occasionally I can get full downloads (the file I'm downloading is ~30gb). I usually have to try 4 or 5 times.

OS: Catalina 10.5.7
aws-cli version (installed via brew): 2.1.13

Debug output (last ~10 lines prior to download termination):

Command: `aws s3 cp s3://bucket-name/s3-original-file-name.tar.gz /demo.filename.gz --debug`

```
2020-12-23 10:54:07,958 - ThreadPoolExecutor-0_0 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_12 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_13 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_14 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_5 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_16 - s3transfer.futures - DEBUG - Submitting task IORenameFileTask(transfer_id=0, {'final_filename': '/demo.filename.gz'}) to executor <s3transfer.futures.BoundedExecutor object at 0x104d02ca0> for transfer request: 0.
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_16 - s3transfer.utils - DEBUG - Acquiring 0
2020-12-23 10:54:07,959 - ThreadPoolExecutor-0_16 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2020-12-23 10:54:07,959 - ThreadPoolExecutor-2_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': '/demo.filename.gz'}) about to wait for the following futures []
2020-12-23 10:54:07,959 - ThreadPoolExecutor-2_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=0, {'final_filename': '/demo.filename.gz'}) done waiting for dependent futures
2020-12-23 10:54:12,218 - ThreadPoolExecutor-2_0 - s3transfer.utils - DEBUG - Releasing acquire 0/None
download failed: s3://bucket-name/s3-original-file-name.tar.gz to ../../../../demo.filename.gz [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
2020-12-23 10:54:12,219 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
```

**Comment by kdaily** [comment] 2020-12-23 21:48
Hi @robcole, 

Can you post more of the debug logs? Adding it as an attachment or a Gist is fine - be sure to remove any sensitive info first (account numbers, etc). Without seeing a bit more of what happens before, I can't speculate too much about the cause.

A quick search of this issue shows that it can often be related to multiprocessing, which a multi-part upload would be using, and may explain the transient nature. I'm wondering if setting TCP keep-alive on would would help - it was noted in one post I read online. This may be OS-dependent if you are able to use keep-alive effectively, as it uses your system's settings.

 You can add `tcp_keepalive = true` in your AWS config file to the profile you're using (maybe `default`).

**Comment by kdaily** [comment] 2020-12-23 21:50
I also don't anticipate it being a problem, but we do not control the HomeBrew package. If possible, confirming that this occurs with one of the supported installation methods would be helpful to rule that out.

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

**Comment by robcole** [comment] 2020-12-28 16:11
> Hi @robcole,
> 
> Can you post more of the debug logs? Adding it as an attachment or a Gist is fine - be sure to remove any sensitive info first (account numbers, etc). Without seeing a bit more of what happens before, I can't speculate too much about the cause.
> 
> A quick search of this issue shows that it can often be related to multiprocessing, which a multi-part upload would be using, and may explain the transient nature. I'm wondering if setting TCP keep-alive on would would help - it was noted in one post I read online. This may be OS-dependent if you are able to use keep-alive effectively, as it uses your system's settings.
> 
> You can add `tcp_keepalive = true` in your AWS config file to the profile you're using (maybe `default`).

Thanks for the response. I gave that a shot but unfortunately got some failures there as well. Here's a longer stack trace:

https://gist.github.com/robcole/e9c4e0ae06d950b1b0c09c680f49a67a

**Comment by robcole** [comment] 2020-12-28 16:13
> I also don't anticipate it being a problem, but we do not control the HomeBrew package. If possible, confirming that this occurs with one of the supported installation methods would be helpful to rule that out.

Seems unlikely to the the cause of this issue but I'll give it a shot regardless.

**Comment by kdaily** [comment] 2020-12-28 22:39
Thanks for trying, @robcole. I found that there is a previous report of this error, currently without a resolution. I'm checking with the team handling that to see if there have been any further suggestions.

**Comment by robcole** [comment] 2020-12-30 19:05
Thanks @kdaily, I really appreciate the responsiveness. Good to know that this isn't (necessarily) PEBKAC of some sort.

**Comment by victorshx** [comment] 2021-01-11 11:34
@robcole Look into [rclone](https://rclone.org/s3/) for copying if the issue you are facing is consistent. I've had some issues with aws s3 on my machine when copying large files. It has automatic retry on failures.

It's very straightforward to configure and start copying. Here is how I do it.
```
rclone config
rclone copy s3:bucket "<dest path>" --transfers 3 -P
```

**Comment by robcole** [comment] 2021-02-08 19:38
@kdaily This seems to be related to the same complaints users are having in this thread - is this something that is unlikely to be fixed in the short-term so anyone encountering this should just look for workarounds like `rclone` etc?

https://forums.aws.amazon.com/thread.jspa?threadID=126932 made me think that this has been going on a long while for various users. 

I'm running into the issue on multiple buckets in multiple regions at this point and more or less have to give up on regular downloads of some of these larger files as it can take hours for a successful request to fully complete.

**Comment by CyberLykan** [comment] 2021-02-19 23:38
Not aws related, but I am also getting this same error when downloading things sometimes.

**Comment by kdaily** [comment] 2021-03-26 19:47
Hi @robcole,

That thread shows users outside of the AWS CLI through other AWS SDKs were also experiencing this issue, so I think it's unlikely to be related specifically to the CLI. I haven't heard anything back from the S3 team about it. If you have other debug logs (specifically with the request ID in them) that could aid in determining the underlying cause.

**Comment by SomervilleTom** [comment] 2021-07-29 13:53
I think I just got bit by this bug, 29-JUL-2021. I'm attempting to use the aws cli on Windows 10 Pro. 

I have solid 1GB/sec connection and I'm experience no issues downloading from other sites. Here's the error I saw:
```
[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)
```

Here is the full command line (executed from an elevated command prompt):
```
I:\c_backup>aws s3 cp "s3://tms-office.zeetix.com/Samsung SSD 860 EVO 1TB RVT03B6Q-0077.tibx" .
download failed: s3://tms-office.zeetix.com/Samsung SSD 860 EVO 1TB RVT03B6Q-0077.tibx to .\Samsung SSD 860 EVO 1TB RVT03B6Q-0077.tibx [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)
```
I had no issues uploading it (although it took forever), and I need to be able to retrieve these (they are backup files!).

**Comment by oddissyus** [comment] 2021-09-08 21:05
I have had this issue for some time om my MacOS (big sur 11.5.2). Here is the error:
[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)

$ uname -a
Darwin guava.adari.net 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

$ aws --version
aws-cli/2.2.34 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off

With big files (over 1GB) it consistently happens, however, on repeat tries it does occasionally succeed.  With smaller file its an issue.

**Comment by kdaily** [comment] 2021-09-20 19:25
Hi @oddissyus and @SomervilleTom,

Thanks for the updates. Are you still getting these errors? Previous posts on the AWS Forums indicated this was a hardware error with a load balancer in use for S3. This is consistent with the posts that showed the same error with PHP and JS/Node.js AWS SDKs as well. So, I'm fairly certain this is not an AWS CLI or Python SDK-specific issue.

In general, getting assistance for this type of issue is best by opening an AWS support request - the AWS forums post had an AWS engineer open an outbound cases for customers through AWS support. If you continue to get this error consistently, I would comment on that post as well and be prepared to provide the details that they are requesting (request ID, SDK logs, and network logs).

Since this is not an AWS CLI-specific issue and there is an open forum thread, I would encourage you to comment there. Thanks again for your feedback.

**Comment by SomervilleTom** [comment] 2021-09-20 21:12
I just now ran the same command line that failed last summer, and it finished as expected.

It appears that this was, in fact, some temporary issue that was resolved.

**Comment by kdaily** [comment] 2021-09-20 22:02
Thanks @SomervilleTom!

**Comment by bransinanderson** [comment] 2021-11-12 20:13
I'm experiencing the same problem. Tried both sync and copy to an empty directory on my local machine. Always copies up to a certain point and then fails. Only a quarter or less of the copy process and then just immediately stops.

I installed aws-cli on Linux Ubuntu 20.04.3 LTS 64-bit
https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

`aws --version`
aws-cli/2.3.5 Python/3.8.8 Linux/5.4.0-90-generic exe/x86_64.ubuntu.20 prompt/off

`python --version`
Python 3.8.10

`$aws --profile customprofile --endpoint-url https://redacted.redacted.redacted.com s3 cp s3://mysite/ ./ --recursive --debug 2> debug.txt`

Last part of the debug file and last file that transferred. Paths and ids have been redacted from this log.
It ends with:
`Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.`


```
2021-11-12 11:32:34,974 - ThreadPoolExecutor-0_0 - urllib3.connectionpool - DEBUG - https://redacted.redacted.redacted.com:443 "GET /mysite/images/Redacted-Folder-Name/AnotherFolderRedacted/_100x100_crop_center-center_82_changed/MySite_RedactedFile_HeroImage.jpg HTTP/1.1" 200 65351
2021-11-12 11:32:34,974 - ThreadPoolExecutor-0_0 - botocore.parsers - DEBUG - Response headers: {'Date': 'Fri, 12 Nov 2021 18:32:34 GMT', 'Content-Type': 'image/jpeg', 'Content-Length': '65351', 'Connection': 'keep-alive', 'Content-Md5': 'bbb91f73f1c90331fcb621a15bb8b07a', 'Etag': '"bbb91f73f1c90331fcb621a15bb8b07a"', 'Last-Modified': 'Thu, 29 Apr 2021 19:58:29 GMT', 'X-Amz-Id-2': 'redacted-id-123', 'X-Amz-Request-Id': 'redacted-id-123', 'Server': 'redacted-backend'}
2021-11-12 11:32:34,974 - ThreadPoolExecutor-0_0 - botocore.parsers - DEBUG - Response body:
<botocore.response.StreamingBody object at 0x7f1268e9abb0>
2021-11-12 11:32:34,974 - ThreadPoolExecutor-0_0 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7f129e03db80>>
2021-11-12 11:32:34,975 - ThreadPoolExecutor-0_0 - botocore.retries.standard - DEBUG - Not retrying request.
2021-11-12 11:32:34,975 - ThreadPoolExecutor-0_0 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f129e03dbe0>>
2021-11-12 11:32:34,975 - ThreadPoolExecutor-0_0 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <function enhance_error_msg at 0x7f129ee3eaf0>
2021-11-12 11:32:34,975 - ThreadPoolExecutor-0_0 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7f129e03d6d0>>
2021-11-12 11:32:35,032 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=973, {'offset': 0}) about to wait for the following futures []
2021-11-12 11:32:35,032 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IOWriteTask(transfer_id=973, {'offset': 0}) done waiting for dependent futures
2021-11-12 11:32:35,032 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - Executing task IOWriteTask(transfer_id=973, {'offset': 0}) with kwargs {'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7f129c2e9a00>, 'offset': 0}
2021-11-12 11:32:35,033 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=973, {'final_filename': '/home/redacted-user/Downloads/mysite-assets/images/Redacted-Folder-Name/AnotherFolderRedacted/_100x100_crop_center-center_82_changed/MySite_RedactedFile_HeroImage.jpg'}) about to wait for the following futures []
2021-11-12 11:32:35,033 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - IORenameFileTask(transfer_id=973, {'final_filename': '/home/redacted-user/Downloads/mysite-assets/images/Redacted-Folder-Name/AnotherFolderRedacted/_100x100_crop_center-center_82_changed/MySite_RedactedFile_HeroImage.jpg'}) done waiting for dependent futures
2021-11-12 11:32:35,033 - ThreadPoolExecutor-0_0 - s3transfer.tasks - DEBUG - Executing task IORenameFileTask(transfer_id=973, {'final_filename': '/home/redacted-user/Downloads/mysite-assets/images/Redacted-Folder-Name/AnotherFolderRedacted/_100x100_crop_center-center_82_changed/MySite_RedactedFile_HeroImage.jpg'}) with kwargs {'fileobj': <s3transfer.utils.DeferredOpenFile object at 0x7f129c2e9a00>, 'final_filename': '/home/redacted-user/Downloads/mysite-assets/images/Redacted-Folder-Name/AnotherFolderRedacted/_100x100_crop_center-center_82_changed/MySite_RedactedFile_HeroImage.jpg', 'osutil': <s3transfer.utils.OSUtils object at 0x7f129e03de50>}
2021-11-12 11:32:35,034 - ThreadPoolExecutor-0_0 - s3transfer.utils - DEBUG - Releasing acquire 973/None
2021-11-12 11:32:35,034 - Thread-1 - awscli.customizations.s3.results - DEBUG - Shutdown request received in result processing thread, shutting down result thread.
```
~/.aws/config. I've tried this without configuring the s3 settings of max_concurrent_requests and still no luck.

```
[profile customprofile]
region = redacted
endpoint-url = https://redacted.redacted.redacted.com
max_attempts = 10
retry_mode = standard
s3 =
    max_concurrent_requests = 20
    max_queue_size = 99999
    multipart_threshold = 10240MB
    multipart_chunksize = 1024MB
    max_bandwidth = 9999MB/s
    use_accelerate_endpoint = false
    addressing_style = auto
```

**Comment by kdaily** [comment] 2022-02-18 19:48
Hi @robcole, sorry for the delay in response. Based on your post, it looks like you're using a non-AWS endpoint. Some S3-compatible implementations do not use the most recent API operations, most often `ListObjectsV2`, which paginate differently than the original `ListObjects`. See my comment here regarding common errors we've seen with third-party endpoints.

https://github.com/aws/aws-cli/issues/6618#issuecomment-996893951

You'll need to contact the maintainer of that service to get further assistance!

**Closed** 2022-02-18 19:48 UTC
Labels: s3, guidance, service-api
