### ISSUE TITLE
ssm doesn't handle longer instance ID's

### ISSUE THREAD

**Issue by jerm** [aws/aws-cli#1729] opened 2016-01-14 20:59 UTC
$ aws ssm send-command --instance-ids i-065d9ed12b63cd03d --document AWS-UpdateSSMAgent

Parameter validation failed:
Invalid length for parameter InstanceIds[0], value: 19, valid range: 10-10

**Comment by JordonPhillips** [comment] 2016-01-15 18:31
Thanks for reporting! Cross-service dependencies like this can be problematic

**Comment by nistic** [comment] 2016-01-21 02:41
Yeah, this is causing issues for us since aws is transitioning to a longer ID format.

**Comment by JordonPhillips** [comment] 2016-01-28 23:59
The SSM model has been fixed as of 1.10.1

**Closed by JordonPhillips** 2016-01-28 23:59 UTC
Labels: bug, ssm

**Comment by tlhumphrey2** [comment] 2017-02-09 01:15
I'm experiencing a similar error. My instance id is the new longer version, i.e. i-00f91d30c45259a35. Specifically, the error is: "Invalid length for parameter InstanceIds[0], value: 19, valid range: 1-16". The awscli command is: "aws autoscaling detach-instances". It doesn't like my long instance id.

**Comment by stenrap** [comment] 2017-02-09 04:47
@tlhumphrey2 I was having a similar error with this command:

`aws autoscaling terminate-instance-in-auto-scaling-group ...`

After reading #1954 I upgraded my awscli to the latest version and the problem is resolved.
