### ISSUE TITLE
Create and publish .deb/.rpm files

### ISSUE THREAD

**Issue by mikael-vandmo-wcar** [aws/aws-cli#6421] opened 2021-09-24 09:10 UTC
**Is your feature request related to a problem? Please describe.**
Keeping the v2 cli up to date.

**Describe the solution you'd like**
`sudo apt upgrade`

**Describe alternatives you've considered**
Just never upgrade until I am missing a feature that I need.

**Comment by stobrien89** [comment] 2021-09-24 17:59
Hi @mikael-vandmo-wcar,

Thanks for bringing this up! I'd consider this a duplicate of https://github.com/aws/aws-cli/issues/5282.  We're actively working on a [source distribution ](https://github.com/aws/aws-cli/pull/6352), which should help ease issues with packaging.  We'll post any updates to the linked issue!

**Closed by stobrien89** 2021-09-24 17:59 UTC
Labels: duplicate, feature-request, v2, installation
