### ISSUE TITLE
mfa_serial does not work with U2F

### ISSUE THREAD

**Issue by jr42** [aws/aws-cli#4094] opened 2019-04-23 12:56 UTC
When configuring a profile with MFA like this:

```
[profile myprofile]
role_arn = arn:aws:iam::123456789012:role/MyRole
source_profile = default
region = eu-west-1
mfa_serial = arn:aws:iam::123456789012:u2f/user/myuser/default-qwertzuioplkjhgfdsa
```

and try to assume the role I get this when pasting the U2F token by long-pressing my Yubikey:

```
T:\>aws --profile myprofile ec2 describe-regions
Enter MFA code for arn:aws:iam::123456789012:u2f/user/myuser/default-qwertzuioplkjhgfdsa:

An error occurred (ValidationError) when calling the AssumeRole operation: 2 validation errors detected: Value 'eifjccgncvncgfkjgjtjbfjilgtjrjbvgbvelhivvjlt' at 'tokenCode' failed to satisfy constraint: Member must have length less than or equal to 6; Value 'eifjccgncvncgfkjgjtjbfjilgtjrjbvgbvelhivvjlt' at 'tokenCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [\d]*
```

Validatation should be extended to support U2F tokens.

**Comment by swetashre** [comment] 2019-04-24 00:06
@jr42 - Thank you for your post. According to our [documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_u2f_supported_configurations.html) using U2F security keys for MFA is not currently supported in the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and [AWS API](https://aws.amazon.com/tools/), or for access to [MFA-protected API operations](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html). 

This feature would have to be first supported by API before it can be implemented in the CLI. Marking this as a feature request with a dependency. 

We will close this issue for now and reopen a new one once the API supports it.

**Closed** 2019-04-24 00:12 UTC
Labels: dependency, feature-request

**Comment by isarang** [comment] 2021-02-08 06:09
Any update or anyone in AWS followed up on this?

**Comment by fstephany** [comment] 2021-02-16 10:25
@isarang It seems that this is a duplicate of https://github.com/aws/aws-cli/issues/3607
And nothing has moved since ages.

**Comment by debek** [comment] 2022-04-06 10:29
Ohh my god. How it is possible :/

**Comment by staenker** [comment] 2022-06-01 06:47
`@[swetashre](https://github.com/swetashre) swetashre closed this as [completed]`
I just hope this was an honest mistake and not your general approach to a definition of done|completed ...

**Comment by igor-nesterov-deltatre** [comment] 2023-01-04 12:34
Any updates?

**Comment by mgrobaker** [comment] 2023-04-12 20:09
Open issue
https://github.com/aws/aws-cli/issues/3607
