### ISSUE TITLE
Expose depencies via PyPi's json api

### ISSUE THREAD

**Issue by lassepe** [aws/aws-cli#6306] opened 2021-07-30 16:29 UTC
Currently, `awscli` exposes no information about dependencies via the [PyPi json api](https://pypi.org/pypi/awscli/json). This causes  package managers like [poetry to choke on this package](https://github.com/python-poetry/poetry/issues/2094#issuecomment-889882745) since it has to download the package at various versions to recover the dependency tree. Thus, I was wondering whether this information could be added json api.

**Comment by kdaily** [comment] 2021-07-30 16:37
Hello @lassepe,

Thanks for the comment. I think this is a duplicate of https://github.com/aws/aws-cli/issues/5701. If so let's close and track there. It's not something that's currently planned to do. Thanks!

**Closed** 2021-07-30 16:39 UTC
Labels: closing-soon, duplicate, feature-request
