### ISSUE TITLE
Cloudformation validate-template does not report CAPABILITY_AUTOEXPAND

### ISSUE THREAD

**Issue by dxciberaws** [aws/aws-cli#4747] opened 2019-12-10 17:57 UTC
When applied to templates containing Fn:Transform functions, validate-template does not report the CAPABILITY_AUTO_EXPAND as a required one. This makes a subsequent call to create-stack that takes the result from validate-template as input, fail.
Probably the limitation comes from Boto3, but have not done the test yet.

Example:
{
  "Parameters" : {
    "AccountCode": {
      "Type":"String",
      "MinLength" : "3",
      "MaxLength" : "12",
      "Description" : "Account code name, between 3 and 5 letters"
    }
  },
  "Resources": {
    "SsmThisAccountCodeLow": {
      "Type" : "AWS::SSM::Parameter",
      "Properties" : {
        "Name" : "account-code-low",
        "Description" : "Low case AWS LZ Code name for this account",
        "Value" : {"Fn::Transform":[
          {
            "Name":"String",
            "Parameters": {
              "InputString": {"Ref":"AccountCode"},
              "Operation": "Lower"
            }
          }
        ]},
        "Type" : "String"
      }
    }
  }
}

When validated returns:

{
    "Parameters": [
        {
            "ParameterKey": "AccountCode",
            "NoEcho": false,
            "Description": "Account code name, between 3 and 5 letters"
        }
    ]
}

Same limitation affects the Java SDK which in turn hits the Eclipse Toolkit, which cannot create CFN stacks containing macros for this reason.

**Comment by jamesls** [comment] 2019-12-10 20:18
It appears that the issue is that the service API is not returning this data, given you're having this issue in the CLI and the Java SDK.  The fix for this would need to come from the cloudformation team.  I can forward this request on to the service team but I would also suggest request this on the cloudformation forums (https://forums.aws.amazon.com/forum.jspa?forumID=92).

I'm going to go ahead and close this out for now given we can't fix this in the CLI.  Let me know if you have any other questions.

**Closed by jamesls** 2019-12-10 20:18 UTC
Labels: service-api
