### ISSUE TITLE
Bug in error reporting: string indices must be integers

### ISSUE THREAD

**Issue by samthebest** [aws/aws-cli#1751] opened 2016-01-27 14:32 UTC
```
aws s3 ls s3://foo

string indices must be integers
```

This is a ridiculous error message, it should be "Please run `aws configure`"

**Comment by kyleknap** [comment] 2016-01-27 17:30
What version of the CLI are using? You can figure this out by running ``$ aws --version``.

I am not able to reproduce the error message when I do not have credentials set:
```
$ aws --version
aws-cli/1.10.0 Python/2.7.5 Darwin/13.4.0 botocore/1.3.22
$ aws configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None
$ aws s3 ls
Unable to locate credentials. You can configure credentials by running "aws configure".
```
Let me know if that helps.

**Comment by samaimia** [comment] 2016-01-27 17:41
I installed on mac with brew, then uninstalled, then pip then uninstalled then using the zip, none worked.

The zip one has version:
`aws-cli/1.10.0 Python/2.7.10 Darwin/15.3.0 botocore/1.3.22`

Which seems to be quite a bit later than yours.

**Comment by samthebest** [comment] 2016-01-27 17:41
I installed on mac with brew, then uninstalled, then pip then uninstalled then using the zip, none worked.

The zip one has version:
`aws-cli/1.10.0 Python/2.7.10 Darwin/15.3.0 botocore/1.3.22`

Which seems to be quite a bit later than yours.

**Comment by kyleknap** [comment] 2016-01-27 18:40
I do not think it is an issue with the differing python versions. It may be an issue with El Capitan. We have had a fair amount of issues coming in about issues installing the cli on El Capitan with no [vitual environment](https://virtualenv.readthedocs.org/en/latest/): https://github.com/aws/aws-cli/issues/1522.

Could you provide two bits of details to help debug this?
1) The debug logs by running: ``aws s3 ls --debug``
2) How you are installing with ``pip``. Note I would not recommend using homebrew since we do not maintain nor officially support ``brew`` as an installation method.

**Comment by samthebest** [comment] 2016-01-27 18:51
RE 2, I used easy_install method, first one on SO.

RE 1, Ok will do, but will have to revert the aws configure.

It should be pretty easy to reproduce by using VM with El Capitan.

**Comment by kyleknap** [comment] 2016-01-28 17:43
Thanks those debug logs will be helpful. I was searching for similar issues in the repository and I found this one: https://github.com/aws/aws-cli/issues/1456. Are you retrieving credentials via assume role because it looked like the requester of the issue had problems related to configuration for assuming an iam role?

**Comment by samthebest** [comment] 2016-01-28 18:21
@kyleknap  Nope, I was literally just trying `s3://foo` expecting to get something along the lines of "Not authorised" or "bucket does not exist".

Please could you tell me how to undo `aws --configure` and I'll get those debug logs to you :)

**Comment by kyleknap** [comment] 2016-01-28 20:24
So you can undo ``aws configure`` by either removing ``~/.aws/credentials`` and/or ``~/.aws/config`` depending on where your credentials are. Or you can comment your profile/credentials out with ``#`` on the lines since they are ini files.

**Comment by samthebest** [comment] 2016-01-29 11:38
@kyleknap I can't reproduce anymore! I tried resintalling inside an ubuntu:latest docker container and it gives a sensible error message.  Did someone quickly fix this? Could it be I was just unlucky that the version released on that day was dodgy? Can anyone confirm?

**Comment by kyleknap** [comment] 2016-01-29 17:21
Good to hear that it is working now. I have no idea why it started working. We did a release yesterday, but nothing related to installation changed. If you figure out what might have happened, we would love to hear what may have happened. Otherwise closing issue.

**Closed by kyleknap** 2016-01-29 17:21 UTC
Labels: installation, question
