### ISSUE TITLE
Support configuring max retries for deploy wait-deployment-successful

### ISSUE THREAD

**Issue by colvardrm2** [aws/aws-cli#6399] opened 2021-09-14 16:43 UTC
**Is your feature request related to a problem? Please describe.**
For some background, we're using the `aws deploy wait-deployment-successful` command to trigger a deploy in a shell script and wait for it as part of our build. I recently encountered a timeout error from the command though, which happened because one of the instances that was spun up for the deploy randomly took about 20 minutes to spin up. Another one spun up at the same time took about 2 minutes, so I think it was just some random slowness. That resulted in the overall deploy taking more than 30 minutes, which made the command fail.

**Describe the solution you'd like**
A way to configure the max number of retries would probably be the simplest solution. Allowing the user to change the time between tries might be good too, but I don't think it's strictly necessary. Being hardcoded at 120 tries/30 minutes means that you have to write retry logic around the wait command itself to handle cases like this. Given that CodeDeploy currently times out after 1 hour for any individual step in the deploy and allows deploys well beyond 30 minutes, I think it's fair to allow consumers to specify how long the command should wait.

**Describe alternatives you've considered**
It's not really an "alternative", but a workaround is to wrap the command in some retry logic to retry it a set number of times. That's not a great solution though, as it can be difficult to tell a timeout error from the waiter vs an actual error in the deployment, which can result in extra wasted calls. Plus every user then has to potentially add this logic if their deploys take a while.

**Comment by kdaily** [comment] 2021-09-15 19:18
Hi @colvardrm2,

Thanks for contacting us! Currently, the only way you can configure your own waiter retry and timeout settings is to use the SDK - you can use the Python SDK, `boto3`, to accomplish this. Here's how you would do it for your use case and stretch it out to two hours (240 retries, wait 30 seconds in between):

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/codedeploy.html#CodeDeploy.Waiter.DeploymentSuccessful

```
import boto3
client = boto3.client('codedeploy')
waiter = client.get_waiter('deployment_successful')

response = waiter.wait(deploymentId='string',
                       WaiterConfig={'Delay': 30, 'MaxAttempts': 240})
```

This is essentially a duplicate of issue https://github.com/aws/aws-cli/issues/6157, so I'm going to close it. Please give a 👍🏻 feedback on the initial comment there to express your interest, and provide any other information. Thanks!

**Closed by kdaily** 2021-09-15 19:18 UTC
Labels: investigating, feature-request
