### ISSUE TITLE
Impossible to use cloudformation deploy when adding new parameters

### ISSUE THREAD

**Issue by jarruda** [aws/aws-cli#2873] opened 2017-10-06 00:32 UTC
If a new parameter is specified with a default parameter, and `cloudformation deploy` is used to **update** a stack, it will fail when creating the change set due to the command implicitly attempting to set the parameter to `UsePreviousValue=true` instead of detecting that 1/the parameter is new and 2/that it has a default set.

It is therefore impossible to use deploy when updating a stack when adding a new parameter with a default value (and not specify the parameter value).  Manually creating a change set and executing it is required.

**Comment by kyleknap** [comment] 2017-10-06 20:26
Looks like this is a duplicate of this issue: https://github.com/aws/aws-cli/issues/2599. We are looking into how to fix it. Let's track this problem in the original issue.

**Closed by kyleknap** 2017-10-06 20:26 UTC
Labels: duplicate
