### ISSUE TITLE
s3 sync with max_concurrent_requests

### ISSUE THREAD

**Issue by WeipingGuo** [aws/aws-cli#5303] opened 2020-06-18 01:47 UTC
Confirm by changing [ ] to [x] below:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

Issue is about usage on:
- [ ] Service API : I want to do X using Y service, what should I do?
- [x] CLI : passing arguments or cli configurations.
- [ ] Other/Not sure.

**Platform/OS/Hardware/Device**
What are you running the cli on?
```
aws --version
aws-cli/1.18.82 Python/2.7.9 Linux/3.16.0-10-amd64 botocore/1.17.5
```

**Describe the question**
I would like to improve the download throughput via max_concurrent_requests, here is the config i have
```
cat ~/.aws/config
[default]
s3 =
    max_concurrent_requests = 100
    max_queue_size = 10000
    max_bandwidth = 100MB/s
```
however when I run the `aws s3 sync`  and watch `lsof -i tcp:443`, the max established connections never gets above 20.  The CPU usage is low. 

Did I miss something? 

Thank you very much

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Comment by KaibaLopez** [comment] 2020-06-18 17:17
Hi @WeipingGuo ,
hmmm, ok so one thing here I'd like to point out is that the default limit is 10, so the fact that it is going above that tells me that your set up at least is correct.

Now, the number or concurrent requests is going to depend on a few things... The first thing that comes to mind is the size of the object you're trying to upload, for example:
An upload to s3 is usually divided in "parts" with default of 8mb and a minimum of 5mb, so if you're trying to upload objects with less than 160mb then by the time you hit 20 request there is no more to upload...
This is only one example though, it could also be just cpu usage or network bandwidth.

Let me know if you think it's none of those and I'll dig around a bit more.

**Comment by WeipingGuo** [comment] 2020-06-18 17:37
@KaibaLopez Thanks a lot for your response. I am trying to sync files from s3 to local EBS. The file size is small (less than 1KB). I would expect 100 concurrent connections to S3 endpoint though.

**Comment by KaibaLopez** [comment] 2020-06-24 20:47
Hi @WeipingGuo ,
Hmm, I think the main confusion is that the `max_concurrent_requests` is not meant to be "how many concurrent requests" but "maximum allowed concurrent requests", I don't think the s3 sync will try to use that many requests for small sized operations.

**Comment by kdaily** [comment] 2020-06-29 17:08
Hi @WeipingGuo,

I tried this using Python 3 to sync 750 small files and I immediately used 100 concurrent requests. I also tried using the latest Python 2.7 version (2.7.18) and also immediately used 100 requests.

I note that you are running a very old version of Python (2.7.9, released back in 2014). I haven't been able to reproduce this yet, I am having some trouble installing that version locally. I'll keep working on that as well.

Is it possible that you try to install a later version of Python? Python 2.7 is in 'end-of-life' maintenance support and will end support after the end of this year (2020) (reference: https://www.python.org/downloads/).

Thanks!

**Comment by kdaily** [comment] 2020-06-29 20:37
@WeipingGuo, could you also advise on the number of files that you are trying to sync? How many of these files are expected to have changed (e.g., the contents are different)?

**Comment by WeipingGuo** [comment] 2020-06-29 22:25
> @WeipingGuo, could you also advise on the number of files that you are trying to sync? How many of these files are expected to have changed (e.g., the contents are different)?
Hi @kdaily thanks for looking into the issue. So basically when new EC2 instance is launched, we are trying to download the whole bucke to EBS volume. Once the download is completed, we will put this into service. Since this is ASG instance, we are trying to maximize CPU and network bandwidth during initial launch.

**Comment by joseph-guo** [comment] 2020-07-06 22:20
Hi @kdaily , my name is Joe Guo, working with Weiping Guo on this. In the situation of downloading files, we'll need to download hundreds of thousands small files (1 KB or smaller) from S3 bucket to EBS volume. Since the instance is newly created, we'll need to download all the files from bucket.

I did some experiment with s3 sync on Linux (Debian, Python 3.6.1) and MAC (Python 3.6.6) and used "lsof -i tcp:443" to measure concurrent connections to S3. On Linux, the number of connections fluctuating between 10 and 20, while on MAC it is between 20 and 90. The AWS configuration in both cases are the same (max_concurrent_requests = 100, max_queue_size = 10000). So is s3 sync OS dependent? What would be the best way of increasing the throughput on running s3 sync? Thank you and appreciate your feedback.

**Comment by joseph-guo** [comment] 2020-07-10 12:55
Hi @kdaily , another question. During the test with S3 sync, we noticed that connection to S3 bucket seems created every time. Is there a way of re-using the connections? Thanks.

**Comment by kdaily** [comment] 2020-07-14 17:32
Hi @joseph-guo, thanks for the further information. I used an Amazon Linux 2 EC2 m5a.2xlarge instance, and I see concurrent requests fluctuate between 10 and 100. I used the scenario and code here to test:

https://aws.amazon.com/blogs/apn/getting-the-most-out-of-the-amazon-s3-cli/

I'm thinking that the time to transfer each 1KB file is so short that you won't see the connections quickly enough from `lsof`. I ran it a number of times - sometimes I would get fluctuation around 10-15, and sometimes it would go all the way up. Keep in mind that this controls the number of all requests that are needed to perform an S3 transfer, and not all of these are downloading parts of a file.

To answer your other question, the code powering the CLI's s3 transfer functions uses a connection pool to reuse connections.

I would suggest asking for advice in the AWS S3 forum to help optimize for your use case:

https://forums.aws.amazon.com/forum.jspa?forumID=24

I imagine you've seen some of the references already existing on this topic:

- https://aws.amazon.com/premiumsupport/knowledge-center/s3-improve-transfer-sync-command/
- https://docs.aws.amazon.com/AmazonS3/latest/dev/optimizing-performance.html
- https://aws.amazon.com/blogs/apn/getting-the-most-out-of-the-amazon-s3-cli/

From those, you can learn about when transferring to an EBS volume on an EC2, the instance type and EBS volume type are also going to have a large impact on how fast you can transfer this much data. How your data is structured in your S3 bucket will also have an impact. Since Python has limitations on multi-threading, in many cases running separate instances of the client to download different parts of the S3 bucket will probably be faster too.

**Comment by joseph-guo** [comment] 2020-07-15 12:41
@kdaily  Thanks!

**Closed** 2020-07-21 21:46 UTC
Labels: guidance, s3, s3sync
