### ISSUE TITLE
Versioned ZIP archives for AWS CLI v2

### ISSUE THREAD

**Issue by vranystepan** [aws/aws-cli#5123] opened 2020-04-12 07:01 UTC
**Is your feature request related to a problem? Please describe.**
For the deployment environment we're trying to build images with pinned versions of all the included software. AWS CLI v2 is distributed as https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip so the version of the CLI will change over the time. 

**Describe the solution you'd like**
Distribute AWS CLI v2 as versioned archive e.g. https://awscli.amazonaws.com/awscli-exe-linux-2.0.7-x86_64.zip

**Describe alternatives you've considered**
For the docker images I can use `COPY --from=amazon/aws-cli:2.0.7`. However, this is not doable for AMIs or similar stuff

**Additional context**

**Comment by Majkl578** [comment] 2020-04-13 13:49
Another quite popular open-source-friendly approach would be attaching the packages to GitHub Releases for your tags.

**Comment by jvanzyl** [comment] 2020-04-19 00:37
It would also be great if there were versioned zip files for all the platforms. The OSX installation mechanism really isn't very nice to use, especially trying to use an XML file to adjust the installation.

**Comment by joguSD** [comment] 2020-04-20 18:10
Duplicate of #5013. 

Versioned archives are already available, see my comment on the other thread here for the details: https://github.com/aws/aws-cli/issues/5013#issuecomment-594183882

@jvanzyl The PKG installer for macOS is the only CLI V2 artifact we release currently, which is also versioned. It sounds like you might be asking for something else other than the PKG? If so, you can open up another issue and we can discuss further there.

**Closed by joguSD** 2020-04-20 18:10 UTC
Labels: feature-request, needs-triage
