### ISSUE TITLE
exclude not working at all in s3 cp

### ISSUE THREAD

**Issue by the-black-wolf** [aws/aws-cli#7330] opened 2022-10-07 17:58 UTC
### Describe the bug

We moved our process to another machine and installed the latest AWS CLI and moved our script over, initialized access and ran the script, the script generates several txt files and uploads them to s3. The offending line is:

`aws s3 cp . s3://vode/aws/logic --recursive --exclude "*" --include "*.txt"`

This used to work and still works on the old box (the old box uses cli aws-cli/1.16.96 Python/3.6.0) and sends just txt files. On the new box it sends everything in the current folder. It completely ignores the exclude switch. I tried to find if command changed in v2, but as per documentation this should work. 

### Expected Behavior

Exclude working, and with subsequent include send only txt files. 

### Current Behavior

All files in the current folder and all subfolders gets uploaded. 

### Reproduction Steps

just a script in the description

### CLI version used

aws-cli/2.8.1 Python/3.9.11

### Environment details (OS name and version, etc.)

Windows/2012ServerR2 exe/AMD64 prompt/off

**Comment by aBurmeseDev** [comment] 2022-10-07 20:55
Hi @the-black-wolf, thanks for reaching out. 

I tried to reproduce with the same command to upload into my bucket and only the txt files were uploaded as expected. I couldn't find anything that's unusual, perhaps if you could share debug logs by adding `--debug` in your CLI command, we could check if there's anything interesting in the logs.

Here's `--exclude` `--include` examples with `aws cp` for your reference:
https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-managing-objects-param

Best,
John

**Comment by the-black-wolf** [comment] 2022-10-09 17:00
@aBurmeseDev I know, right? This is not some fringe scenario, this approach is documented and its used daily by thousands. Which is why its so frustrating. I'll run the debug mode in a moment and post here.

**Comment by the-black-wolf** [comment] 2022-10-09 19:22
Debug log -> [aws.debug.log](https://github.com/aws/aws-cli/files/9742394/aws.debug.log)

I think the problematic part is at the end:

```
2022-10-09 12:06:36,761 - MainThread - awscli.customizations.s3.filters - DEBUG - C:\[TVEXXXX] XXX Daily report\Job\xxx\ftp.log did not match exclude filter: C:\[TVEXXXX] XXX Daily report\Job\xxx\*
2022-10-09 12:06:36,761 - MainThread - awscli.customizations.s3.filters - DEBUG - C:\[TVEXXXX] XXX Daily report\Job\xxx\ftp.log did not match exclude filter: vode\aws\lorem\*
2022-10-09 12:06:36,761 - MainThread - awscli.customizations.s3.filters - DEBUG - C:\[TVEXXXX] XXX Daily report\Job\xxx\ftp.log did not match include filter: C:\[TVEXXXX] XXX Daily report\Job\xxx\*.txt
2022-10-09 12:06:36,761 - MainThread - awscli.customizations.s3.filters - DEBUG - C:\[TVEXXXX] XXX Daily report\Job\xxx\ftp.log did not match include filter: vode\aws\lorem\*.txt
2022-10-09 12:06:36,761 - MainThread - awscli.customizations.s3.filters - DEBUG - =C:\[TVEXXXX] XXX Daily report\Job\xxx\ftp.log final filtered status, should_include: True
```

The file should have been eliminated by the first exclude.

**Comment by the-black-wolf** [comment] 2022-10-09 20:08
@aBurmeseDev 

Actually, I just figured out what went wrong (and am glad I am not insane). You guys are using regular expressions without cleaning up the location prefix. The `[` and `]` characters are messing it up because they form a character class instead of being matched ad verbatim. When I removed the characters from the folder name, the filter started working. 

Since these characters are valid path characters, this is definitely a bug as aws-cli should handle such paths.  

Suggested solution would be that you escape all valid path characters in prefixes with `\` if they are special characters in regex.

**Comment by aBurmeseDev** [comment] 2022-10-10 18:24
@the-black-wolf - I'm very glad to hear that it's working for you now. I wanted to understand more and clarify what the issue was: were you saying that you had `[` and `]` in your file paths when you run the command? Could you elaborate more on that and perhaps point out a line in source code that's causing this issue?

I also found this issue that I think is somewhat related to what you experienced if you could take a look: https://github.com/aws/aws-cli/issues/6253

**Comment by the-black-wolf** [comment] 2022-10-11 08:19
@aBurmeseDev - yes, the `[` and `]` were in the path as one of the folder names (see my code block 3 messages up, the `[TVEXXXX]` part) and that is what caused the problem. It started working immediately after I removed them from the folder name, and as far as I can see its not related to #6253

Even though I solved my problem, I think this qualifies as a bug and should be solved by you guys, since `[` and `]` characters are valid path characters on both Win and Linux, I think its just a chance that I was the first one to stumble on it due to our naming convention. 

I do not know which line of code in the repo is causing the problem, I suspect the part where regular expression is constructed from prefix and exclude/include parameters and would require prefixing `[` and `]` with backslash to avoid accidentally constructing a regex character class from path string. This is just an educated guess on my part, and this is as far as I can help you.

**Comment by aBurmeseDev** [comment] 2022-11-15 23:09
@the-black-wolf - thanks for bringing it up to our attention. I created a backlog item for the team to further review and investigate. Since you were able to find the solution and resolve this issue, I will go ahead and close this now. Please let us know if you have any followup questions or concerns and again, thank you for contacting us!

**Closed by aBurmeseDev** 2022-11-15 23:09 UTC
Labels: s3, s3api, p2
