### ISSUE TITLE
Session Manager should come pre-installed in the awsl-cli docker image

### ISSUE THREAD

**Issue by fearphage** [aws/aws-cli#6248] opened 2021-06-25 22:01 UTC
## Issue

Docker images do not contain the [Session Manager plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html).

## Solution

The docker image should have the session manager preinstalled.

## Alternatives

There are various 1-line dockerfiles floating [around](https://gist.github.com/redmount/8fa8cda7d01a04282523641d321a87a2) the [web](https://hub.docker.com/r/jtbouse/aws-cli) that are the based on the AWS cli with the session manager added. This should be a part of the default install so no third-party images are required.

**Comment by stobrien89** [comment] 2021-06-28 16:20
Hi @fearphage,

Thanks for the feature request!

**Comment by stobrien89** [comment] 2021-06-29 17:31
Hey @fearphage,

Thanks again for the request.  It looks like this is a duplicate of #5373.  I did discuss this with the team today and it looks like something we would consider implementing as a separate image at some point in the future.

**Closed by stobrien89** 2021-06-29 17:31 UTC
Labels: docker, duplicate, feature-request
