### ISSUE TITLE
Problem parsing argument of function Fn::Base64 on Cloudformation templates

### ISSUE THREAD

**Issue by vmmello** [aws/aws-cli#913] opened 2014-09-15 23:51 UTC
Hi,

When using a Cloudformation template with aws-cli and having an object property defined like:
`
{
  "UserData"       : { "Fn::Base64" : { "Ref" : "BootScriptText" } }
}
`

I get a client error:
> A client error (ValidationError) occurred when calling the CreateStack operation: Template error: every Fn::Base64 object must have a String-typed value.

Though submitting the very same template through Cloudformation web interface it works.

To me it seems that aws-cli doesn't take into account that the Fn::Base64 function can receive a "Ref" as argument, as exemplified on page 13 of the [Cloudformation Bootstrapping doc](https://s3.amazonaws.com/cloudformation-examples/BoostrappingApplicationsWithAWSCloudFormation.pdf).

I tested it on:
> aws-cli/1.4.3 Python/2.6.6

**Comment by jamesls** [comment] 2015-01-14 19:30
Looking at the forum thread, it sounds like the root cause was found and there's no action needed on the CLI side.  Closing out issue.

**Closed by jamesls** 2015-01-14 19:30 UTC
Labels: response-needed
