### ISSUE TITLE
`aws -h` output should include mention of `help`

### ISSUE THREAD

**Issue by corneliusroemer** [aws/aws-cli#7648] opened 2023-02-08 16:27 UTC
### Describe the bug

When I type `aws -h` or generally `-h` after any subcommand like `aws s3 cp -h` I should be offered help on where to find more documentation. Either immediately as stdout or by telling me how to get man pages.

Instead, when typing the universal standard `-h` or `--help` one gets an unhelpful output that doesn't help at all by omitting the existence of `help` (without `--`).

### Expected Behavior

I expected that running

`aws -h` would return a mention of `aws help`:

```console:
$ aws -h
usage: aws [-h] [--profile PROFILE] [--debug] [help]

subcommands:
  help               show man pages for this subcommand <<-- line that is not present in current behavior

options:
  -h, --help         show this help message and exit
  --profile PROFILE
  --debug
```

Furthermore, use of `-h` on a subcommand should not trigger the base `aws` usage, but the subcommand usage:
```console
$ aws s3 cp -h
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters] [help]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
```

### Current Behavior

```console
$ aws -h       
usage: aws [-h] [--profile PROFILE] [--debug]

options:
  -h, --help         show this help message and exit
  --profile PROFILE
  --debug
```
-> no mention at all of `help`, it's a self-referential loop, no way to guess `help` without StackOverflow etc (see https://stackoverflow.com/questions/75388596/how-to-get-meaningful-help-pages-for-aws-subcommands-like-aws-s3-cp/75388618#75388618)

```console
$ aws s3 cp -h    
usage: aws [-h] [--profile PROFILE] [--debug]

options:
  -h, --help         show this help message and exit
  --profile PROFILE
  --debug
```

### Reproduction Steps

```bash
aws -h
```

```bash
aws s3 cp -h
```

### Possible Solution

First step: mention `help` in `aws -h` output explicitly

Second step: make subcommand help show instead of generic CLI output when running `aws s3 cp -h` and other subcommands with `-h`

### CLI version used

aws-cli/2.9.19 Python/3.11.1 Darwin/22.3.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 13.2, M1 Pro

**Comment by tim-finnigan** [comment] 2023-02-09 17:25
Hi @corneliusroemer thanks for creating this issue. I agree with you that `-h` and `--help` are not very helpful. This actually came up here in a recent issue as well: https://github.com/aws/aws-cli/issues/7629. I want to highlight the `help` documentation again for visibility: https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-help.html#cli-usage-help-command.

In https://github.com/aws/aws-cli/issues/7629 we discussed some possibilities going forward. Ultimately I closed that issue as a duplicate of https://github.com/aws/aws-cli/issues/303, as we try to consolidate overlapping issues to help with tracking. We recommend adding a 👍 to that issue and sharing any comments there if you'd like. The 👍 reactions and comments can help the team assess prioritization.

**Closed by tim-finnigan** 2023-02-09 17:25 UTC
Labels: bug, needs-triage
