### ISSUE TITLE
Upgrading packages caused install loop between awscli and botocore

### ISSUE THREAD

**Issue by alper** [aws/aws-cli#7101] opened 2022-07-12 11:36 UTC
### Describe the bug

I don't think this is supposed to happen but just now upgrading my system python packages it went into a backtracking loop between awscli and botocore I guess because it could not figure out how to satisfy dependencies.

### Expected Behavior

I expected a clean upgrade.

### Current Behavior

It spent 10-15 minutes downloading older and older versions of both packages to see if it could satisfy but I think in the end it could not.

### Reproduction Steps

Not sure how. This is the output of `pip list` after this happened:

```
Package                           Version
--------------------------------- -------------------
absl-py                           1.1.0
adb-shell                         0.4.3
aiohttp                           3.8.1
aiosignal                         1.2.0
ansible-base                      2.10.17
anyio                             3.6.1
apispec                           5.2.2
appdirs                           1.4.4
appnope                           0.1.3
argcomplete                       2.0.0
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.2
asgiref                           3.5.2
astor                             0.8.1
asttokens                         2.0.5
astunparse                        1.6.3
async-generator                   1.10
async-timeout                     4.0.2
attrs                             21.4.0
Automat                           20.2.0
aws-google-auth                   0.0.38
awscli                            1.11.18
backcall                          0.2.0
backports.entry-points-selectable 1.1.1
bcrypt                            3.2.2
beautifulsoup4                    4.11.1
binaryornot                       0.4.4
biplist                           1.0.3
black                             22.6.0
bleach                            5.0.1
blis                              0.9.0
boto                              2.49.0
boto3                             1.4.3
botocore                          1.4.75
CacheControl                      0.12.11
cachetools                        5.2.0
cachy                             0.3.0
catalogue                         2.0.7
certifi                           2022.6.15
cffi                              1.15.1
chardet                           5.0.0
charset-normalizer                2.1.0
clang                             14.0
cleo                              0.8.1
click                             8.1.3
clikit                            0.6.2
colorama                          0.3.7
colorclass                        2.2.2
commonmark                        0.9.1
configparser                      5.2.0
constantly                        15.1.0
crashtest                         0.3.1
cryptography                      37.0.4
cymem                             2.0.6
debugpy                           1.6.2
decorator                         5.1.1
deepdiff                          5.8.1
defusedxml                        0.7.1
dill                              0.3.5.1
distlib                           0.3.4
dnslib                            0.9.19
dnspython                         2.2.1
docker                            5.0.3
docopt                            0.6.2
docutils                          0.19
dotty-dict                        1.3.1
dulwich                           0.20.44
ecdsa                             0.18.0
entrypoints                       0.4
executing                         0.8.3
fastjsonschema                    2.15.3
filelock                          3.7.1
flatbuffers                       2.0
frozenlist                        1.3.0
funcparserlib                     1.0.0
gast                              0.5.3
Geometry3D                        0.2.4
google-api-core                   2.8.2
google-api-python-client          2.52.0
google-auth                       2.9.0
google-auth-httplib2              0.1.0
google-auth-oauthlib              0.5.2
google-pasta                      0.2.0
googleapis-common-protos          1.56.3
gql                               3.3.0
graphql-core                      3.2.1
grpcio                            1.47.0
h11                               0.13.0
h5py                              3.7.0
halo                              0.0.31
hid                               1.0.5
hjson                             3.0.2
html5lib                          1.1
httplib2                          0.20.4
hy                                0.24.0
hyperlink                         21.0.0
idna                              3.3
importlib-metadata                4.12.0
incremental                       21.3.0
iniconfig                         1.1.1
invoke                            1.7.1
iOSbackup                         0.9.923
ipykernel                         6.15.1
ipython                           8.4.0
ipython-genutils                  0.2.0
ipywidgets                        7.7.1
isort                             5.10.1
jedi                              0.18.1
Jinja2                            3.1.2
jinja2-time                       0.2.0
jmespath                          0.10.0
jsonschema                        4.7.2
jupyter                           1.0.0
jupyter-client                    7.3.4
jupyter-console                   6.4.4
jupyter-core                      4.11.1
jupyterlab-pygments               0.2.2
jupyterlab-widgets                1.1.1
keras                             2.9.0
keras-nightly                     2.5.0.dev2021032900
Keras-Preprocessing               1.1.2
keyring                           23.6.0
keyrings.alt                      4.1.0
langcodes                         3.3.0
libclang                          14.0.1
libusb1                           3.0.0
localstack                        0.14.5
localstack-client                 1.35
localstack-ext                    0.14.5
localstack-plugin-loader          1.1.1
lockfile                          0.12.2
log-symbols                       0.0.14
lxml                              4.9.1
Markdown                          3.3.7
MarkupSafe                        2.1.1
matplotlib-inline                 0.1.3
mccabe                            0.7.0
milc                              1.6.6
mistune                           2.0.3
mpmath                            1.2.1
msgpack                           1.0.4
multidict                         6.0.2
murmurhash                        1.0.7
mvt                               2.0.1
mypy                              0.961
mypy-extensions                   0.4.3
nbclient                          0.6.6
nbconvert                         6.5.0
nbformat                          5.4.0
nest-asyncio                      1.5.5
notebook                          6.4.12
NSKeyedUnArchiver                 1.5
numpy                             1.23.1
oauth2client                      4.1.3
oauthlib                          3.2.0
opt-einsum                        3.3.0
ordered-set                       4.1.0
outcome                           1.2.0
packaging                         21.3
pandas                            1.4.3
pandocfilters                     1.5.0
paramiko                          2.11.0
parso                             0.8.3
pastel                            0.2.1
pathlib2                          2.3.7.post1
pathspec                          0.9.0
pathy                             0.6.2
pbr                               5.9.0
pexpect                           4.8.0
pickleshare                       0.7.5
Pillow                            9.2.0
pip                               22.1.2
pip-check                         2.7
pkginfo                           1.8.3
platformdirs                      2.5.2
pluggy                            1.0.0
plux                              1.3.1
poetry                            1.1.14
poetry-core                       1.0.8
poyo                              0.5.0
preshed                           3.0.6
prometheus-client                 0.14.1
prompt-toolkit                    3.0.30
protobuf                          4.21.2
psutil                            5.9.1
ptyprocess                        0.7.0
pure-eval                         0.2.2
py                                1.11.0
pyaes                             1.6.1
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.8.0
pycparser                         2.21
pycryptodome                      3.15.0
pydantic                          1.9.1
pyflakes                          2.4.0
Pygments                          2.12.0
PyJWT                             2.4.0
pylev                             1.4.0
PyNaCl                            1.5.0
pyparsing                         3.0.9
pyrsistent                        0.18.1
pytest                            7.1.2
python-dateutil                   2.8.2
python-dotenv                     0.20.0
python-jose                       3.3.0
python-slugify                    6.1.2
pytz                              2022.1
pytz-deprecation-shim             0.1.0.post0
pyusb                             1.2.1
pywin32-ctypes                    0.2.0
PyYAML                            6.0
pyzmq                             23.2.0
qtconsole                         5.3.1
QtPy                              2.1.0
requests                          2.28.1
requests-oauthlib                 1.3.1
requests-toolbelt                 0.9.1
rich                              12.5.1
rply                              0.7.8
rsa                               3.4.2
s3transfer                        0.1.13
scipy                             1.8.1
semver                            2.13.0
Send2Trash                        1.8.0
setuptools                        63.1.0
setuptools-scm                    7.0.5
shellingham                       1.4.0
simplejson                        3.17.6
six                               1.16.0
smart-open                        6.0.0
sniffio                           1.2.0
sortedcontainers                  2.4.0
soupsieve                         2.3.2.post1
spacy                             3.3.1
spacy-legacy                      3.0.9
spacy-loggers                     1.0.2
spinners                          0.0.24
sqlparse                          0.4.2
srsly                             2.4.3
stack-data                        0.3.0
starlette                         0.20.4
stevedore                         3.5.0
sympy                             1.10.1
tabulate                          0.8.10
tailer                            0.4.1
tensorboard                       2.9.1
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
tensorflow                        2.9.1
tensorflow-estimator              2.9.0
tensorflow-io-gcs-filesystem      0.26.0
termcolor                         1.1.0
terminado                         0.15.0
terminaltables                    3.1.10
testpath                          0.6.0
text-unidecode                    1.3
tf-estimator-nightly              2.8.0.dev2021122109
thinc                             8.1.0
things-cli                        0.1.4
things.py                         0.0.14
tinycss2                          1.1.1
tld                               0.12.6
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
torch                             1.12.0
tornado                           6.2
tqdm                              4.64.0
traitlets                         5.3.0
trio                              0.21.0
Twisted                           22.4.0
typed-ast                         1.5.4
typer                             0.5.0
typing_extensions                 4.3.0
tzdata                            2022.1
tzlocal                           4.2
uritemplate                       4.1.1
urllib3                           1.26.10
uvicorn                           0.18.2
virtualenv                        20.15.1
wasabi                            0.9.1
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.3.3
websockets                        10.3
Werkzeug                          2.1.2
wheel                             0.37.1
widgetsnbextension                3.6.1
wrapt                             1.14.1
yarl                              1.7.2
youtube-dl                        2021.12.17
z3-solver                         4.9.1.0
zipp                              3.8.0
zipper                            0.0.3
zope.interface                    5.4.0
```

### CLI version used

1.11.18

### Environment details (OS name and version, etc.)

macOS

**Comment by nateprewitt** [comment] 2022-07-12 15:44
Hi @alper,

Installing Boto3 and the CLI in the same environment require the same version of Botocore. This either requires manually pinning the equivalent versions, or the preferred approach is to install them in separate virtual environments.

The [CLI v2](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) is also available now which provides an isolated installation of the CLI, avoiding these issues entirely.

For the backtracking, it sounds like you have an old version of `pip` installed. Most of their dependency resolvers backtracking issues were resolved in `pip>=22.0` which should avoid long resolution cycles like you're experiencing.

**Comment by alper** [comment] 2022-07-12 16:04
My pip version is: `pip 22.1.2`

But good to know about the v2 of the CLI. I'll get on that.

(I was just curious because this is the first time I've seen this happen in quite a long time that I've been doing this.)

**Comment by nateprewitt** [comment] 2022-07-12 21:11
> (I was just curious because this is the first time I've seen this happen in quite a long time that I've been doing this.)

That's very interesting if this is happening with `pip 22`, this is the first instance I'm aware of since the changes were made.

To make sure we have the reproduction steps what is the exact `pip` command that was used, and if it relies on a requirements/lockfile, can you provide that? Thanks!

**Comment by alper** [comment] 2022-07-15 10:42
Ehm. It's just my system global installed packages.

I think it must be this command or similar:
```
pip3 install --upgrade awscli black boto3 botocore cffi colorama dill docutils dulwich google-api-python-client google-auth jsonschema nbclient pathy requests rsa setuptools-scm starlette torch virtualenv cachetools chardet idna mistune PyYAML
```

I don't think I can piece together a before state of the version numbers.

(Feel free to close this if it's not productive. Maybe somebody else will run into something like this as well.)

**Comment by nateprewitt** [comment] 2022-07-15 17:27
Ok, no worries. Given how old the installed versions are, I'm wondering if we have some bad metadata that's short circuiting `pip`'s resolution mechanism. We won't be able to update those older versions, and I think the guidance of isolating the CLI or moving to CLI v2 will still remain.

Thanks again for reaching out about this, I'll resolve for now unless we hear back with more cases like this.

**Closed by nateprewitt** 2022-07-15 17:27 UTC
Labels: guidance
