### ISSUE TITLE
Resource completion fails with missing region but region is defined in profile

### ISSUE THREAD

**Issue by ccayg-sainsburys** [aws/aws-cli#5037] opened 2020-03-04 21:36 UTC
```
aws --version
aws-cli/2.0.0 Python/3.8.1 Darwin/19.3.0 botocore/2.0.0dev4
```

With this:
```
aws --profile PROFILENAME configure list
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile           PROFILENAME           manual    --profile
access_key     ******************** shared-credentials-file
secret_key     ******************** shared-credentials-file
    region                eu-west-1      config-file    ~/.aws/config
```

This works:
```
aws --profile PROFILENAME dynamodb list-tables
```

As does this:
```
aws --profile PROFILENAME dynamodb describe-table --table-name TABLENAME
```

But:
```
aws --profile PROFILENAME dynamodb describe-table --table-name <TAB>
```

fails with
```
Traceback (most recent call last):
  File "/usr/local/bin/aws_completer", line 36, in <module>
    main()
  File "/usr/local/bin/aws_completer", line 28, in main
    autocomplete(command_line, command_index)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/awscli/autocomplete/main.py", line 61, in autocomplete
    results = completer.autocomplete(command_line, position)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/awscli/autocomplete/completer.py", line 44, in autocomplete
    result = completer.complete(parsed)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/awscli/autocomplete/serverside/servercomp.py", line 94, in complete
    raw_results = self._retrieve_remote_completion_data(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/awscli/autocomplete/serverside/servercomp.py", line 112, in _retrieve_remote_completion_data
    client = self._client_creator.create_client(service_name)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/awscli/autocomplete/serverside/servercomp.py", line 58, in create_client
    return self._session.create_client(service_name, **kwargs)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/session.py", line 807, in create_client
    client = client_creator.create_client(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 78, in create_client
    client_args = self._get_client_args(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 170, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 47, in get_client_args
    final_args = self.compute_client_args(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 123, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 192, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/args.py", line 214, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 245, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/regions.py", line 121, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

The same is not true if this is done:
```
export AWS_PROFILE=PROFILENAME
aws dynamodb describe-table --table-name <TAB>
```

**Comment by KaibaLopez** [comment] 2020-03-05 20:14
hi @ccayg-sainsburys ,
 I have not been able to reproduce the error, do you get that as soon as you press tab? or when does it happen?
But server side auto-complete doesn't consider `--profile "profilename"` that is not part of the feature at the moment, that's why you must set AWS_PROFILE with the profile name you want it to use, or manually type the resource name.

**Comment by ccayg-sainsburys** [comment] 2020-03-06 11:30
yes, on pressing tab (with some delay as, I presume, a request is fired in the background)

Then, docs might be useful...
https://aws.amazon.com/blogs/developer/aws-cli-v2-is-now-generally-available/
for example makes no mention of requirement for AWS_PROFILE?

**Comment by KaibaLopez** [comment] 2020-03-06 20:04
Hi @ccayg-sainsburys, 
Ok, I was able to reproduce this, it's basically not finding a profile to use, I'll mark it as a bug because I believe it should either silently fail to find a resource, or at least return a more specific less verbose error message than "no region".
So far I think the auto complete follows the standard credential chain Instance< env variable< config file's [default] profile.
And yea documentation is something we are working on, specially for the server autocomplete, for the specific case of AWS_PROFILE, it's not so much that is a requirement, but rather it's how you would decide which profile name the auto completer looks for.

**Comment by stobrien89** [comment] 2021-02-25 01:18
Unable to reproduce using either the latest CLI version or CLI version 2.0.0.  Closing for now.

**Closed by stobrien89** 2021-02-25 01:18 UTC
Labels: bug, configuration, confusing-error, documentation
