### ISSUE TITLE
aws s3 ls/cp/put 'AWSHTTPSConnection' object has no attribute 'ssl_context'

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-cli#3330] opened 2018-05-17 19:16 UTC
Hi. I am just receiving this error on any s3 operation: 'AWSHTTPSConnection' object has no attribute 'ssl_context'

What does it means?

**Comment by joguSD** [comment] 2018-05-17 19:33
I'm going to assume you installed the CLI via `apt-get`. See this issue for reference:
https://github.com/boto/botocore/issues/1258

I'd suggest uninstalling the AWS CLI via your system package manager and use one of our bundled installers:
https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html

Closing as a duplicate of the above.

**Closed by joguSD** 2018-05-17 19:33 UTC

**Comment by neoacevedo** [comment] 2018-05-17 20:41
I'm using openSUSE Tumbleweed so no, I didn't installed it via apt-get. I forgot to say it in my first comment.

**Comment by joguSD** [comment] 2018-05-17 21:28
Did you install the CLI via pip or via SUSE's package manager? I'm guessing it's a similar issue as ubuntu where our vendored dependencies are being removed in favor of the system installed ones.

**Comment by neoacevedo** [comment] 2018-05-17 21:54
Maybe can be that. In the closed issue https://github.com/aws/aws-cli/issues/3092 was some related with the package in favor of the system. I was solved but now I am having this new one.

**Comment by joguSD** [comment] 2018-05-17 22:38
Yep, that does seem related, along with the downstream ticket in suse [here](https://bugzilla.opensuse.org/show_bug.cgi?id=1092493https://bugzilla.opensuse.org/show_bug.cgi?id=1092493).

As we don't maintain that package (the SUSE team does) we won't be able to help much here.
