### ISSUE TITLE
`aws sso login` Opens Browser (No Override Option)

### ISSUE THREAD

**Issue by hicklemon** [aws/aws-cli#6313] opened 2021-08-03 14:28 UTC
Presently, the `aws sso login` command opens the user's browser. Unfortunately, in my case, it automatically opens the most recently activated Google Chrome profile -- not the window in which I am using the AWS console. Thus, I am unable to authenticate until I inconveniently close out the entire other window.

The expected behavior would be either to ask, or to simply prompt the user to copy and paste the URL, rather than trying to open the browser and breaking the login. Alternatively, having a `--manual` option would help, wherein the user would be required to manually copy `https://device.sso.us-east-1.amazonaws.com/` into a browser tab (allowing them to choose the correct browser, profile and session), as well as the 8-character code.

aws-cli/2.2.25 Python/3.8.8 Linux/5.13.7-arch1-1 exe/x86_64.arch prompt/off

**Comment by onitake** [comment] 2021-08-04 08:19
Duplicate of https://github.com/aws/aws-cli/issues/5301

**Closed** 2021-08-04 15:18 UTC
Labels: needs-triage

**Comment by ericpardee** [comment] 2022-09-27 15:58
I don't think this is a duplicate actually.
[#5301](https://github.com/aws/aws-cli/issues/5301) is referring to the aws config profile, not the chrome profile.

I looks like the python library webbrowser supports [remote_args](https://github.com/python/cpython/blob/dd53b79de0ea98af6a11481217a961daef4e9774/Lib/webbrowser.py#L212) and you can pass in a chrome profile_directory, as shown [here](https://www.programcreek.com/python/example/120459/webbrowser.Chrome):
``` python
def _make_chrome(path):
    new_chrome = webbrowser.Chrome()
    new_chrome.name = path
    profile_directory = tempfile.mkdtemp()
    with open(os.path.join(profile_directory, "First Run"), "wb") as firstrun:
        # This file existing prevents prompts to make the new profile directory
        # the default
        firstrun.flush()
    new_chrome.remote_args = webbrowser.Chrome.remote_args + [
        '--user-data-dir="{}"'.format(profile_directory),
        "--no-first-run",
    ]
    return new_chrome 
```
This said, I can't find `webbrowser` in [aws-cli](https://github.com/aws/aws-cli) so maybe this is outdated.

Either way, would like to be able to specify a `aws sso login` chrome profile directory name.

**Comment by delta2112** [comment] 2023-10-19 09:31
Have you found any solution for this? If yes, please share. I have the exact same problem where I'm using different chrome profiles for different uses (work, personal, etc.) and they all log in to different AWS accounts.

Thank you!

**Comment by onitake** [comment] 2023-10-19 22:11
There are solutions for this.
You can use `BROWSER="" aws sso login` and manually open the link in whichever browser or browser session you like.

If you're a Firefox user, you can use the [multi-account container extension](https://support.mozilla.org/en-US/kb/containers) to assign a different container to each SSO URL. When executing `aws sso login`, the browser would then reopen the tab in the assigned container. I'm not sure if there's a similar extension for Chrome or other browsers.

**Comment by delta2112** [comment] 2023-10-20 07:19
Thank you for the reply!
Starting from your message, I built it up a bit further. For anyone else searching for this, I'll add my code of my `~/bin/sso` file.

I'll start by saying, I have a `~/bin` folder in my search `PATH`, and, of course, the file is `chmod +x`.

`
#!/bin/bash

set -u           # Treat unset variables as an error, and immediately exit
set -o pipefail  # Exit if any command in a pipeline errors
set -e           # Fail if a normal command fails

##############################################################################
# Utils:
# cat ~/.config/google-chrome/Local\ State  | jq .profile.last_active_profiles

# FILE: ~/bin/chrome3 (chmod +x ~/bin/chrome3):
# #!/bin/bash
# google-chrome --profile-directory="Profile 3" $@

# FILE: ~/bin/chrome4 (chmod +x ~/bin/chrome4):
# #!/bin/bash
# google-chrome --profile-directory="Profile 4" $@

# FILE: ~/bin/chrome5 (chmod +x ~/bin/chrome5):
# #!/bin/bash
# google-chrome --profile-directory="Profile 5" $@
##############################################################################

PROJECT1=proj1
PROJECT2=proj2
PROJECT3=proj3

PROJECT_LIST="${PROJECT1} ${PROJECT2} ${PROJECT3}"
PROJECT=$1

isIn() {
   [[ $2 =~ (^|[[:space:]])$1($|[[:space:]]) ]] && return 0 || return 1
}

if ! $(isIn "${PROJECT}" "${PROJECT_LIST}"); then
   echo "Unsupported Project: ${PROJECT}"
   exit -1
fi

if [ "X${PROJECT}" == "X${PROJECT1}" ]; then
    export BROWSER=chrome5
elif [ "X${PROJECT}" == "X${PROJECT2}" ]; then
    export BROWSER=chrome3
elif [ "X${PROJECT}" == "X${PROJECT3}" ]; then
    export BROWSER=chrome4
fi

aws sso login --sso-session ${PROJECT}-session
`
Then you just use it like `sso proj2` it will magically navigate workspaces and open a new tab in the already open chrome profile window.

I should also mention that I use "sessions" in my `~/.aws/config` as I have multiple roles for the accounts I'm working with.

Good luck AWS-ing!
