### ISSUE TITLE
aws s3 sync --delete option not deleting folders creating manually on console

### ISSUE THREAD

**Issue by akumar-99** [aws/aws-cli#7098] opened 2022-07-11 16:14 UTC
### Describe the bug

I have a scenario wherein someone created directories inside S3 using AWS console and put in some files inside those directories using manual upload. So now when I run the sync command, those files get removed but the manually created directories still persist.

### Expected Behavior

The manually created directories should also be deleted after the command execution.

### Current Behavior

The manually created directories persist after the command execution.

### Reproduction Steps

1. Create a S3 bucket.
2. Create a folder inside S3 using AWS console.
3. Upload some files inside the directory.
4. Run **aws s3 sync \<localpath\> \<s3URI\> --delete**

### Additional Information/Context

All the manually uploaded files even the ones inside these directories get deleted.

### CLI version used

aws-cli/2.6.1

### Environment details (OS name and version, etc.)

macOS Monterey 12.4

**Comment by tim-finnigan** [comment] 2022-07-12 18:08
Hi @akumar-99 thanks for reaching out. This is actually a duplicate of https://github.com/aws/aws-cli/issues/2685 so I’m going to close the issue and we can continue tracking it there. Please 👍 the issue or leave a comment if you have anything additional to add as far as how this is affecting your workflows. There are workarounds mentioned in that issue but a fix would require new logic being added to the s3 sync command.

**Closed by tim-finnigan** 2022-07-12 18:08 UTC
Labels: bug, duplicate, s3sync

**Comment by paul-uz** [comment] 2022-07-25 08:25
> Hi @akumar-99 thanks for reaching out. This is actually a duplicate of https://github.com/aws/aws-cli/issues/2685 so I’m going to close the issue and we can continue tracking it there. Please 👍 the issue or leave a comment if you have anything additional to add as far as how this is affecting your workflows. There are workarounds mentioned in that issue but a fix would require new logic being added to the s3 sync command. 

Problem is, the issue isn't being addressed. It's been 5 years now...
