### ISSUE TITLE
`aws codeartifact login --tool dotnet *` Fails with `list index out of range`

### ISSUE THREAD

**Issue by JCKortlang** [aws/aws-cli#7328] opened 2022-10-06 18:34 UTC
### Describe the bug

```
aws codeartifact login --tool dotnet --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
```

 Fatals with `list index out of range`

As described in, https://docs.aws.amazon.com/codeartifact/latest/ug/nuget-cli.html

Note that the same command using `--tool nuget` succeeds.

```
aws codeartifact login --tool nuget --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
```

### Expected Behavior

```
aws codeartifact login --tool dotnet --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
``` 

Successful login to the ECR repository and NuGet credential updated

### Current Behavior

```
aws codeartifact login --tool dotnet --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
``` 

Fatals with `list index out of range`.

Debug response indicates a valid response.

```
{"repositoryEndpoint":"https://<redacted>-<redacted>.d.codeartifact.us-west-2.amazonaws.com/nuget/<redacted>/"}
```

```
2022-10-06 11:17:17,602 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"repositoryEndpoint":"https://<redacted>-<redacted>.d.codeartifact.us-west-2.amazonaws.com/nuget/<redacted>/"}'
2022-10-06 11:17:17,602 - MainThread - botocore.hooks - DEBUG - Event needs-retry.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7fe9d86161f0>>
2022-10-06 11:17:17,602 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2022-10-06 11:17:17,602 - MainThread - botocore.hooks - DEBUG - Event after-call.codeartifact.GetRepositoryEndpoint: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x7fe9d85d0be0>>
2022-10-06 11:17:18,038 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 458, in main
  File "awscli/clidriver.py", line 593, in __call__
  File "awscli/customizations/commands.py", line 191, in __call__
  File "awscli/customizations/codeartifact/login.py", line 663, in _run_main
  File "awscli/customizations/codeartifact/login.py", line 122, in login
  File "awscli/customizations/codeartifact/login.py", line 201, in _get_source_to_url_dict
IndexError: list index out of range

list index out of range
```

### Reproduction Steps

1. Install AWS CLI
2. Install dotnet SDK
3. Create ECR repository
4. Setup AWS profile with credentials / artifacts access role. e.g. `artifacts`
5. Use AWS profile to attempt to log into the created ECR repositroy

```
dotnet --version
6.0.400

aws --version
aws-cli/2.7.35 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off

aws codeartifact login --tool dotnet --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
```

### CLI version used

aws-cli/2.7.35 Python/3.9.11 Darwin/21.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS 12.6 (21G115)

**Comment by mmarston** [comment] 2022-10-06 22:34
I suspect this is related to the welcome message output by the `dotnet` command the first time it is run after installation. 

See [this comment](https://github.com/aws/aws-cli/issues/6197#issuecomment-854301631) on #6197.

**Comment by aBurmeseDev** [comment] 2022-10-06 22:55
@JCKortlang, thanks for checking in. As @mmarston mentioned, https://github.com/aws/aws-cli/issues/6197 was a similar issue and the solution was to add `dotnet nuget list source --format detailed` before `aws codeartifact login`.

I'm going to follow up with codeartifact team internally on the error handling improvement there. Please feel free to close the issue if it resolved the issue.

**Comment by JCKortlang** [comment] 2022-10-07 17:08
The work around described in #6197 does not work in my case. I have tried by running,

```
dotnet nuget list source --format detailed && aws codeartifact login --tool dotnet --repository ** --domain ** --domain-owner ** --profile artifacts --region ** --debug
```

**Comment by aBurmeseDev** [comment] 2022-10-07 17:53
Followed up with codeartifact team internally. I'll post the outcome/update here.

P48141609

**Comment by NataliaAn** [comment] 2022-10-17 09:55
I am having the same issue with dotnet. Is there any update on the fix or when we could expect it?

**Comment by aBurmeseDev** [comment] 2022-10-17 16:31
Hi @NataliaAn, thanks for reporting. Have you tried the workaround mentioned in https://github.com/aws/aws-cli/issues/6197#issuecomment-854164399 to run `dotnet nuget list source --format detailed` before `aws codeartifact login`? Please let me know if that resolves it for you and I'm going to follow up on this issue internally as well.

**Comment by NataliaAn** [comment] 2022-10-18 08:24
Hello @aBurmeseDev,

Yes, I have tried all the suggestions above including the one you list here and I keep seeing the same unfortunately.

**Comment by aBurmeseDev** [comment] 2022-10-20 16:19
@NataliaAn, thanks for confirming. I'm still waiting to hear back from the team and will post an update once I hear back.

**Comment by JCKortlang** [comment] 2022-10-20 20:15
@NataliaAn Do you have an `http` repository configured in NuGet? If so, this causes the command to fail because it introduces an unexpected warning message into the output which fatals the brittle CLI code.

From an internal discussion;

> The login --tool dotnet command invokes the dotnet nuget list source --format detailed command and parses the output. **It is the dotnet command that is outputting the warning, and it is the warning that causes the login command to fail to parse the output.**

Work arounds:
1. Use `aws codeartifact login --tool nuget *`
2. Remove the `http`repository from your nuget configuration
3. Reconfigure the repository that you are trying to log into and manually log in to the code artifact repository via the CLI.

For 3:

```
88665a01e0b6 % cat ~/.nuget/NuGet/NuGet.Config 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="awsdomain/https-repo" value="https://<domain>/nuget/<httpsRepo>/v3/index.json" />
        <add key="my/http-repo" value="http://<domain>/nuget" />
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    </packageSources>
    <packageSourceCredentials>
        <awsdomain_x002F_https-repo>
            <add key="Username" value="aws" />
            <add key="ClearTextPassword" value="%MY_HTTPS_REPO_TOKEN%" />
        </awsdomain_x002F_https-repo>
  </packageSourceCredentials>
</configuration>
```

```
#Set `%MY_HTTPS_REPO_TOKEN%` daily by logging in with...
export MY_HTTPS_REPO_TOKEN=$(aws codeartifact get-authorization-token --domain awsdomain --profile artifacts --region us-west-2 |  jq -r '.authorizationToken')
```

**Comment by NataliaAn** [comment] 2022-10-21 14:44
@JCKortlang Thank you for the detailed message. No HTTP used here, third solution is not possible either cause I try to automate instead of adding it manually. I am going to give it a go with the first solution again (as I tried it and gave me some errors before too) and see if I can work things out.

I guess if the cause is the warning message, this is something that codeartifact team should be able to catch and handle. I'll be waiting for an update from @aBurmeseDev 's side too about this.

**Comment by aBurmeseDev** [comment] 2022-10-26 17:22
@NataliaAn, thanks for your patience. I heard back from the team and it might overlaps to workarounds @JCKortlang mentioned above. 

The first workaround to try is running `dotnet nuget list source --format detailed`. That only solves the issue when it is caused by the dotnet CLI's welcome message output on first use (that is usually only observed as a problem in a CI build environment). 
Another workaround is to install the nuget CLI (this is only an option for Windows users) and then run the `aws codeartifact login` command with `--tool nuget` instead of `--tool dotnet`. After successful login the dotnet CLI commands can be used with CodeArtifact. This works because the nuget CLI and dotnet CLI use the same configuration files for nuget sources (repositories).

The issue for @JCKortlang is caused by an HTTP URL (not HTTPS) in his configuration, and the dotnet nuget command outputs a warning in that case, and the login command doesn't properly handle the warning when parsing the output.
The team has a backlog item to fix the parsing. While we do not have definite timeline on the fix, I can definitely post an update here when the fix is deployed.  

Please let me know if you have any other questions or concerns.

**Comment by NataliaAn** [comment] 2022-10-31 16:57
Hello,

Apologies for the delay. I finally managed to work it out with '-tool nuget' as well. Thank you both for your input in this.

**Closed** 2022-10-31 18:27 UTC
Labels: codeartifact login, customization

**Comment by hermesjimenez** [comment] 2023-05-29 16:18
The error message **list index out of range**  problem was the warning message that shows this command : 
`dotnet nuget list source --format detailed`

> warn message
> `warn : You are running the 'list source' operation with an 'HTTP' source, '{NugetSourceName} [http://{host_nuger}nuget/]'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.`

Just remove or change the source with http in order to prevent the warn message. 

`aws codeartifact login --tool dotnet --repository`
