### ISSUE TITLE
Command resourcegroupstaggingapi get-resources do not return Resources with empty Tags list

### ISSUE THREAD

**Issue by yambrosov** [aws/aws-cli#6417] opened 2021-09-22 15:31 UTC
**Describe the bug**
An aws account some resources exists without Tag. It is not possible to see it in teh list of resources but documentation for the api says it should return.

**SDK version number**
aws --version
aws-cli/2.2.39 Python/3.8.8 Linux/4.19.0-9-amd64 exe/x86_64.debian.11 prompt/off
~/.aws/config
[profile profile_name]
region = eu-central-1
output = yaml

**Platform/OS/Hardware/Device**
Ubuntu

**To Reproduce (observed behavior)**
Run such command, it return ResourceTagMappingList with resources with configured Tag

aws --profile profile_name resourcegroupstaggingapi get-resources --tag-filters --region eu-central-1

**Expected behavior**
On was account we have more no tagged resources

**Logs/output**
ResourceTagMappingList:
- ResourceARN: arn:aws:ec2:eu-central-1:***:dhcp-options/dopt-9ba836f1
  Tags:
  - Key: no-tag
    Value: no-tag

**Additional context**
From AwsWebConsole/resource-groups/tag-editor we could wee non tagged resources

**Comment by stobrien89** [comment] 2021-09-22 16:26
Hi @yambrosov,

Thanks for reaching out!  This is a duplicate of https://github.com/boto/boto3/issues/2983.  The [documented behavior](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/resourcegroupstaggingapi/get-resources.html) for this operation is:

> Returns all the tagged or previously tagged resources that are located in the specified Region for the AWS account.

Most services will have a `list`, `describe` or `get` operation that will list all resources for a given service, depending on which resources you're trying to list resources for.

Hope this helps!

**Closed by stobrien89** 2021-09-22 16:26 UTC
Labels: duplicate, guidance, resourcegroupstaggingapi
