### ISSUE TITLE
cloudformation package might upload artifacts multiple times

### ISSUE THREAD

**Issue by Dunedan** [aws/aws-cli#3585] opened 2018-09-19 12:41 UTC
A CloudFormation template which defines multiple `AWS::Serverless::Function` resources, which use the same artifacts, causes the artifacts to be uploaded multiple times when using `aws cloudformation package --force-upload`. Apparently for each AWS Lambda function using the artifact it's uploaded all over again to the same S3 key.

So e.g. the following template would upload the artifact three times when running the package command with `--force-upload`:
```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Globals:
  Function:
    Runtime: python3.6
    Handler: index.handler

Resources:
  HelloWorld1:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
  HelloWorld2:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
  HelloWorld3:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
```

That's not really noticable for small artifacts, but is annoying with larger artifacts and a lot of `AWS::Serverless::Function` resources using the same artifact.

**Comment by Umkus** [comment] 2019-01-05 12:46
Duplicate of #3131

**Comment by Dunedan** [comment] 2019-01-05 12:54
I believe this is not a duplicate of #3131. #3131 is about creating (and uploading) new zip files for a single AWS Lambda function for consecutive runs of `cloudformation package, while this is about the generated zip getting uploaded multiple times during a single run of `cloudformation package` when it's used for multiple AWS Lambda functions.

**Comment by justnance** [comment] 2019-01-11 04:57
@Dunedan - Thanks for reaching out and sorry for unacceptable delay on this issue.  I have labeled this issue as a duplicate so we can use #3131 to track the progress.

**Closed by justnance** 2019-01-11 04:57 UTC
