### ISSUE TITLE
list-instance-profiles --generate-cli-skeleton output does not work

### ISSUE THREAD

**Issue by tchia04** [aws/aws-cli#2406] opened 2017-01-23 18:48 UTC
The input parameter works

<pre>
tonychia@blueapple ~ $ aws iam list-instance-profiles --generate-cli-skeleton input
{
    "PathPrefix": "",
    "Marker": "",
    "MaxItems": 0
}
</pre>

Running aws iam list-instance-profiles works too
<pre>
aws iam list-instance-profiles  | head
{
    "InstanceProfiles": [
        {
            "InstanceProfileId": "AIPAJDK6PAFW6FO7F4JTQ",
            "Roles": [
                {
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {

</pre>

However running with the output parameter doesn't work.  I was expecting an sample output template

<pre>
tonychia@blueapple ~ $ aws iam list-instance-profiles --generate-cli-skeleton output

Parameter validation failed:
Invalid length for parameter InstanceProfiles[0].Arn, value: 3, valid range: 20-inf
Invalid length for parameter InstanceProfiles[0].Roles[0].RoleId, value: 6, valid range: 16-inf
Invalid length for parameter InstanceProfiles[0].Roles[0].Arn, value: 3, valid range: 20-inf
tonychia@blueapple ~ $ 
tonychia@blueapple ~ $ aws --version
aws-cli/1.11.41 Python/2.7.10 Darwin/16.3.0 botocore/1.5.4
</pre>

**Comment by kyleknap** [comment] 2017-01-23 21:48
Thanks for reporting. Looks like the same bug as this one: https://github.com/aws/aws-cli/issues/2337. Since it is the same root cause, let's track the conversation/progress on the linked GitHub issue. Closing this issue as a duplicate.

**Closed by kyleknap** 2017-01-23 21:48 UTC
Labels: bug, duplicate
