### ISSUE TITLE
Describe-instances prints additional `None` with `--output text`, `--query` and `--max-items`

### ISSUE THREAD

**Issue by nicojs** [aws/aws-cli#5654] opened 2020-10-19 10:06 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

Running `aws ec2 describe-instances` with `--output text`, `--query` and `--max-items` results in a final `None` being printed. 

For example:

```sh
$  aws ec2 describe-instances --output text --query 'Reservations[*].Instances[*].InstanceId' --max-items 1
i-xxxxxxxxxxxxxxxx
None # <-- didn't expect this.
```

Without `--output text`

```sh
$  aws ec2 describe-instances --query 'Reservations[*].Instances[*].InstanceId' --max-items 1
[
    [
        "i-0f42fd05fb607fc2d"
    ]
]
```

**SDK version number**

```
$ aws --version
aws-cli/2.0.38 Python/3.7.7 Windows/10 exe/AMD64
```

**Platform/OS/Hardware/Device**

```
$ aws --version
aws-cli/2.0.38 Python/3.7.7 Windows/10 exe/AMD64
```

**To Reproduce (observed behavior)**
Run `aws ec2 describe-instances --output text --query 'Reservations[*].Instances[*].InstanceId' --max-items 1`

**Expected behavior**

```
i-xxxxxxxxxxxxxxxx
```

**Comment by kdaily** [comment] 2020-10-21 19:57
Hi @nicojs, thanks for reporting. I reproduced this on the AWS CLI v1 as well.

**Comment by mustanggb** [comment] 2021-01-28 15:26
Just encountered this also.
`aws-cli/1.16.292 Python/2.7.16 Linux/4.14.186-110.268.amzn1.x86_64 exec-env/AWS_ECS_EC2 botocore/1.13.28`

**Comment by stobrien89** [comment] 2021-03-02 02:02
Hi @nicojs and @mustanggb, 

Just tested again to ensure this is still a valid bug report and was unable to reproduce on either (more recent versions of) v2 or v1— 2.1.28 and 1.18.213, respectively. 

For anyone who is still experiencing the issue, I'd recommend bumping up to the latest (or a later) version.  Closing for now, but please @ me if you have any questions!

**Closed by stobrien89** 2021-03-02 02:02 UTC
Labels: bug
