### ISSUE TITLE
Allow `aws cloudformation package` to work with local paths in `AWS::Include` transforms

### ISSUE THREAD

**Issue by nikolay** [aws/aws-cli#2513] opened 2017-03-28 23:57 UTC

**Comment by kyleknap** [comment] 2017-03-29 22:18
Marking as feature request. @sanathkr what's your thoughts on this?

**Comment by sanathkr** [comment] 2017-03-29 22:39
Great idea. Let's do it. PRs please :-)

**Comment by nikolay** [comment] 2017-04-11 21:02
@kyleknap @sanathkr It looks like this won't be so easy to implement as you guys have made assumptions in the current code that won't work with `AWS::Include`, which can literally be placed anywhere.

**Comment by nikolay** [comment] 2017-06-08 17:35
Any luck? This would be a huge improvement of the CloudFormation workflow, which is the main obstacle of people adopting CloudFormation widely!

**Comment by davidkelley** [comment] 2017-10-20 07:42
Any update on this issue? It would be a fantastic feature to have.

**Comment by lafiosca** [comment] 2018-01-22 21:34
This would be a huge help for the use case from this example: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml

**Comment by ASayre** [comment] 2018-02-06 10:33
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment] 2018-04-06 20:16
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by georgealton** [comment] 2018-04-11 19:13
this would be a major benefit as @lafiosca mentions the exact same problem i'm trying to solve :)

**Comment by ekcrisp** [comment] 2018-07-10 23:06
@sanathkr @lafiosca @georgealton @nikolay 

I just submit a PR that would add this for inline swagger definitions on AWS::Serverless::Api resources. Adding it for arbitrary resources would be much more difficult, it seems this is the main use case though

https://github.com/aws/aws-cli/pull/3440

**Comment by ekcrisp** [comment] 2018-07-17 18:06
Update: I have implemented this for arbitrary include transforms, not sure about my implementation approach, here is the PR, I will close the previous one if we decide to go ahead with this https://github.com/aws/aws-cli/pull/3454

**Comment by ekcrisp** [comment] 2018-08-08 23:10
@kyleknap @sanathkr @joguSD @stealthycoin how do i go about getting my PR for this reviewed?
https://github.com/aws/aws-cli/pull/3454

**Comment by jniedrauer** [comment] 2018-08-10 17:06
I also want this functionality. Let's get this merged!

**Comment by sanathkr** [comment] 2018-11-10 03:12
Looks like the PRis merged but the Issue is still open. Need to close it.

**Comment by debora-ito** [comment] 2019-01-23 21:52
Closing this as #3454 has been merged.

**Closed by debora-ito** 2019-01-23 21:52 UTC
Labels: cloudformation package/deploy, feature-request
