### ISSUE TITLE
My CI/CD pipeline is unable to install aws-cli awscli-1.19.50

### ISSUE THREAD

**Issue by sandeep-patle1508** [aws/aws-cli#6092] opened 2021-04-13 06:26 UTC
Looks like we have seen this issue before as well https://github.com/aws/aws-cli/issues/6064

It was successful with awscli-1.19.49.

Is this new version awscli-1.19.50 causing this failure?

Here is a screenshot of my build failure:
<img width="1348" alt="Screenshot 2021-04-13 at 08 25 11" src="https://user-images.githubusercontent.com/13983369/114506235-c8230180-9c31-11eb-88fe-5631179db648.png">

**Additional context**

**Comment by nateprewitt** [comment] 2021-04-13 16:10
Hi @sandeep-patle1508,

This is a duplicate of #6064 as you've noted, and isn't unique to 1.19.50. The underlying issue is the version of `pip`/`setuptools` being used. Full information on the problem and how to fix it for your setup can be found in the original thread (https://github.com/aws/aws-cli/issues/6064#issuecomment-815011418).

Also please note that the CLI will be deprecating support for Python 2.7 on July 15th. You can find full information [here](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/).

**Closed** 2021-04-16 17:11 UTC
Labels: closing-soon, duplicate, guidance
