### ISSUE TITLE
Cannot delete published `@types/foobar` package from CodeArtifact

### ISSUE THREAD

**Issue by guoliang** [aws/aws-cli#6125] opened 2021-04-27 18:25 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Cannot delete published `@types/foobar` package from CodeArtifact.

**SDK version number**
aws-cli/2.1.29 Python/3.8.8

**Platform/OS/Hardware/Device**
Windows 10

**To Reproduce (observed behavior)**
1. Publish an NPM package which starts with `@types/foobar` in its name
2. Delete package with `aws codeartifact delete-package-versions ...`

**Expected behavior**
Package should be removed

**Logs/output**
> An error occurred (ValidationException) when calling the DeletePackageVersions operation: 1 validation error detected: Value '@types/foobar' at 'packageName' failed to satisfy constraint: Member must satisfy regular expression pattern: [^!#/\s]+

**Additional context**
I stripped out what was in `--debug` as it evident here what the issue is. The problem is the validator which matches "/" character in my package name therefore will exit with error.

**Comment by kdaily** [comment] 2021-04-27 21:46
Hi @guoliang,

This is a duplicate of this issue #5501. The service team is aware of it, but I do not have an ETA on a fix. Please track on the other issue for updates. Thanks!

**Closed** 2021-04-27 21:46 UTC
Labels: codeartifact, customization, duplicate
