### ISSUE TITLE
CodeBuild push to ECR doesn't works

### ISSUE THREAD

**Issue by AMB-Informacio** [aws/aws-cli#7231] opened 2022-08-30 07:35 UTC
### Describe the bug

It's the same behaviour as the described in:

[https://github.com/aws/aws-cli/issues/7102]

A buildspec.yml file describes to build a docker image and to push it to ECR but the Docker push don't work, retrying to do that and finally fails.

There was answered as a problem with the artifacts and the image-definitions.json file. But that's happening because the previous step "docker push" fails unexpectedly, and that is the real problem.

### Expected Behavior

Docker image pushed to ECR

### Current Behavior

For any reason docker push is retrying and then an EOF appears.

```
[Container] 2022/08/30 06:32:01 Running command docker push $REPOSITORY_URI:latest
--
723 | The push refers to repository [XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/gitoccupacy-backend-service]
724 | 6a37c076ad0a: Preparing
725 | 838351f683ff: Preparing
726 | f00576e66739: Preparing
727 | 845237c43dbf: Preparing
[...]
1069 | 845237c43dbf: Retrying in 1 second
1070 | 94a688c21a1d: Retrying in 1 second
1071 | EOF
1072 |  
1073 | [Container] 2022/08/30 06:32:51 Command did not exit successfully docker push $REPOSITORY_URI:latest exit status 1
1074 | [Container] 2022/08/30 06:32:51 Phase complete: POST_BUILD State: FAILED

```

### Reproduction Steps

Commit or retry to build project with this buildspec.yml file:

```

version: 0.2

env:
  secrets-manager:
    DOCKERHUB_LOGIN: "dockerhub:login"
    DOCKERHUB_PASSWORD: "dockerhub:password"

batch:
  fast-fail: false

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_DOMAIN_NAME=$(echo $AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_DEFAULT_REGION'.amazonaws.com')
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_DOMAIN_NAME
      - REPOSITORY_URI=$(echo $REPOSITORY_DOMAIN_NAME'/'$IMAGE_REPO_NAME)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to DockerHub
      - docker login --username $DOCKERHUB_LOGIN --password $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --target release --file './backend-service/Dockerfile' -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

```

### CLI version used

code build version: 0.2

### Environment details (OS name and version, etc.)

code build version: 0.2

**Comment by AMB-Informacio** [comment] 2022-08-30 08:03
I think this issue better goes to [aws-codebuild-docker-images](https://github.com/aws/aws-codebuild-docker-images)

I posted it here because is the same case of one already posted here (and closed).

**Comment by tim-finnigan** [comment] 2022-08-31 20:54
Hi @AMB-Informacio thanks for reaching out. Are you also seeing that "no matching artifact paths found" error mentioned in https://github.com/aws/aws-cli/issues/7102? If so have you looked through the related issues mentioned [here](https://github.com/aws/aws-cli/issues/7102#issuecomment-1185777242)?

This issue may be better suited for [aws-codebuild-docker-images](https://github.com/aws/aws-codebuild-docker-images) as you mentioned. I can transfer it there if you'd like. If you can provide any more info (reproduction steps, code snippets, debug logs) that would also help give more insight into this.

**Comment by AMB-Informacio** [comment] 2022-09-01 05:14
HI @tim-finnigan , I saw the other posts and solution, but in this case no matching artifact paths are found because the previous step, docker push fails.

Please can you transfer this to [https://github.com/aws/aws-codebuild-docker-images](https://github.com/aws/aws-codebuild-docker-images)?

Thank you!

**Comment by tim-finnigan** [comment] 2022-09-01 14:55
Hi @AMB-Informacio thanks for following up. I tried transferring the issue but wasn't able to, possibly due to some permissions issue. But I recreated the issue there (https://github.com/aws/aws-codebuild-docker-images/issues/558). If you subscribe to that issue then you will get a notification when there is an update. You can also try reaching out to [AWS Support](https://aws.amazon.com/contact-us/) if you are blocked. I'll go ahead and close this issue now. Thanks!

**Closed by tim-finnigan** 2022-09-01 14:55 UTC
Labels: bug, response-requested, ecr
