### ISSUE TITLE
Cannot delete replace-root-volume-task objects

### ISSUE THREAD

**Issue by kpouget** [aws/aws-cli#6650] opened 2022-01-11 19:10 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Users cannot delete `replace-root-volume-task/replacevol-...` objects

**SDK version number**
N/A

**Platform/OS/Hardware/Device**
N/A

**To Reproduce (observed behavior)**

* Create a replace-root-volume task, eg

```
    resp = client_ec2.create_replace_root_volume_task(
        InstanceId=instance.id,
        SnapshotId=snapshot.id,
```

* get a `replacevol-...` identifier
* see that you can't delete the object

**Expected behavior**
* should be able to delete the object

**Comment by kdaily** [comment] 2022-01-11 23:45
Hi @kpouget,

Sorry to hear you're having a problem. Can you please provide the debug logs for this? You opened this in the AWS CLI repository, but posted `boto3` code. For the CLI, you can add the `--debug` flag to your command. For `boto3`, you can add `boto3.set_stream_logger('')` to your script.

Thanks!

**Comment by kpouget** [comment] 2022-01-12 07:51
Hello @kdaily, the issue I point out is actually (I guess) at the API level, there is no API to delete the `replacevol-...` objects.

Here are the CLIs command to get to the same point:
```
$ aws ec2 create-replace-root-volume-task --instance-id INSTANCE_ID  --snapshot-id SNAPSHOT_ID  --output json 
<replace root volume task created>
```
```
$ aws ec2 describe-replace-root-volume-tasks
<replace root volume tasks listed>
```

**==> <replace root volume tasks> cannot be deleted**

**Comment by kdaily** [comment] 2022-01-12 19:17
Hi @kpouget,

Sorry that I misunderstood! Yes, there is no way to delete a replace root volume task. Per the [EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-restoring-volume.html#view-replacement-tasks) task states, deleted is not one of them.

This would be a feature request to the AWS EC2 service team, as there is no API to perform this operation. I can pass along this feedback to the EC2 team if you can provide some more details on:

1. The use case for this feature
2. Specific pain points that are caused by the lack of the feature
3. What you're doing now to work around this.

Thanks!

**Comment by kpouget** [comment] 2022-01-12 20:13
Hello @kdaily 

I was trying to do proper resource identification during a snapshot/rollback, so the `replace-root-volume-task` was created with the OpenShift ownership label: 

```
    resp = client_ec2.create_replace_root_volume_task(
        InstanceId=instance.id,
        SnapshotId=snapshot.id,
        TagSpecifications=[
            {
                'ResourceType': 'volume',
                'Tags': [
                    {'Key': 'Name', 'Value': f'{cluster_name}-restored-at-{ts}'},
                    {'Key': f'kubernetes.io/cluster/{cluster_name}', 'Value': 'owned'},
                ]
            },
            {
                'ResourceType': 'replace-root-volume-task',
                'Tags': [
                    {'Key': f'kubernetes.io/cluster/{cluster_name}', 'Value': 'owned'},
                ]
            },
        ]
    )
```
however, when destroying a cluster containing such resources, `openshift-installer` loops forever as it detects that these objects are alive:
```
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG unrecognized EC2 resource type replace-root-volume-task  arn=arn:aws:ec2:eu-central-1:...:replace-root-volume-task/replacevol-...
DEBUG search for matching resources by tag in eu-central-1 matching aws.Filter{"kubernetes.io/cluster/kpouget-...":"owned"}
DEBUG search for matching resources by tag in eu-central-1 matching aws.Filter{"openshiftClusterID":"..."}
```

The workaround for this is to avoid using the usual tag `kubernetes.io/cluster/kpouget-...: owned`. 
Is this the recommended way to proceed, just letting these resources dangling?

thanks,

Kevin

**Comment by kdaily** [comment] 2022-01-12 22:43
Hi @kpouget,

Thanks for the details. I'm not at all familiar with OpenShift or how it's using tags to manage resources. Regarding this statement:

> it detects that these objects are alive:

What does 'alive' mean to OpenShift? If you do a `describe-replace-root-volume-tasks` operation, what's the status of the tasks that you are getting `unrecognized EC2 resource type` for?

I'm afraid we won't be much help here, as this looks like a third party issue with OpenShift. I can request some information from the EC2 team regarding these tasks, but cannot guarantee on when I would get a response. I would suggest asking on StackOverflow, or the new AWS forums at https://repost.aws/questions.

**Comment by kpouget** [comment] 2022-01-14 09:28
ok, I think it's fair to ignore these resources then

thanks for your help

**Comment by tim-finnigan** [comment] 2022-11-08 21:54
Since it was determined earlier that this is a third-party issue involving OpenShift, I am going to close this issue. If there is a feature request here for new API functionality then we recommend reaching out directly to [AWS Support](https://aws.amazon.com/contact-us/) for further escalation and tracking.

**Closed by tim-finnigan** 2022-11-08 21:54 UTC
Labels: feature-request, ec2, service-api, third-party
