### ISSUE TITLE
 aws resourcegroupstaggingapi get-resources does not return resources with empty tags

### ISSUE THREAD

**Issue by antoni-g** [aws/aws-cli#6578] opened 2021-11-29 22:38 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws resourcegroupstaggingapi get-resources` does not return resources with empty tags
The [documentation](https://docs.aws.amazon.com/cli/latest/reference/resourcegroupstaggingapi/get-resources.html) for this operation, as found here, is as follows:
Returns all the tagged or previously tagged resources that are located in the specified Amazon Web Services Region for the account.

**SDK version number**
aws-cli/2.0.46

**Platform/OS/Hardware/Device**
What are you running the cli on?
MacOS

**To Reproduce (observed behavior)**
execute operation `aws resourcetaggingapi get-resources`

**Expected behavior**
A full list of resources including all tags or lack thereof.
Instead, the operation only returns resources that have at some point been tagged.
While this is _technically_ correct through a strictly literal interpretation of the documentation, this is unintuitive behavior as "manually set as empty tags" and "never tagged" are two distinct states for resources that are functionally indistinct. For the purposes of the potential use cases of the API, ie, automating tagging compliance across resources, this makes the API an ineffective solution as then resources are not actually visible to API. This begs the question of why this operation or even the API claims to be useful for this purpose.

**Comment by kdaily** [comment] 2021-11-30 17:07
Hi @antoni-g,

Thanks for your post. This is a duplicate of https://github.com/aws/aws-cli/issues/6417.

I would also have to confirm with the Resource Tagging team, but my intuition is that there is an implementation difference - if you never tagged something, then there is no record of it in the data store being used by the `get-resources` API.

Regardless, there is a semantic difference between "manually set as empty tags" and "never tagged". If I explicitly set a tag on something, even if it's an empty tag, I'm adding data to it in the form of metadata, which makes it visible via APIs such as the ResourceTagging `get-resources` API. If I do not tag it at all (or have a tagging policy that makes the tags inaccessible to you), you do not have visibility of the resource based on the tags, which might be for a privacy or compliance purpose.

It seems that what you want is an inventory of certain types of resources, which the [AWS Config service](https://docs.aws.amazon.com/config/index.html#lang/en_us) can provide. There are also third party, including open source, options to crawl AWS accounts for resource discovery, but I cannot provide support or recommendations for those.

**Closed** 2021-11-30 17:07 UTC
Labels: duplicate, guidance, resourcegroupstaggingapi
