### ISSUE TITLE
eks update-config - generates incorrect kube-config - missing aws-iam-authenticator command

### ISSUE THREAD

**Issue by javapapo** [aws/aws-cli#4145] opened 2019-05-11 20:49 UTC
Version: aws-cli/1.16.156 Python/2.7.5 Linux/3.10.0-957.12.1.el7.x86_64 botocore/1.12.146
kubectl : 1.12.7
iam-aws-authenticator: 1.12.7

```bash
aws --region eu-west-1 eks update-kubeconfig --name XXXXXX
```

it generates 

```
 apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      -  XXXXXX
      command: aws ---> it should be aws-iam-authenticator
```

Obviously whatever the attempt with the get-token - it should not break the previous mode
or give me the choice
```
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - xxxxx
      command: aws-iam-authenticator
```
The above makes kubectl invoke the aws cli but results to

```
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by joguSD** [comment] 2019-05-12 06:50
Using `aws` instead of `aws-iam-authenticator` is intentional, but authentication failing is definitely not intentional. We pushed some changes in the last release to reduce the number of dependencies required (you should only need the `aws` command). Looking into this now.

**Comment by javapapo** [comment] 2019-05-12 07:10
I understand I think I spotted a related P.R . Kubectl is invoking the aws cli but it fails ..

```
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by joguSD** [comment] 2019-05-12 07:12
Interesting, does this always happen? Or is it intermittent?

**Comment by javapapo** [comment] 2019-05-12 07:14
Always - it makes sense, since the new config instead of `aws-iam-authenticator` - changes the command to `aws` - then the cli is invoked. 

Either the `aws xxx` command that you expect to be executed is not , or there something with kubectl and this ? 

I am using the latest `kubectl` as fetched from the documents 1.12.7

**Comment by javapapo** [comment] 2019-05-12 07:15
Also a side note - if and when this command makes it prime -the documentation needs to be updated: https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html . Because now is still part of the official docs still. So this kind of change I have a feeling should be communicated with an EKS blog post?

**Comment by joguSD** [comment] 2019-05-12 07:24
Does setting a region in either `~/.aws/config` or set the `AWS_REGION` env var make the command kubectl invoking work?

**Comment by javapapo** [comment] 2019-05-12 07:27
hmm I need to test it - this and currently I have pivoted back to an older version of awscli that does not break this.

But still I don't think this is a safe assumption - because if you think so we do pass the region on the command : aws --region eu-west-1 

So whatever was the intention - the command is not properly templated on kubectl

**Comment by javapapo** [comment] 2019-05-12 07:29
Maybe you can force this - when you generate the snippet? 

```
apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --region
     - <region>
      - --cluster-name
      -  XXXXXX
```

**Comment by sernst** [comment] 2019-05-12 20:27
I'm encountering this issue as well. In my case the issue is intermittent. I can run a kubectl command multiple times in a row and get different errors/success outcomes. For example, running this command:

```
$ kubectl get roles --namespace kube-system

NAME                                             AGE
extension-apiserver-authentication-reader        14d
system::leader-locking-kube-controller-manager   14d
system::leader-locking-kube-scheduler            14d
system:controller:bootstrap-signer               14d
system:controller:cloud-provider                 14d
system:controller:token-cleaner                  14d
```

gives me the expected output. I can execute the same command again a moment later and get:

```
$ kubectl get roles --namespace kube-system

error: You must be logged in to the server (Unauthorized)
```

Occasionally, I'll get this error as well:

```
$ kubectl get roles --namespace kube-system

error: the server doesn't have a resource type "roles"
```

The profile I used to invoke the `eks update-kubeconfig` command does have a region name specified in the config file. Reverting the awscli worked for me as well to resolve the problem.

**Comment by jkpl** [comment] 2019-05-13 11:14
I'm experiencing this problem as well. Some of the `kubectl` commands succeed, and some fail with `Unauthorized`. There doesn't seem to be clear pattern on which commands this happens on. Looking at the authenticator logs for EKS reveals that there are "access denied" errors with the message `input token was not properly formatted: illegal base64 data at input byte 1071`.

The old configs using aws-iam-authenticator seem to work still just fine, so that can still be used as a workaround.

**Comment by micahhausler** [comment] 2019-05-13 18:49
@jkpl The illegal format error should be fixed in #4146 and will be rolled out shortly

**Closed** 2019-05-13 23:39 UTC

**Comment by landaumd** [comment] 2019-05-15 16:28
Hi all, my team is still running in to this issue. Is the fix to revert back to an older version of aws-cli?

**Comment by kyleknap** [comment] 2019-05-15 17:22
@landaumd what version of the AWS CLI are you using? You can determine the version from running `aws --version`. In order to see the fix, you need to be using version `1.16.158`.

**Comment by javapapo** [comment] 2019-05-16 18:15
I can confirm that the latest version , currently for me is `1.16.159` generates this config

```yaml
- name: arn:aws:eks:eu-west-1:486389912938:cluster/PRD1741-iccp-dev-eks-cluster-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - cluster1
      command: aws
      env:
      - name: AWS_PROFILE
        value: XXXXXX
```

**Comment by landaumd** [comment] 2019-05-16 19:03
@kyleknap I reverted back to 1.16.135 and it is working as expected now. Thank you for following up!

**Comment by landaumd** [comment] 2019-05-16 19:04
@javapapo yes that was the same error I was getting

**Comment by github4es** [comment] 2019-09-01 23:56
Is there an option to include 
- "-r"
      - "arn:aws:iam::111122223333:role/my-cluster-masters-role"

this is not clear in the documentation. One has to magically know to add these flags to the config file in order to have the aws authenticator create the proper token to talk to the cluster.

**Comment by jkpl** [comment] 2019-09-02 08:04
@github4es When you generate the Kubeconfig file using `aws eks update-kubeconfig`, you can pass the role using the CLI argument `--role-arn`. Example:

```shell
aws eks update-kubeconfig --name my-cluster --role-arn arn:aws:iam::111122223333:role/my-cluster-masters-role
```

I learned this information from the `update-kubeconfig` sub-command [documentation](https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html). You can also view the doc as a man page using the `help` sub-command.

```shell
aws eks update-kubeconfig help
```

The flag is also mentioned in the [EKS documentation](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html).
