### ISSUE TITLE
Unicode issues with non-ascii chars in home path

### ISSUE THREAD

**Issue by alex88** [aws/aws-cli#2395] opened 2017-01-19 14:27 UTC
I had to install aws-cli on a Turkish pc running windows 7 with the user's home folder called `İK` and I get this output

```
C:\Users\İK>aws
Traceback (most recent call last):
  File "aws", line 27, in <module>
  File "aws", line 23, in main
  File "awscli\clidriver.pyc", line 53, in main
  File "awscli\clidriver.pyc", line 61, in create_clidriver
  File "botocore\session.pyc", line 375, in full_config
  File "botocore\configloader.pyc", line 105, in load_config
  File "botocore\configloader.pyc", line 145, in raw_config_parse
  File "botocore\exceptions.pyc", line 27, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 9: ordinal not in range(128)
```
could it be something related to the user's folder name?

I've tried also with --debug but I've the same issue

**Comment by kyleknap** [comment] 2017-01-19 22:58
@alex88 
Yeah looks the initializer for that exception does not correctly handle unicode, which blows up the config/credential loading process because it is expecting for a ConfigNotFound to be raised. I have not reproduced this yet but could you include the complete debug logs to help us look into it?

**Comment by alex88** [comment] 2017-01-19 23:00
Hi @kyleknap where can I find the debug logs? Using `--debug` after the command provides the same output

**Comment by alex88** [comment] 2017-01-19 23:02
Just a quick test on my OSX machine

```
➜  İK export HOME=/tmp/İK
➜  ~ pwd
/tmp/İK
➜  ~ aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 53, in main
    driver = create_clidriver()
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 61, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/session.py", line 375, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/configloader.py", line 105, in load_config
    parsed = raw_config_parse(config_filename)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/configloader.py", line 145, in raw_config_parse
    raise botocore.exceptions.ConfigNotFound(path=path)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/exceptions.py", line 27, in __init__
    msg = self.fmt.format(**kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
➜  ~ aws --debug
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 53, in main
    driver = create_clidriver()
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/awscli/clidriver.py", line 61, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/session.py", line 375, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/configloader.py", line 105, in load_config
    parsed = raw_config_parse(config_filename)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/configloader.py", line 145, in raw_config_parse
    raise botocore.exceptions.ConfigNotFound(path=path)
  File "/usr/local/Cellar/awscli/1.11.37/libexec/lib/python2.7/site-packages/botocore/exceptions.py", line 27, in __init__
    msg = self.fmt.format(**kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 5: ordinal not in range(128)
```

**Comment by kyleknap** [comment] 2017-01-19 23:03
Right this error happens before the debug logger actually gets registered, so there won't be any debug logs... We will look into reproducing it and come up with a fix. Thanks for the complete Traceback!

**Comment by kyleknap** [comment] 2017-01-19 23:09
I can confirm the same on my OS X machine. We will look into what we can do here.

**Comment by soukicz** [comment] 2017-01-26 16:49
It is probably the same issue as #2366

**Comment by galopin** [comment] 2017-01-31 15:39
@kyleknap Having the same issue on my Windows set-up:

```shell
$ echo $HOME
/c/Documents and Settings/Michaël

$ aws
Traceback (most recent call last):
  File "C:/Python27/Scripts/aws", line 27, in <module>
    sys.exit(main())
  File "C:/Python27/Scripts/aws", line 23, in main
    return awscli.clidriver.main()
  File "C:\Python27\lib\site-packages\awscli\clidriver.py", line 53, in main
    driver = create_clidriver()
  File "C:\Python27\lib\site-packages\awscli\clidriver.py", line 61, in create_clidriver
    load_plugins(session.full_config.get('plugins', {}),
  File "C:\Python27\lib\site-packages\botocore\session.py", line 375, in full_config
    self._config = botocore.configloader.load_config(config_file)
  File "C:\Python27\lib\site-packages\botocore\configloader.py", line 105, in load_config
    parsed = raw_config_parse(config_filename)
  File "C:\Python27\lib\site-packages\botocore\configloader.py", line 145, in raw_config_parse
    raise botocore.exceptions.ConfigNotFound(path=path)
  File "C:\Python27\lib\site-packages\botocore\exceptions.py", line 27, in __init__
    msg = self.fmt.format(**kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xeb in position 31: ordinal not in range(128)
```

Interestingly [pypa/pip](https://github.com/pypa/pip) project had a similar issue (https://github.com/pypa/pip/issues/3463) that was fixed in early October 2016 (https://github.com/pypa/pip/pull/4000):

```
* Fix problems on Windows on Python 2 when username or hostname contains
  non-ASCII characters (:issue:`3463`, :pull:`3970`, :pull:`4000`).
```

Hope this helps!

**Closed** 2017-03-24 21:49 UTC
Labels: bug, confirmed
