### ISSUE TITLE
Stage synchronized files like rsync does

### ISSUE THREAD

**Issue by nkadel-skyhook** [aws/aws-cli#1705] opened 2016-01-06 17:39 UTC
There's a service problem when using "aws s3 sync" to mirror bulky files, especially source tarballs. The file is loaded in place, with the eventual target name, such as "awscli.tar.gz". The result is that while in progress, a file with that name is present on the local filesystem and may be accessed or downloaded by others. But if the file is being updated in place, the file is not usable until the transfer is complete. And for bulky tarballs, this can be unreliable.

The result is that "aws s3 sync" corrupts the local copy of any file it can't successfully sync. "rsync" does this better by default, using a temporary target file generated with "mktemp" such as ".awscli.tar.gz.kdpaud"  and only moving it into place upon completion.

Would you be willing to add an "aws s3 sync --delay-updates" option, much like hte "rsync" option, to stage the deployment t of the new files until the sync is completed?

**Comment by JordonPhillips** [comment] 2016-01-11 17:32
Ah, I see what you're saying. We'll look into adding this to the backlog!

**Comment by nkadel-skyhook** [comment] 2016-01-13 14:56
A quick check with the older "s3cmd" shoes that it does just what I was looking for: you might check that code for a working model.

**Comment by jamesls** [comment] 2016-01-13 18:41
Would you need the entire set of transferred files staged first?  If not, I believe this is a dupe of https://github.com/aws/aws-cli/issues/701

**Comment by jamesls** [comment] 2016-01-15 03:35
Consolidating issues.  Let's track this discussion in #701.  I don't know if we can do a `--delay-updates` for all the files as that's potentially creating duplicates of millions of files during the download process.  I do think that we should change our default behavior to where we write to a temp file while downloading and only rename the file once we've finished downloading.  Feel free to add your additional thoughts over in #701.

**Closed by jamesls** 2016-01-15 03:35 UTC
Labels: feature-request, s3sync
