### ISSUE TITLE
Pip install fails AWS CLI 1.7.34 wants simpleJSON in python 2.6

### ISSUE THREAD

**Issue by dstuebe** [aws/aws-cli#1384] opened 2015-06-12 13:06 UTC
```
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.6/site-packages/awscli/clidriver.py", line 16, in <module>
    import botocore.session
  File "/usr/local/lib/python2.6/site-packages/botocore/session.py", line 27, in <module>
    import botocore.config
  File "/usr/local/lib/python2.6/site-packages/botocore/config.py", line 18, in <module>
    from botocore.compat import six
  File "/usr/local/lib/python2.6/site-packages/botocore/compat.py", line 119, in <module>
    import simplejson as json
ImportError: No module named simplejson
```

**Comment by kyleknap** [comment] 2015-06-12 16:11
What version of pip are using and what OS are you using?

**Comment by dstuebe** [comment] 2015-06-12 17:43
I can repro the problem on my local machine using the system installed python2.6 in /usr/bin

I set up a virtual env... 

$ pip --version
pip 1.5.6 from /Users/davidstuebe/.virtualenvs/awscli_test/lib/python2.6/site-packages (python 2.6)

Mac OSX 10.9.5
$ uname -a
Darwin ip-192-168-60-85.ec2.internal 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64

**Comment by jamesls** [comment] 2015-06-12 18:24
Confirmed, the issue is that the whl files were not specifying the conditional dependencies properly.  We'll just need to re-upload new whl files to fix this.  I'll update once this is done.

The workaround for anyone running into this on python2.6 is to manually install the dependencies for now `pip install simplejson ordereddict argparse`.

**Comment by jamesls** [comment] 2015-06-12 18:30
Should be fixed now.  The latest release also added support for installing from .whl files which has a few issues we need to fix.  For the time being, I've pulled the .whl files out so we'll just use sdists (.tar.gz), which is what we were using previously.

Let me know if you're still running into any issues.

**Closed by jamesls** 2015-06-12 18:30 UTC
Labels: bug, confirmed
