### ISSUE TITLE
[v2] SSO login not launching browser

### ISSUE THREAD

**Issue by ericmillinder** [aws/aws-cli#4839] opened 2020-01-14 15:38 UTC
When using the packaged aws2 distributed at https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip, running the sso login fails to open the webbrowser. 

`$ /usr/local/aws-cli/v2/current/bin/aws2 sso login --profile <my profile> --debug`

```
2020-01-14 09:34:08,942 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.0dev3 Python/3.7.3 Linux/5.4.8-200.fc31.x86_64 botocore/2.0.0dev2
2020-01-14 09:34:08,942 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['sso', 'login', '--profile', 'appdev-admin', '--debug']
2020-01-14 09:34:08,943 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fa442bde950>
2020-01-14 09:34:08,943 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fa4434af048>
2020-01-14 09:34:08,943 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fa442b2a158>
2020-01-14 09:34:08,944 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fa4434cdbf8>
2020-01-14 09:34:08,947 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2020-01-14 09:34:08,947 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fa442d4dd08>
2020-01-14 09:34:08,947 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fa442d8a730>
2020-01-14 09:34:08,957 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/sso/2019-06-10/service-2.json
2020-01-14 09:34:08,960 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_sso_commands at 0x7fa442d78378>
2020-01-14 09:34:08,960 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sso: calling handler <function add_waiters at 0x7fa442b6bea0>
2020-01-14 09:34:08,970 - MainThread - botocore.hooks - DEBUG - Event building-command-table.login: calling handler <function add_waiters at 0x7fa442b6bea0>
2020-01-14 09:34:08,972 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/endpoints.json
2020-01-14 09:34:08,982 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fa444532510>
2020-01-14 09:34:08,982 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/sso-oidc/2019-06-10/service-2.json
2020-01-14 09:34:08,983 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sso-oidc: calling handler <function add_generate_presigned_url at 0x7fa444517d90>
2020-01-14 09:34:08,992 - MainThread - botocore.endpoint - DEBUG - Setting oidc timeout as (60, 60)
2020-01-14 09:34:08,993 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.0.0dev3/dist/botocore/data/_retry.json
2020-01-14 09:34:08,994 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: sso-oidc
2020-01-14 09:34:08,995 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sso-oidc.StartDeviceAuthorization: calling handler <function base64_decode_input_blobs at 0x7fa442b2a950>
2020-01-14 09:34:08,996 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sso-oidc.StartDeviceAuthorization: calling handler <function generate_idempotent_uuid at 0x7fa4444de400>
2020-01-14 09:34:08,996 - MainThread - botocore.hooks - DEBUG - Event before-call.sso-oidc.StartDeviceAuthorization: calling handler <function inject_api_version_header_if_needed at 0x7fa4444dbd90>
2020-01-14 09:34:08,996 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=StartDeviceAuthorization) with params: {'url_path': '/device_authorization', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.0.0dev3 Python/3.7.3 Linux/5.4.8-200.fc31.x86_64 botocore/2.0.0dev2'}, 'body': b'{"clientId": "RQPD_rAU6psh-0jampS8CXVzLWVhc3QtMQ", "clientSecret": "eyJraWQiOiJrZXktMTU2NDAyODA5OSIsImFsZyI6IkhTMzg0In0.eyJzZXJpYWxpemVkIjoie1wiZXhwaXJlZFwiOmZhbHNlLFwiY2xpZW50SWRcIjp7XCJ2YWx1ZVwiOlwiUlFQRF9yQVU2cHNoLTBqYW1wUzhDWFZ6TFdWaGMzUXRNUVwifSxcImNsaWVudE5hbWVcIjpcImJvdG9jb3JlLWNsaWVudC0xNTc4MzM5MTAyXCIsXCJjbGllbnRUeXBlXCI6XCJQVUJMSUNcIixcInRlbXBsYXRlQXJuXCI6bnVsbCxcInRlbXBsYXRlQ29udGV4dFwiOm51bGwsXCJleHBpcmF0aW9uVGltZXN0YW1wXCI6MTU4NjExNTEyOC4xNDQwMDAwMDAsXCJjcmVhdGVkVGltZXN0YW1wXCI6MTU3ODMzOTEyOC4xNDQwMDAwMDAsXCJ1cGRhdGVkVGltZXN0YW1wXCI6MTU3ODMzOTEyOC4xNDQwMDAwMDAsXCJjcmVhdGVkQnlcIjpudWxsLFwidXBkYXRlZEJ5XCI6bnVsbH0ifQ.XRupcgH-58uQf8-BX9WqprgpAIVuyYm-zGGG_QlplWLrGPgkzsGWGTrdPTzEq06Z", "startUrl": "<STARTURL>"}', 'url': 'https://oidc.us-east-1.amazonaws.com/device_authorization', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7fa4428f04e0>, 'has_streaming_input': False, 'auth_type': 'none'}}
2020-01-14 09:34:08,997 - MainThread - botocore.hooks - DEBUG - Event request-created.sso-oidc.StartDeviceAuthorization: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fa4428f04a8>>
2020-01-14 09:34:08,997 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sso-oidc.StartDeviceAuthorization: calling handler <function set_operation_specific_signer at 0x7fa4444de2f0>
2020-01-14 09:34:08,998 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://oidc.us-east-1.amazonaws.com/device_authorization, headers={'User-Agent': b'aws-cli/2.0.0dev3 Python/3.7.3 Linux/5.4.8-200.fc31.x86_64 botocore/2.0.0dev2', 'Content-Length': '750'}>
2020-01-14 09:34:08,999 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): oidc.us-east-1.amazonaws.com:443
2020-01-14 09:34:09,183 - MainThread - urllib3.connectionpool - DEBUG - https://oidc.us-east-1.amazonaws.com:443 "POST /device_authorization HTTP/1.1" 200 311
2020-01-14 09:34:09,183 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 14 Jan 2020 14:34:09 GMT', 'Content-Type': 'application/json', 'Content-Length': '311', 'Connection': 'keep-alive', 'x-amzn-RequestId': '4f4cae3e-cfff-47cf-97c2-b39ac215ca52'}
2020-01-14 09:34:09,184 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"deviceCode":"zLQp_Y21lZEobo8jGb9u9E1LH9zSzT1CoeBMaWqO05-qefgFFtvAcubdxjjxdPYRjttECfWLIPdGt9sO41RtCw","expiresIn":600,"interval":1,"userCode":"THE-CODE","verificationUri":"https://device.sso.us-east-1.amazonaws.com/","verificationUriComplete":"https://device.sso.us-east-1.amazonaws.com/?user_code=THE-CODE"}'
2020-01-14 09:34:09,184 - MainThread - botocore.hooks - DEBUG - Event needs-retry.sso-oidc.StartDeviceAuthorization: calling handler <botocore.retryhandler.RetryHandler object at 0x7fa4428f07b8>
2020-01-14 09:34:09,184 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.us-east-1.amazonaws.com/

Then enter the code:

THE-CODE
2020-01-14 09:34:09,262 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sso-oidc.CreateToken: calling handler <function base64_decode_input_blobs at 0x7fa442b2a950>
2020-01-14 09:34:09,263 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sso-oidc.CreateToken: calling handler <function generate_idempotent_uuid at 0x7fa4444de400>
2020-01-14 09:34:09,263 - MainThread - botocore.hooks - DEBUG - Event before-call.sso-oidc.CreateToken: calling handler <function inject_api_version_header_if_needed at 0x7fa4444dbd90>
2020-01-14 09:34:09,263 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CreateToken) with params: {'url_path': '/token', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.0
```
No logs indicating an exception from the browser launch are apparent. I was expecting to see the log from the try block in utils.py.
```
try:
	return self._open_browser(verificationUriComplete)
except Exception:
	LOG.debug('Failed to open browser:', exc_info=True)
```

HOWEVER when I clone the aws-cli repo, switch to v2 branch, install and run `aws-cli/bin/aws sso login --profile appdev-admin`, the browser DOES launch as expected. 

This appears to be happening across multiple linux installations as no one on my team is getting the browser to launch.

**Comment by joguSD** [comment] 2020-02-05 22:06
I was able to confirm this on an archlinux install running KDE. Thankfully, I was able to get *some* output to see what was going wrong:
```
kde-open5: /tmp/awscli/v2/2.0.0dev4/dist/libz.so.1: no version information available (required by /usr/lib/libpng16.so.16)
kde-open5: /tmp/awscli/v2/2.0.0dev4/dist/libz.so.1: no version information available (required by /usr/lib/libpng16.so.16)
kde-open5: symbol lookup error: /usr/lib/libpng16.so.16: undefined symbol: inflateReset2, version ZLIB_1.2.3.4
```

Immediately of notice is the mixing of system libraries and the ones bundled with the AWS CLI. In my case the mismatch in version is enough to get some errors, in addition to failing the command. We're using the stdlib `webbrowser` module to do this which will obey the `BROWSER` env var. Tried setting `xdg-open` and `firefox`, neither of which worked.

This is because pyinstaller sets `LD_LIBRARY_PATH` which then bleeds into any subprocess calls which in turn causes the browser not to open. I think if we can somehow remove `LD_LIBRARY_PATH` from being passed to the subprocess env we can get this work, but that's a little tricky given we aren't directly making the subprocess call.

**Comment by joguSD** [comment] 2020-03-05 18:35
This should be fixed in AWS CLI V2. Let me know if you're still running into issues using the latest version.

**Closed** 2020-03-05 18:35 UTC
Labels: bug, v2

**Comment by alfonso-presa** [comment] 2020-10-22 21:20
Hi,

we have a custom credential process, and it's failing apparently because of this issue. It's a python 3 development that bootstraps a webserver and opens a webbrowser to receive credentials from our own IDP. The browser never opens.

Unsetting LD_LIBRARY_PATH prior to executing our tool in the `credential_process` entry inside `sh -c` solves the issue, but it's kind of hacky.

To reproduce the problem easily just add this to the aws config file in a linux machine:

```
[profile fake]
credential_process=google-chrome www.google.es
```
Then run `AWS_PROFILE=fake aws s3 ls` from a terminal.

Obviously it will fail as not credentials would be provided, but the expected behaviour would be to open the browser, and it would not.

Changing the config to:

```
[profile fake]
credential_process=bash -c "unset LD_LIBRARY_PATH; google-chrome www.google.es"
``` 
Would make the browser star opening.

**Comment by Anil2421** [comment] 2023-07-28 11:57
this worked for me-
sudo apt install xdg-utils wslu sshuttle
