### ISSUE TITLE
Support generating presigned PUT URLs for S3

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-cli#6855] opened 2022-04-07 04:29 UTC
### Describe the feature

This is really a re-reporting of #5923 which was closed for being stale but it wasn't.

Currently the `aws s3 presign` subcommand only supports generating presigned URLs for GET:

https://github.com/aws/aws-cli/blob/v2/awscli/customizations/s3/subcommands.py#L699

It'd be good if we could generate pre-signed URLs for POST/PUT commands too.

### Use Case

I often have a need to upload files to an S3 bucket independent of the "where" of that file - e.g. the final database dumps when decommissioning servers; it would be great if I could generate a very short lived URL that I can copy and paste between my terminals rather than having to either download the file to my local or push my access keys up to the server.

### Proposed Solution

Implement a `--method` flags to the subcommand that would have a default value of `GET`, that would allow passing in `PUT` as well - optionally there could be other flags to support extended options.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2

### Environment details (OS name and version, etc.)

Ubuntu

**Comment by G-Rath** [comment] 2022-04-07 04:31
@AdrianCX in your issue you said you could provide a PR - is that something you'd still be interested in doing? I'm keen to see this feature landed, but Python is not one of my primary languages and I've got a few other things on so don't know if I'll have the skills and time to be able to implement this, but you might. I am happy (and can spare the time) to help with the PR, I just don't think I can do it by myself 😓

**Comment by aaoswal** [comment] 2022-04-07 19:30
Hi @G-Rath,
Thank you for submitting the feature request. We will review this further to help prioritize it in a future release. 

I would also like to request the community to make sure to 👍🏼 this `feature-request` to help us understand the community needs better.

**Comment by aaoswal** [comment] 2022-04-07 20:32
Hi @G-Rath,
This seems to be a duplicate of #3050.
Hence, Closing this issue in favor of the original one.

**Closed by aaoswal** 2022-04-07 20:32 UTC
Labels: feature-request, s3

**Comment by G-Rath** [comment] 2022-04-07 20:38
@aaoswal and it's even got a PR, awesome! I did try and search for existing issues but guess my keywords didn't hit the right notes to turn that one up 🙈
