### ISSUE TITLE
s3 sync attempts to sync files it was not asked to sync, and produces an error

### ISSUE THREAD

**Issue by entitycs** [aws/aws-cli#3493] opened 2018-08-07 02:15 UTC
I synced my s3 bucket to /home/myfolder (eg. aws s3 sync s3://mylaunchbucket /home/myfolder).  That worked fine, and it was synced a week ago.

Now **I have one solitary file in a separate s3 bucket** eg (s3://mybucket/.bashrc)

I run the following command:

`aws s3 sync s3://mybucket /home/myfolder --include ".bashrc" --exclude "*"`

And what I get in return:

----------ERROR-------

warning: Skipping file /home/ironfist/.c9/bridge.socket. File is character special device, block special device, FIFO, or socket.

warning: Skipping file /home/ironfist/.c9/6ed698f93b18464b8f578be52e2d965f/collab.sock. File is character special device, block special device, FIFO, or socket.

warning: Skipping file '03_\xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe_\xd0\xbf\xd0\xbe_\xd1\x8d\xd0\xba\xd1\x81\xd0\xbf\xd0\xbb\xd1\x83\xd0\xb0\xd1\x82\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8.rst'. There was an error trying to decode the the file '03_\xd0\xa0\xd1\x83\xd0\xba\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb4\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe_\xd0\xbf\xd0\xbe_\xd1\x8d\xd0\xba\xd1\x81\xd0\xbf\xd0\xbb\xd1\x83\xd0\xb0\xd1\x82\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8.rst' in directory "/home/ironfist/.c9/node_modules/nak/node_modules/isbinaryfile/tests/fixtures/".

Please check your locale settings. The filename was decoded as: ANSI_X3.4-1968

On posix platforms, check the LC_CTYPE environment variable.

warning: Skipping file '\xc3\xa6.txt'. There was an error trying to decode the the file '\xc3\xa6.txt' in directory "/home/ironfist/.c9/node_modules/nak/tests/sorting_fixtures/".

Please check your locale settings. The filename was decoded as: ANSI_X3.4-1968

On posix platforms, check the LC_CTYPE environment variable.

warning: Skipping file /home/ironfist/repo/frontend/sess. File does not exist.

warning: Skipping file /home/ironfist/repo/frontend/trainings. File does not exist.

warning: Skipping file /home/ironfist/repo/frontend/contests. File does not exist.

warning: Skipping file /home/ironfist/sandbox/frontend/laravel. File does not exist.

warning: Skipping file /home/ironfist/sandbox/frontend/trainings. File does not exis

---Error truncated----

**Comment by pyrtsa** [comment] 2018-08-07 06:34
This looks like a duplicate of https://github.com/aws/aws-cli/issues/1588. (I'll share my findings there.)

**Comment by jamesls** [comment] 2018-08-08 20:46
I agree this looks like a dupe of #1588.  @entitycs, can you confirm @pyrtsa's comment [here](https://github.com/aws/aws-cli/issues/1588#issuecomment-411024387).  If so we can close this as a dupe of track the issue over at #1588.

**Comment by entitycs** [comment] 2018-08-13 13:35
Confirmed.  Thanks.

On Wed, Aug 8, 2018 at 2:46 PM, James Saryerwinnie <notifications@github.com

**Comment by jamesls** [comment] 2018-08-13 17:32
Thanks, closing.

**Closed by jamesls** 2018-08-13 17:32 UTC
Labels: duplicate
