### ISSUE TITLE
AWS CLI v2.15.30 needs --policy-name as required argument instead of optional when performing `kms get-key-policy`

### ISSUE THREAD

**Issue by TejasRGitHub** [aws/aws-cli#8835] opened 2024-08-01 14:47 UTC
### Describe the bug

While performing `aws kms get-key-policy `, for all the other CLI versions, the `--policy-name` is an optional argument but for v2.15.30 this is a required argument. 

Also I couldn't find the documentation of v2.15.30. 

For the latest aws cli v2, this is  an optional argument as well. Thus, I think it is a bug in AWS CLI v2.15.30 

### Expected Behavior

--policy-name arg should be optional 

### Current Behavior

--policy-name arg is required

### Reproduction Steps

1. Create a KMS key
2. Install AWS CLI v2.15.30 ( https://docs.aws.amazon.com/cli/latest/userguide/getting-started-version.html )
3. Open terminal , perform `aws kms get-key-policy --key-id <YOUR_KEY_ID> `
4. This should fail with the usage instructions

### CLI version used

2.15.30

### Environment details (OS name and version, etc.)

mac

**Comment by tim-finnigan** [comment] 2024-08-02 18:25
Thanks for reaching out. It looks like this was change introduced in [2.15.31](https://github.com/aws/aws-cli/blob/bf3709f9838141c5eae99621bbec9114f6a1ed19/CHANGELOG.rst?plain=1#L874):
>* api-change:``kms``: Adds the ability to use the default policy name by omitting the policyName parameter in calls to PutKeyPolicy and GetKeyPolicy

So from 2.15.31 onward the `policyName` can be omitted. Closing as not a bug but expected behavior based on the version. Will also link documentation for reference:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kms/get-key-policy.html
* https://docs.aws.amazon.com/kms/latest/APIReference/API_GetKeyPolicy.html

**Closed by tim-finnigan** 2024-08-02 18:25 UTC
Labels: bug, investigating, needs-triage
