### ISSUE TITLE
Random Read timeout error during reading from S3 from Lambda in VPC

### ISSUE THREAD

**Issue by OleksiiYeromenko** [aws/aws-cli#7309] opened 2022-09-29 08:51 UTC
### Describe the bug

Randomly from time to time AWS Lambda throws such errors when trying to read a file with a list of JSONs from s3.
Lambda is inside VPC, S3 - outside.
File size is less then 25Mb, there is no clear pattern, hard to reproduce, but it could be related with the load.     
It could be up to 3-5 times per day receiving such errors:  
```
[ERROR] ReadTimeoutError: Read timeout on endpoint URL: "None"
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 234, in lambda_handler
    raise e
  File "/var/task/lambda_function.py", line 230, in lambda_handler
    jsons_list = read_json_data(boto_streaming_body)
  File "/var/task/lambda_function.py", line 46, in read_json_data
    for line in body.iter_lines():
  File "/var/runtime/botocore/response.py", line 118, in iter_lines
    for chunk in self.iter_chunks(chunk_size):
  File "/var/runtime/botocore/response.py", line 131, in iter_chunks
    current_chunk = self.read(chunk_size)
  File "/var/runtime/botocore/response.py", line 85, in read
    raise ReadTimeoutError(endpoint_url=e.url, error=e)
```

File on s3 is ok, if copy it again - all fine. Issue could be with very frequent and heavy reading from s3, but can't debug as it's unstable happens not frequently.  

Code example:
```

  for record in records:
        data = json.loads(record['Sns']['Message'])
        bucket = data['Records'][0]['s3']['bucket']['name']
        key = unquote_plus(data['Records'][0]['s3']['object']['key'], encoding='utf-8')
        logging.info(f"### bucket: {bucket} \n file: {key}")    
        try:
            response = s3.get_object(Bucket=bucket, Key=key)
            boto_streaming_body = response['Body']  

            jsonsList =[]
            for line in boto_streaming_body.iter_lines():
                try:
                    data_json = json.loads(line)
                    jsonsList.append(data_json) 
                except:
                    logging.info(f'Error in json.loads reading json transaction from a file')   
                
 
        except Exception as e:
            logging.error(e)
            logging.error('Error getting object {} from bucket {}. Make sure they exist and your bucket is in the same region as this function.'.format(key, bucket))
            raise e

```

### Expected Behavior

Reading files from S3 without errors. Or at least understand the reason for error.

### Current Behavior

I have tried to change timeout and retries - no result.
( `Config(connect_timeout=100,read_timeout=100, retries={'max_attempts': 10})`)

In debug see that botocore.retryhandler [DEBUG] No retry needed., in Response metadata also 'RetryAttempts': 0.

![image](https://user-images.githubusercontent.com/50664057/192984335-a16e8a9a-50ad-4c13-8850-17e24273d3ca.png)

### Reproduction Steps

It's hard to reproduce as it happens randomly few times per day. But could be related that we have multiple lambdas reading frequently files up to 25Mb from s3.

```
 response = s3.get_object(Bucket=bucket, Key=key)
 boto_streaming_body = response['Body']  
 for line in boto_streaming_body.iter_lines()::
...
```

### Additional Information/Context

Log with boto debug:  
![image](https://user-images.githubusercontent.com/50664057/192984508-1006a578-9897-4b66-8605-8d0bcd43c905.png)

### CLI version used

2.7.34

### Environment details (OS name and version, etc.)

AWS Lambda, Python 3.8, x86_64

**Comment by tim-finnigan** [comment] 2022-09-29 16:08
Hi @OleksiiYeromenko thanks for reaching out. It looks like this is a duplicate of https://github.com/boto/botocore/issues/2764. That repository is a better place for the issue since you're using boto3, and both the AWS CLI and boto3 use botocore for their low-level functionality. 

Have you tried using `tcp_keepalive` as discussed in the other issue? If that still doesn't resolve the problem then I think we should reach out to the Lambda or VPC teams for more insight since it sounds like you've narrowed the problem down and it only occurs in Lambda when using a VPC.

**Comment by OleksiiYeromenko** [comment] 2022-09-29 16:43
Sorry, as I understand it's not boto3 isssue, but more from AWS side.  Anyway, Today I needed to copy a large amount of data and it's  definetly much more errors when load increases. 
Now I'm trying to test with  `tcp_keepalive=true` but  I can't figure out how to change it in Lambda - 
I can't set it with botocore.client Config..

**Comment by tim-finnigan** [comment] 2022-09-29 16:55
Thanks @OleksiiYeromenko for following up. There is a [recent PR](https://github.com/boto/botocore/pull/2766) to allow setting `tcp_keepalive` on the Config object that I expect to be merged soon. I also followed up [here](https://github.com/boto/botocore/issues/2764#issuecomment-1262502338) on the other issue with a couple more articles that I think are more directly related to your workflow. The [first article](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-troubleshoot-invocation-timeouts/) I linked there mentions: 

> **Note:** Lambda removes idle connections to downstream resources. To allow your function to maintain a persistent connection, use the [tcp_keepalive](https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-tcp_keepalive.html) variable that's associated with the Lambda runtime that you're using.

**Comment by OleksiiYeromenko** [comment] 2022-10-09 22:07
Sorry, @tim-finnigan , thank you for your support, we've fixed an issue, it was indeed related to the VPC endpoint - requests to s3 were going through internal network, external Internet and then hit S3, very long trip. After switching to VPC endpoint no errors anymore.

**Comment by tim-finnigan** [comment] 2022-10-10 15:51
Thanks @OleksiiYeromenko for letting us know! I'll go ahead and close this issue.

**Closed by tim-finnigan** 2022-10-10 15:51 UTC
Labels: bug, lambda, response-requested
