### ISSUE TITLE
Invalid length for parameter when running aws secretsmanager create-secret --name babbelfisch1 --generate-cli-skeleton output

### ISSUE THREAD

**Issue by ustrahlendorf** [aws/aws-cli#6846] opened 2022-04-04 11:55 UTC
### Describe the bug

When running the following cli-command: 
aws secretsmanager create-secret --name babbelfisch1 --generate-cli-skeleton output

I get following answer:

Parameter validation failed:
Invalid length for parameter ARN, value: 3, valid min length: 20
Invalid length for parameter VersionId, value: 9, valid min length: 32

### Expected Behavior

No error,
response in json notification with data that was defined from the platform that describes the new created secret (ARN, ..)

### Current Behavior

Error: Parameter validation failed:

### Reproduction Steps

Execute:
aws secretsmanager create-secret --name babbelfisch1 --generate-cli-skeleton output

### CLI version used

aws-cli/2.2.46 Python/3.8.8 Darwin/20.6.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

macOS Big Sur; Version 11.6.4

**Comment by aaoswal** [comment] 2022-04-05 00:40
Hi @ustrahlendorf,
Thank you for submitting the issue.
I would like to request you to please provide some context on the use-case for using `aws secretsmanager`[create-secret](https://awscli.amazonaws.com/v2/documentation/api/2.0.33/reference/secretsmanager/create-secret.html) `--name babbelfisch1 --generate-cli-skeleton output` command?

If provided with no value or the value `input`, prints a sample input JSON that can be used as an argument for `--cli-input-json`. Similarly, if provided `yaml-input` it will print a sample input YAML that can be used with `--cli-input-yaml`.

Thank you for your patience.

**Comment by ustrahlendorf** [comment] 2022-04-05 12:54
Hi Anish,
my use case: get an idea how the output will look like when executing the command in a dry-run mode. This information will be used to define a JMESH.Path filter to extract only the newly created ARN and save this value in a shell-variable with --output text. The variable will be used in a following process.

Hope this gives an idea what I try to achieve.

Regards
Uwe

**Comment by aaoswal** [comment] 2022-04-05 19:23
Hi @ustrahlendorf,
`--generate-cli-skeleton output` validates the command inputs and returns a sample output JSON for that command. This would only print out the structure of the response output.

The response received would be not the same but similar to [CreateSecret API](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html#API_CreateSecret_ResponseSyntax):

```
{ 
    "ARN": "string", 
    "Name": "string", 
    "ReplicationStatus": [ 
        { "KmsKeyId": "string", 
        "LastAccessedDate": number, 
        "Region": "string", 
        "Status": "string", 
        "StatusMessage": "string" 
        }
      ], 
    "VersionId": "string" 
}
```

I am able to confirm that this is a `bug` which is a duplicate of https://github.com/aws/aws-cli/issues/2337
Hence, I would be closing this issue and track progress of this `bug` in #2337.

Thank you for your patience.

**Closed** 2022-04-15 19:19 UTC
Labels: bug, closing-soon, secretsmanager
