### ISSUE TITLE
Invalid '-e' flag for docker login generated by ecr get-login

### ISSUE THREAD

**Issue by panga** [aws/aws-cli#2753] opened 2017-08-07 18:23 UTC
Problem:
The 'ecr get-login' command is generating an incompatible syntax for latest docker version.
Docker 17.06 doesn't support the deprecated '-e' flag anymore and give the following error:
```
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```

**This is a blocker for all my scripts using aws ecr get-login.**

Command:
`aws ecr get-login`

Result:
`docker login -u AWS -p <token> -e none https://<accountid>.dkr.ecr.us-east-1.amazonaws.com`

Versions:
aws-cli/1.11.129 Python/2.7.10 Darwin/16.7.0 botocore/1.5.92
Docker version 17.06.0-ce, build 02c1d87

'--email' flag removal PR: https://github.com/docker/cli/pull/143

**Comment by joguSD** [comment] 2017-08-07 18:52
You can remove that by specifying the `--no-include-email` flag. We default to including the email so we don't break customers still relying on it.

Duplicate of #2743, #2732, #2694, #2691, #2676, and a few others

**Closed by joguSD** 2017-08-07 18:52 UTC
Labels: duplicate

**Comment by AndrewRayCode** [comment] 2019-03-06 21:50
@joguSD Looks incorrect, I'm getting
```
unknown flag: --no-include-email
```
Removing the `-e none` part of the aws login command entirely let me log in though

**Comment by schematical** [comment] 2019-04-17 21:29
+1 getting the same as @AndrewRayCode

**Comment by tarikozket** [comment] 2019-08-31 04:26
(@AndrewRayCode @schematical)

@joguSD means using `aws ecr get-login --no-include-email`. It worked perfectly for me!

aws-cli/1.16.102
Docker version 18.06.1-ce
