### ISSUE TITLE
ConstraintException s3 create bucket name to short

### ISSUE THREAD

**Issue by asyba** [aws/aws-cli#3723] opened 2018-11-13 20:37 UTC
With this it fails:
`aws s3api create-bucket --bucket fede-test --profile midwesttrading`

> An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

With this it works:
`aws s3api create-bucket --bucket fede-test-hhhhhhh --profile midwesttrading`

Bad error message should be something like "bucket name to short".

**Comment by justnance** [comment] 2018-11-16 19:43
@asyba - Thank you for reaching out.  I agree this error message could be improved so I have labeled it as such.

**Comment by justnance** [comment] 2019-05-02 22:38
@asyba - I reproduced this behavior under a similar issue and find the following error is reasonable but our documentation needs improvement:

> An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The us-east-1 location constraint

The workaround used with `--profile` may have resolved this issue but may not be the best practicd going forward adn here's why.  As per our [documentation for regions and endpoints for s3](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region):

> Amazon S3 renamed the US Standard Region to the US East (N. Virginia) Region to be consistent with AWS regional naming conventions. There is no change to the endpoint and you do not need to make any changes to your application.

> If you use a region other than the US East (N. Virginia) endpoint to create a bucket, you must set the LocationConstraint bucket parameter to the same region. Both the AWS SDK for Java and AWS SDK for .NET use an enumeration for setting location constraints (Region for Java, S3Region for .NET). For more information, see PUT Bucket in the Amazon Simple Storage Service API Reference.

As such, the location constraint error occurs when the bucket was created or located in a region other than the default region (us-east-1).   [If you send your create bucket request to the s3.amazonaws.com endpoint, the request go to the us-east-1 region.](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html).  Basically, the `location constraint` is not a required parameter when using `us-east-1` but is required when using other regions.  An example:
 
```
aws s3api create-bucket --bucket mybucket --create-bucket-configuration LocationConstraint=us-west-2
```

Another option is use [s3 mb](http://docs.aws.amazon.com/cli/latest/reference/s3/mb.html) which using the global options --region and --endpoint-url to redirect the request:

```
aws s3 mb s3://mybucket --region us-west-2 --endpoint-url https://s3.us-west-2.amazonaws.com
```

It appears our documentation and examples require some improvement around this topic so I have escalated this issue internally to our documentation writers. 

Related issues:  #3567 #3510 #2603 #3723 #3044 #2138 #589 #90

**Comment by justnance** [comment] 2019-05-06 14:39
closing this issue because we are tracking the progress under #3567

**Closed** 2020-08-31 20:42 UTC
Labels: confusing-error, enhancement, s3, s3api
