### ISSUE TITLE
Dynamodb can't accept a key with an explicitly NULL value.

### ISSUE THREAD

**Issue by jcoyne** [aws/aws-cli#3135] opened 2018-02-07 17:01 UTC
I am attempting to create a table with a single primary key(called `id) and a secondary index (called `source_id`).

I create the table like so:

```
aws dynamodb create-table --table-name resources  
        --attribute-definitions AttributeName=id,AttributeType=S 
           AttributeName=source_id,AttributeType=S
        --key-schema AttributeName=id,KeyType=HASH
        --provisioned-throughput=ReadCapacityUnits=5,WriteCapacityUnits=5
        --global-secondary-indexes "IndexName=ResourceBySourceID,\
  KeySchema=[{AttributeName=source_id,KeyType=HASH}],\
  Projection={ProjectionType=KEYS_ONLY},\
  ProvisionedThroughput={ReadCapacityUnits=5,WriteCapacityUnits=5}"
```

Now I can insert values into the table without `source_id` and it seems to work:
```
$ aws dynamodb put-item --table-name resources --item '{"id":{"S":"9999"}}'

$ aws dynamodb scan --table-name resources
{
    "Count": 1,
    "Items": [
        {
            "id": {
                "S": "9999"
            }
        }
    ],
    "ScannedCount": 1,
    "ConsumedCapacity": null
}
```

And, I can specify a value of `source_id` and this also seems to work:

```
$ aws dynamodb put-item --table-name resources --item '{"id":{"S":"9997"},"source_id":{"S":"1231"}}'

$ aws dynamodb scan --table-name resources
{
    "Count": 2,
    "Items": [
        {
            "id": {
                "S": "9999"
            }
        },
        {
            "source_id": {
                "S": "1231"
            },
            "id": {
                "S": "9997"
            }
        }
    ],
    "ScannedCount": 2,
    "ConsumedCapacity": null
}
```

But if I explicitly set the value of `source_id` to `NULL` I get an exception:

```
$ aws dynamodb put-item --table-name resources --item '{"id":{"S":"9996"},"source_id":{"NULL":true}}'

An error occurred (ValidationException) when calling the PutItem operation: Invalid attribute value type
````

**Comment by kyleknap** [comment] 2018-02-08 00:31
Hi @jcoyne thanks for the steps! That is really helpful. So I actually followed the steps end to end and I got the following message from dynamodb on the last step:
```
An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: Type mismatch for Index Key source_id Expected: S Actual: NULL IndexName: ResourceBySourceID
```
This error message is much more helpful than the one you got (I am not quite sure how that happened), but it looks like the issue is because you declared the source_id's schema as a string and you cannot set its type as NULL for an item if the attribute is being used as an index in your table. So you will probably have to restructure your table's schema or for the values that you are planning to use for `source_id`. Hope this helps. Let us know if you have any more questions.

**Comment by jcoyne** [comment] 2018-02-08 02:27
@kyleknap thanks for responding.  Don't your findings seem to run contrary to what is written about sparse indexes here? https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForGSI.html#GuidelinesForGSI.SparseIndexes  That seems to indicate it would be okay if the key value isn't present. 

Maybe there's a disagreement over the significance of NULL (Oh no!).  Are you saying that NULL is semantically different than the value being not present? 

I am using the https://github.com/aws/aws-sdk-go library for making these requests. Do you think I ought to open a bug on their repository?

**Comment by JordonPhillips** [comment] 2018-02-23 22:35
@jcoyne it looks like the issues you're running into are on the service level, so opening a bug on the go sdk won't help as they will behave exactly the same. You may want to open a support ticket, or ask on the service forums / stackoverflow to engage people with more service specific expertise.

**Comment by lafiosca** [comment] 2018-02-23 22:40
Yes, `null` is semantically different from a non-existent key. I am unfamiliar with Go, but the distinction comes up often in JavaScript. You can also see it visualized in the Dynamo console. A null value is represented by a field of type "null" with value `true` in DynamoDB's explicit representation.

**Comment by joguSD** [comment] 2018-03-14 22:34
Closing out here as there's no action for us to take on the SDK side.

**Comment by elipeters** [comment] 2018-04-06 04:03
Is an empty string also not a string?

`Error: the value of subtitle is not allowed to be empty`

We could solve these issues at the adapter by conditional omission which are just sideline fixes to what other database models like MongoDb don't require. Consider that RESTful api's may send empty and null - **maybe we should make all fields required**?

**Comment by jamesls** [comment] 2018-06-20 20:21
Following up here, I don't think there's anything actionable on the CLI side.  Both Kyle and Jordan have given some explanation about what's happening, and it looks like the linked issue on the go sdk has been closed.

Let me know if I missed anything and we can reopen and take another look.

**Closed by jamesls** 2018-06-20 20:21 UTC

**Comment by mrcoles** [comment] 2024-06-05 04:23
If anyone else runs into this from a search result, the DynamoDB update expression needs to be a REMOVE instead of a SET. You can’t set a GSI value to null, you have to remove it: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.REMOVE
