### ISSUE TITLE
Credential-less cross-acount profile switching

### ISSUE THREAD

**Issue by usrenmae** [aws/aws-cli#1604] opened 2015-10-29 09:38 UTC
I'd like to switch across AWS accounts via the profiles defined like so:
```
[default]
aws_access_key_id = xxx
aws_secret_access_key = yyy

[secondAccount]
role_arn = arn:aws:iam::222222222:role/deployer
source_profile = default

[thirdAccount]
role_arn = arn:aws:iam::333333333:role/deployer
source_profile = default
```
using it like this
```
$ AWS_PROFILE=secondAccount aws s3 ls
$ AWS_PROFILE=thirdAccount aws s3 ls
```
And this works ok with current `awscli` once the `[default]` section is defined and populated with credentials.
The commands themselves run in the EC2 instance which has a IAM role assigned. Instance itself lives in another firstAccount of the AWS. I do not need any credentials stored for this instance because those are fetched from the meta-service via `http://169.254.169.254/latest/meta-data/iam/security-credentials/` calls.
The problem is that I cannot run `awscli` without specifying the `[default]` section, or leaving this section empty, assuming the IAM role credentials of the machine are the default credentials. Currently when my `[default]` section is empty, `awscli` is not able to run with neither `secondAccount` nor `thirdAccount` profile, asking me the default's profile credentials.

Expected:
```
[default]
# empty profile

[secondAccount]
role_arn = arn:aws:iam::222222222:role/deployer
source_profile = default

[thirdAccount]
role_arn = arn:aws:iam::333333333:role/deployer
source_profile = default
```
when running `AWS_PROFILE=thirdAccount aws s3 ls` I expect the default profile acting on behalf of the role the current EC2 machine is running under.

The scenario is that I have Jenkins machine in AWS account:1 EC2. The machine performs deployments of the AWS infra to different accounts: 2 and 3 with ansible. From both accounts 2 and 3 I have provided access to account:1's role to act on their behalf. I do not want to store any credentials on Jenkins machine.

**Comment by JordonPhillips** [comment] 2015-10-29 18:04
This is a difficult situation to address without knowing the exact policies you have in place. As a test I completely commented out my default profile and performed some commands with another profile I had already set up. Everything worked as expected. However, if the other roles you have don't have full access to S3, the `aws s3 ls` command will fail with an Access Denied error.

More to the point, I don't understand why you need to use the shared credentials file in the first place. You already have a role assigned to the instance, why not just [grant it access](http://docs.aws.amazon.com/IAM/latest/UserGuide/walkthru_cross-account-with-roles.html) to the relevant resources in your other accounts?

**Comment by usrenmae** [comment] 2015-10-29 20:46
@JordonPhillips 
> why not just grant it access to the relevant resources in your other accounts?

That's exactly what I do. Let me try to explain it on example:
I am on EC2 instance of AWS account 1111. The instance has a `Deployer` role assigned. So it can call AWS API it has access to.
- Case 1: No `~/.aws/*` files exist 
```bash
acc1111instance $ aws s3 ls
1-s3-bucket-for-1111-acount
2-s3-bucket-for-1111-account
...
```
I bring a particular S3 API call in my example just because it's short enough. I actually call EC2 API to run instances.
All nice so far. No need to keep any credentials on the machine.

- Case 2: Call API on behalf of 2222 account user

Account 2222 has a user `poweruser`, which has policy to allow a `Deploy` user from account 2222 act on its behalf. No `~/.aws/*` files still exit, same machine:
```bash
acc1111instance $ aws sts assume-role --role-arn arn:aws:2222:user/poweruser
{..."Credentials": {"SecretAccessKey":"aaa","SessionToken":"bbb","AccessKeyId":"ccc"... }... }
acc1111instance $ export AWS_ACCESS_KEY_ID=ccc
acc1111instance $ export AWS_SECRET_ACCESS_KEY=aaa
acc1111instance $ export AWS_SESSION_TOKEN=bbb
acc1111instance $ aws s3 ls
1-s3-bucket-for-2222-acount
2-s3-bucket-for-2222-account
```
- Case 3:

Now I figure out that `awscli` provides a special configuration trick exactly for my case, so I can act on behalf of another account's user using the `--profile` parameter or the `AWS_DEFAULT_PROFILE` environment variable.
So insted of calling the `assume-role` myself and handle the temporary credentials, I just run
```
acc1111instance $ AWS_DEFAULT_PROFILE=account2 aws s3 ls
1-s3-bucket-for-2222-acount
2-s3-bucket-for-2222-account
````
For this I need to define the `account2` profile in my `~/.aws/credentials` file

- Case 3.1:
```bash
acc1111instance $ cat ~/.aws/credentials
[default]
# empty profile
[account2]
role_arn = arn:aws:iam::2222:role/poweruser
source_profile = default

acc1111instance $ AWS_DEFAULT_PROFILE=account2 aws --debug s3 ls
...
    'sts', aws_access_key_id=source_cred_values['aws_access_key_id'],
KeyError: 'aws_access_key_id'
...
```
I would expect when I reference a `default` profile from the `source_profile` of another profile, it would take a `Deployer` role credentials. But it just tells that it's missing a key_id. But there is no key_id for the role I want to keep in any of locally stored files.

**Comment by kyleknap** [comment] 2015-11-03 22:44
This looks like a duplicate of https://github.com/aws/aws-cli/issues/1390. Feature request seems reasonable to me. Closing this issue in favor of the referenced issue. Let's track progress on that issue.

**Closed by kyleknap** 2015-11-03 22:44 UTC
Labels: question
