### ISSUE TITLE
`aws cloudfront list-distributions` doesn't list disabled distributions

### ISSUE THREAD

**Issue by sgametrio** [aws/aws-cli#6410] opened 2021-09-21 07:43 UTC
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I'd like to get a list of all the disabled distributions I have in Cloudfront but the command returns only the Enabled ones.

**SDK version number**
aws-cli/2.1.25

**Platform/OS/Hardware/Device**
aws-cli/2.1.25 Python/3.7.3 Linux/5.11.0-7612-generic exe/x86_64.pop.20 prompt/off

**To Reproduce (observed behavior)**
1. Make sure you have at least one Disabled distribution linked to your account and region.
1. `aws cloudfront list-distributions --no-paginate --query="DistributionList.Items[*].Enabled`

You will see that the entire list is made by `true` and no `false`-

**Expected behavior**
At least one `false` result.

**Comment by stobrien89** [comment] 2021-09-21 14:52
Hi @sgametrio,

Sorry to hear you're having issues.  I attempted to reproduce, but my disabled distribution was reflected in the query. 

I'm not sure what the default page size is for this operation, but if you have a large number of distributions, it's possible that the disabled distributions are not being included in the first page of results, which is what the `--no-paginate` option limits the result set to.

Another possibility is that the initial behavior for this operation was to only return enabled distributions.  Updates to API operations are pushed to the SDK service models periodically and it's possible that the version you're using does not include the current behavior.  

I'd try toggling the `--no-paginate` option to see if that allows you to see any disabled distributions, but it might also be worth bumping the CLI version as well since `2.1.27` was released in February.  Let me know if this helps!

**Comment by sgametrio** [comment] 2021-09-21 15:11
@stobrien89 I thank you so much for your answer! I totally misread the `--no-paginate` option and indeed my distribution was not in the first page.

Removing the `--no-paginate` option and increasing the default `--page-size` showed the disabled distributions too.

Thanks very much, I will close the issue :)

**Closed** 2021-09-21 15:12 UTC
Labels: guidance, response-requested, cloudfront
