### ISSUE TITLE
Support AWS console federation

### ISSUE THREAD

**Issue by waldiTM** [aws/aws-cli#7547] opened 2022-12-25 16:41 UTC
### Describe the feature

AWS can do console logins even without password, for example with access keys. The API to do that is sadly not a standard AWS API. The [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/example_sts_Scenario_ConstructFederatedUrl_section.html) just circulates a Python script to do that.

### Use Case

If I just have an access key, sometimes I want to do manual tests and using the AWS console is then the easiest solution. Going from access key to console log is supported, but only using unrelated scripts.

### Proposed Solution

Add a command that uses the normal aws-cli authentication to create a console login URL.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CLI version used

2.9.9

### Environment details (OS name and version, etc.)

Debian Unstable

**Comment by tim-finnigan** [comment] 2022-12-27 19:02
Hi @waldiTM thanks for the feature request. This appears to be a duplicate of https://github.com/aws/aws-cli/issues/4642. We recommend adding a 👍 to that issue to show your support, and feel free to leave a comment there if you had any more info to share regarding your use case.

**Closed by tim-finnigan** 2022-12-27 19:02 UTC
Labels: feature-request, needs-triage
