### ISSUE TITLE
s3 sync: better/selectable strategy when source has much less objects than destination

### ISSUE THREAD

**Issue by oakad** [aws/aws-cli#6374] opened 2021-09-01 09:37 UTC
It may be a corner case, but I do believe it's not that uncommon.

Let's say there's a bucket shared across many users. There are many objects in the bucket, but each individual user is only interested to transfer a small number of objects that changed (this is essentially a typical VCS pattern which surfaces quite often).

Clearly, the `--delete` flag is not used here, we just want to upload objects that changed from a small subset of all objects.

It appears that in this particular situation `s3 sync` will still scan the entirety of the remote bucket and thus execute rather slowly. A more efficient approach will be to only scan the source files and HEAD the relevant destination objects.

May it be possible to add a flag that alters the sync strategy depending on the use case (full remote scan vs selective remote HEAD)?

**Comment by stobrien89** [comment] 2021-09-02 15:47
Hi @oakad,

Thanks for reaching out!  It looks like this is a duplicate of #2800.  We had a discussion about this as a team yesterday and are open to adding a flag to alter the sync strategy like you suggested, but we do have a large backlog of sync feature requests, so it's difficult to tell when we'd be able to implement this.  Feel free to track the above issue for any further updates!

**Closed by stobrien89** 2021-09-02 15:47 UTC
Labels: duplicate, feature-request, s3syncstrategy
