### ISSUE TITLE
aws logs tail should support selecting a stream

### ISSUE THREAD

**Issue by ragebiswas** [aws/aws-cli#5702] opened 2020-11-09 03:00 UTC
**Is your feature request related to a problem? Please describe.**
Not able to select a stream in a log group while performing `aws logs tail`

**Describe the solution you'd like**
The `--stream` arg should be added for users to supply the exact stream name.

**Describe alternatives you've considered**
Couldn't find any - the only alternative was hand-rolling a script that uses `get-log-events` for that particular stream.

**Additional context**
The `aws logs tail` command is fantastic and very useful. However, for our use case, we have multiple ec2 instances sending logs to a single CloudWatch log group (as separate streams). It would be very useful to be able to tail logs from a single such instance.

Please let me know if this is already supported in some way that is not obvious to me (apologies in advance if that's the case!)

**Comment by kdaily** [comment] 2020-11-09 20:26
Hu @ragebiswas,

Thanks for the request. I think this is a duplicate of #5560. Give a 👍 on the initial post and comment there to indicate support. Cheers!

**Comment by ragebiswas** [comment] 2020-11-10 02:40
> Hu @ragebiswas,
> 
> Thanks for the request. I think this is a duplicate of #5560. Give a 👍 on the initial post and comment there to indicate support. Cheers!

Done, feel free to close this!

**Closed** 2021-03-29 18:41 UTC
Labels: duplicate, feature-request
