### ISSUE TITLE
Support --help, and maybe -h, for fetching help on commands

### ISSUE THREAD

**Issue by adamchainz** [aws/aws-cli#1937] opened 2016-04-25 14:21 UTC
I've typed `aws something something --help` like a hundred times and been frustrated that I've had to recall that it's without the `--` every time. Nearly every CLI program supports `--help` so it's surprising that `aws` doesn't.

**Comment by JordonPhillips** [comment] 2016-04-25 16:44
Duplicate of #303 / #576

**Closed by JordonPhillips** 2016-04-25 16:44 UTC
Labels: duplicate

**Comment by adamchainz** [comment] 2016-04-25 17:12
Thanks, I couldn't find those after a five minute search
