### ISSUE TITLE
aws eks update-kubeconfig writes an insecure file

### ISSUE THREAD

**Issue by SarahRiley** [aws/aws-cli#5617] opened 2020-10-08 17:23 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws eks update-kubeconfig` writes a world readable, group readable file, which the latest version of helm warns over:

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: config/kube/main-cluster
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: config/kube/main-cluster

-rw-r--r--  1 sarah  staff   2.1K 10 Aug 15:05  config/kube/main-cluster

**SDK version number**
aws-cli/1.18.154 Python/3.5.3 Linux/4.19.76-linuxkit botocore/1.18.13

**Platform/OS/Hardware/Device**
Debian Linux (inside docker)

**To Reproduce (observed behavior)**
1. Run aws eks update-kubeconfig
1. Run a helm operation that uses the generated kubeconfig
1. Observe warinng

**Expected behavior**
A file generated that doesn't create a warning in helm.

**Comment by kdaily** [comment] 2020-10-09 17:09
Hi @SarahRiley, thanks for reporting!

This is a duplicate of #5598, but that's a PR to fix. I'll leave this issue open for more visibility. I've made the owner of the EKS customization aware of the issue.

**Comment by SarahRiley** [comment] 2020-10-09 17:10
Thanks, I searched the issues, but not the pull requests.  Excellent.

**Comment by kdaily** [comment] 2021-03-15 23:13
This has been fixed @SarahRiley! Thanks again.

**Closed by kdaily** 2021-03-15 23:13 UTC
Labels: customization, eks-kubeconfig, enhancement, feature-request
