### ISSUE TITLE
RSA dep not installed anymore

### ISSUE THREAD

**Issue by lwinkler-cloudflight** [aws/aws-cli#5977] opened 2021-02-25 10:29 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
CI suddenly fails on bitbucket runner as RSA python module is not installed anymore:
![image](https://user-images.githubusercontent.com/74179248/109139193-890d1f80-775b-11eb-84b9-f264cf671998.png)

**SDK version number**
see screenshot, both .14 and .15 seem to be affected, did not test further

**Platform/OS/Hardware/Device**
What are you running the cli on?
bitbucket ci, with the following image:
image: atlassian/default-image:2 

**To Reproduce (observed behavior)**
Should be able to just run the above mentioned docker container.
```
docker run -it --rm atlassian/default-image:2 sh
apt-get update && apt-get install -y python3-pip
pip3 install -U "awscli==1.19.15" 
```
-> rsa not installed and certain commands then fail during runtime

**Expected behavior**
rsa is installed as specified in setup.py

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
workaround: specify rsa as a dep in the pip3 install command: `pip3 install -U "awscli==1.19.14" "rsa>=3.1.2,<4.8"`

**Comment by kdaily** [comment] 2021-02-25 17:48
Hi @lwinkler-cloudflight,

This is a duplicate of #5968. Duplicating a comment from there here since it was closed to see if more information about your environment can be obtained:

> Thanks for bringing this to our attention. The change that went out today was adjusting our dependencies for rsa. We've moved our range to versions that no longer support Python 3.5. The AWS CLI did a [deprecation campaign](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-python-3-4-and-3-5-in-the-aws-sdk-for-python-and-aws-cli-v1/) last year for dropping support of 3.4/3.5 at the beginning of Feb 2021.
> 
> What's interesting is modern versions of pip for the last several years prevent what's happening here by refusing to install awscli-1.19.0+ on Python 3.5. Do you know offhand what version of pip your environment is using?
> 
> In the meantime, we'd encourage you to either migrate to the AWS CLI v2, Python 3.6+, or pin to awscli<1.19.
> 
> _Originally posted by @nateprewitt in https://github.com/aws/aws-cli/issues/5968#issuecomment-783774993_

**Comment by lwinkler-cloudflight** [comment] 2021-02-25 18:03
ah did not see the linked issue as i only searched open ones. sorry about that.

the atlassian image (pretty default for bitbucket pipelines) is based on debian/sid and ships with python 3.5.

**Closed** 2021-03-03 18:16 UTC
Labels: duplicate, guidance
