### ISSUE TITLE
cloudformation deploy exits without useful message

### ISSUE THREAD

**Issue by GavinZZ** [aws/aws-cli#8256] opened 2023-10-19 23:38 UTC
### Describe the bug

We had a [customer issue](https://github.com/aws/serverless-application-model/issues/58) cut to SAM repo and I think this is an issue with aws-cli. So creating the same issue here for help.

The following is what the customer described originally

******************************************************************
After running the aws cloudformation package command, I then run deploy and get this:

aws cloudformation deploy --template-file new_template.yml --stack-name stack_name --capabilities CAPABILITY_IAM --profile profile_name
Waiting for changeset to be created..

'Status'

It exits at that point. It gets stuck on the first event:
"ResourceStatus": "REVIEW_IN_PROGRESS",

I am using the code from this example:
https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/hello_world

******************************************************************
We've figured out the root cause where it's because of missing permission when calling the aws cli deployment command. 

### Expected Behavior

Give the error message more meaningful content

### Current Behavior

```
aws cloudformation deploy --template-file new_template.yml --stack-name stack_name --capabilities CAPABILITY_IAM --profile profile_name
Waiting for changeset to be created..

'Status'
```
It exits at that point. 

### Reproduction Steps

Any template with only `cloudformation:DescribeStacks` permission in the profile

### CLI version used

aws-cli/1.11.36 Python/2.7.10 Darwin/16.3.0 botocore/1.4.93

### Environment details (OS name and version, etc.)

N/A

**Comment by tim-finnigan** [comment] 2023-10-24 00:05
Thanks for reporting this issue. It appears to be a duplicate of https://github.com/aws/aws-cli/issues/3982 so I'll close this to continue tracking there. Please feel free to upvote( 👍) that issue.

A couple other notes:
* 1.11.36 is a very old version of the AWS CLI. The latest v1 version if 1.29.69 per the [CHANGELOG](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst?plain=1). We also recommend using v2 of the AWS CLI if possible ([see installation instructions here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).)
* I'm not able to access this link — not sure if it's private or if you intended to link somewhere else:
>I am using the code from this example:
https://github.com/awslabs/serverless-application-model/tree/master/examples/2016-10-31/hello_world

**Closed** 2023-10-24 00:05 UTC
Labels: bug, needs-triage
