### ISSUE TITLE
Please accept `--help` as an alias for `help`

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cli#5832] opened 2020-12-21 10:48 UTC
**Is your feature request related to a problem? Please describe.**

I use UNIX command line tools all day. There is some common UX among most of these tools, the foremost of which is that `--help` brings up a help dialog.

Literally *every time* I use the AWS CLI I instinctively type `aws <service> <command> --help` to have it tell me about the arguments it expects, and *every time* it tells me:

```
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --help
```

This frustrates me every day for no reason. 

**Describe the solution you'd like**

Please just recognize `--help` and treat it as if I typed `help` without the dashes.

It's a tiny change and improves usability by a 1000%.

**Describe alternatives you've considered**

Throwing my computer out of the window and becoming a chef.

**Additional context**

It's hard to express the rage I feel because of this, since the decision to use `help` instead of `--help` wilfully ignores existing conventions, and knowledge transfer from existing tools.

You are forcing me to spend time learning a new command language just for a single tool, and it's not even any benefit attached to learning something new here, it's just arbitrary.

Is your time more important than mine?

**Comment by kellertk** [comment] 2020-12-22 22:14
Closing as a duplicate of #576

**Closed by kellertk** 2020-12-22 22:14 UTC
Labels: feature-request, needs-triage
