### ISSUE TITLE
[cli v2] [request] kms decrypt/encrypt stdin input

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-cli#4037] opened 2019-04-01 19:37 UTC
currently, most of our usage of `aws kms decrypt` follows the pattern:
`aws kms decrypt --ciphertext-blob fileb://<(echo \'${encryptedPass}\' | base64 -d) --output text --query Plaintext | base64 -d`

adding the ability for `aws kms encrypt` and `aws kms decrypt` to take each others' output directly as input would simplify this workflow significantly:

```
alias enc="aws kms encrypt --output text --query CiphertextBlob --key-id $KEY"
alias dec="aws kms decrypt --output text --query Plaintext"
echo 'hello'
| base64
| enc
| dec
| enc
| dec
| base64 -d
```
would return 'hello' in this case (assuming proper key permissions).  AFAIK, this also will not break backward compatibility (since `ciphertext-blob` and `plaintext` are currently only supported as parameters).

Removing the need for `base64` would be ideal, but probably more harmful for backward compatibility.

**Comment by justnance** [comment] 2019-04-29 07:09
@hauntingEcho - Thanks for your post.  Looks like we are tracking a similar issue under #2063.  I'm going to close this issue as a duplicate.

**Closed by justnance** 2019-04-29 07:09 UTC

**Comment by hauntingEcho** [comment] 2019-04-29 16:49
@justnance I disagree - that one is asking a change in base64-ness of input, while this is asking for the ability to take input via the standard input stream rather than via the `--plaintext` or `--ciphertext-blob` arguments.

**Comment by notorand-it** [comment] 2023-01-30 10:27
Please, reopen it. This is not a duplicate of https://github.com/aws/aws-cli/issues/2063 .
Having the ability to pipe whatever secret directly into the `aws kms decrypt` is not just shell friendly, it allows for easier and more secure data processing.
The `<()` construct requires the spawning of another shell instance just to pipe the data through.
Allowing for something like `--ciphertext-blob -` or `--ciphertext-blob stdin://` would make things better.
