### ISSUE TITLE
describe-network-interfaces "--query" not working as expected

### ISSUE THREAD

**Issue by nyw2022** [aws/aws-cli#8388] opened 2023-12-04 21:28 UTC
### Describe the bug

Hi team,

I got the following command from this re:Post [How can I troubleshoot the "You have exceeded the maximum limit for Lambda HyperPlane ... ](https://repost.aws/knowledge-center/lambda-hyperplane-vpc)

```
aws ec2 describe-network-interfaces --region us-east-1 \
  --filters 'Name=vpc-id,Values=VPC' 'Name=status,Values=in-use' \
  --query 'NetworkInterfaces[?InterfaceType=='lambda'].NetworkInterfaceId'
```

When I tested in my account, I was able to get a result with out the "--query" parameter values. When I add the "--query" parameter value `'NetworkInterfaces[?InterfaceType=='lambda'].NetworkInterfaceId'`

THEN nothing shows up even thought the output had the result that are supposed to show up because I checked the raw output. 

Tested this with my colleague and found the same issue on his setup so I'm not the only one experiencing this.

Currently I'm using this command with "jq" to workaround the issue. 
```
aws ec2 describe-network-interfaces --region us-east-1 --filters 'Name=vpc-id,Values=VPC' | jq '.NetworkInterfaces[] | select(.InterfaceType == "lambda") | .NetworkInterfaceId'
``` 

I double checked the officially provided JMESPath to query and result and found nothing wrong, tested with this site [JMESPath Tutorial](https://jmespath.org/tutorial.html)

Check the V2 AWS CLI docs and found that "--query" isn't deprecated.

This is potentially very impactful because its giving false information to whom ever is running this command to troubleshoot their AWS Account/Lambda.

### Expected Behavior

```input
aws ec2 describe-network-interfaces --region us-east-1 \
  --filters 'Name=vpc-id,Values=VPC' 'Name=status,Values=in-use' \
  --query 'NetworkInterfaces[?InterfaceType=='lambda'].NetworkInterfaceId'
```

```output
[
     "eni-A",
     "eni-B",
     "eni-C",
]
```

### Current Behavior

```input
aws ec2 describe-network-interfaces --region us-east-1 \
  --filters 'Name=vpc-id,Values=VPC' 'Name=status,Values=in-use' \
  --query 'NetworkInterfaces[?InterfaceType=='lambda'].NetworkInterfaceId'
```

```output
[]
```

### Reproduction Steps

Create an Lambda with VPC setting in your default or any VPC

use the VPC ID to query the ENI:

```input
aws ec2 describe-network-interfaces --region us-east-1 \
  --filters 'Name=vpc-id,Values=VPC' 'Name=status,Values=in-use' \
  --query 'NetworkInterfaces[?InterfaceType=='lambda'].NetworkInterfaceId'
```

### Possible Solution

```jq more detail
aws ec2 describe-network-interfaces --region us-east-1 --filters 'Name=vpc-id,Values=VPC' | jq '.NetworkInterfaces[] | select(.InterfaceType == "lambda")'
```

```jq ENI ID only
aws ec2 describe-network-interfaces --region us-east-1 --filters 'Name=vpc-id,Values=VPC' | jq '.NetworkInterfaces[] | select(.InterfaceType == "lambda") | .NetworkInterfaceId'
```

### CLI version used

V1 and V2

### Environment details (OS name and version, etc.)

13-inch, 2020, Four Thunderbolt 3 ports, OS 13.5.2 (22G91)

**Comment by nyw2022** [comment] 2023-12-07 15:42
That the crazy thing, I'm using MacOS: 

Environment details (OS name and version, etc.)
`13-inch, 2020, Four Thunderbolt 3 ports, OS 13.5.2 (22G91)`

I tried it on native MacOS Terminal and iTerm2 and only double quotations work.

**Comment by RyanFitzSimmonsAK** [comment] 2023-12-14 23:47
I see the issue.

From https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-filter.html#cli-usage-filter-client-side-select-list, filtering for specific values (InterfaceType in this case) should be using backticks rather than single quotes.  It's a subtle difference, but important because the first single quote around in `?InterfaceType=='lambda'` was closing the single quote from the start of the query.  This query should work with single quotes after making that change.

So, everything appears to be working as intended, and I'll reach out internally about getting the re:Post article fixed.  Thanks again for reporting this.

**Closed** 2024-05-22 21:50 UTC
Labels: bug, ec2, p3
