### ISSUE TITLE
Output is empty, help to fix it?

### ISSUE THREAD

**Issue by lopes-gustavo** [aws/aws-cli#4253] opened 2019-06-19 19:24 UTC
Running the following command gives me an empty output and nothing happened on my lambda code.

`aws lambda update-function-code --function-name my-function-name --zip-file fileb://function.zip`

Running for valid function name and an invalid both gives me an empty output.

What am I doing wrong?

Thanks

**Comment by justnance** [comment] 2019-06-21 22:23
Thank you for posting this issue.  I was not able to reproduce the same results.  The `update-function-code` is working as expected with the latest version of the CLI:

```
aws --region us-east-1 lambda update-function-code --function-name python3 --zip-file fileb://test-direct-upload.zip
{
    "FunctionName": "python3",
    "FunctionArn": "arn:aws:lambda:us-east-1:<acctno>:function:python3",
    "Runtime": "python3.7",
    "Role": "arn:aws:iam::<acctno>:role/service-role/python3-role",
    "Handler": "lambda_function.lambda_handler",
    "CodeSize": 3093,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2019-06-20T01:59:45.220+0000",
    "CodeSha256": "<foobar>=",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "<no-removed>"
}
```

I also attempted to using different scenarios such as non-zip file, an empty zip file, the wrong region, a code size larger than 50 MB, uploaded from a local destination and from s3, and zip files after moving files to a parent directory.  All scenarios returned the expected error handling.  It appears the CLI is working as expected.  We would need the output from the `--debug` option to investigate further.  

I would also recommend opening a [support case with AWS Premium Support](https://console.aws.amazon.com/support/home#/). or post the issue on the [AWS Developer forums](https://forums.aws.amazon.com/forum.jspa?forumID=186) as there will probably be individuals that can provide further help.

**Comment by lopes-gustavo** [comment] 2019-06-24 13:37
After using the `--debug` option, I could see that I was uploading (mistakenly) a large file (300Mb) to the lambda. 
Probably, my working machine (a 500Mb RAM, aws linux 2) couldn't handle the file in memory and failed the upload, silently.

**Comment by justnance** [comment] 2019-06-24 16:07
@lopes-gustavo - Thanks for the feedback.  Looks like the large file of 300 MB exceeded the[ limit set by the Service team](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).   Having an error return like "insufficient ram to upload the file" or "exceed service limits" is a good idea.  It would be a better practice to have the API return the error because the CLI does not control the limits set by the service.  I suggest reaching out to the [Lambda service team on their forums](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).  If you posted the forum ID here I can escalate the feature request internally.

**Comment by lopes-gustavo** [comment] 2019-06-25 17:53
I created this thread: https://forums.aws.amazon.com/thread.jspa?threadID=305287

**Comment by justnance** [comment] 2019-07-03 05:41
@lopes-gustavo - Thank you for your feedback.  I have escalated this issue internally and will close this GitHub issue so we can track the progress on the forum.

**Closed by justnance** 2019-07-03 05:41 UTC
Labels: confusing-error, lambda, service-api
