### ISSUE TITLE
Unable to assume role in latest CLI version - botocore-session?

### ISSUE THREAD

**Issue by owenashurst** [aws/aws-cli#7307] opened 2022-09-28 12:38 UTC
### Describe the bug

I have a script to deploy my CDK stack to a designated AWS account. I have a master account, and a "child" AWS account within the master organisation. A service users credentials in the master account is used to try and assume a role within the child AWS account, however it fails to assume the role.

### Expected Behavior

The role is assumed and the AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN is assigned the new values from the credentials object from the assume command.

### Current Behavior

When these commands run, I get the following error:
`An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::<ChildAWSAccountId>:assumed-role/service/botocore-session-1664316680 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::089297561553:role/service`

### Reproduction Steps

Create a user in the master account, and create a policy with the following:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ChildAwsAccount",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::<ChildAWSAccountId>:role/service"
        },
    ]
}
```

In the child AWS account, I have a role called service, with the following trust relationship:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<MasterAWSAccountId>:root"
            },
            "Action": [
                "sts:AssumeRole",
                "sts:TagSession"
            ],
            "Condition": {}
        }
    ]
}
```

Run the following commands as per my CI/CD:
My deployment script then has this as the initial step to setup the credentials:
```
aws configure set role_arn $AWS_ASSUMED_ROLE_ARN --profile service
aws configure set source_profile mainProfile --profile service 
ASSUMED_ROLE=$(aws sts assume-role --role-arn $AWS_ASSUMED_ROLE_ARN --role-session-name service --profile service -- output json)
export AWS_ACCESS_KEY_ID=$(echo $ASSUMED_ROLE | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo $ASSUMED_ROLE | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo $ASSUMED_ROLE | jq -r .Credentials.SessionToken)
```

AWS_ASSUMED_ROLE_ARN = The ARN of the service role in the child AWS account.

### Additional Information/Context

I have no idea what so ever what `/botocore-session-1664316680` is all about, I've never seen that before.

This is a big problem because I have several pipelines running these commands and they've all worked perfectly fine until now.

### CLI version used

2.43.1 (build c1ebb85)

### Environment details (OS name and version, etc.)

Linux / Windows

**Comment by aBurmeseDev** [comment] 2022-09-29 22:34
Hi @owenashurst, thanks for reaching out and sorry to hear you're having trouble.

Generally, these AssumeRole type of errors are caused by missing permissions and roles as mentioned [in the troubleshoot guide](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-error/). However, it looks to me that you have trust policy to grant permission to assume roles. 

In the policy for master account, could you try with `*` as Resource (for testing purpose) and see if it changes anything?
```
"Resource": "*"
```

I also found [this stackOverflow post](https://stackoverflow.com/questions/69801102/why-is-botocore-session-id-being-attached-to-my-amazon-resource-number-arn) with similar issue you're having. Unfortunately, it doesn't seem the issue was resolved for them.

[This guide](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-error/) would be the best place to start to verify some of the policy and account roles that you have set up. 

If you're still having issues, please share your debug logs by adding `--debug` in your command. 

Best,
John

**Comment by owenashurst** [comment] 2022-10-05 22:41
Hi John,

Thank you very much. After some playing around in my local AWS-CLI, I managed to resolve it by specifying the source profile. I'm not sure if something has changed, but my previous repo's seem to be working the same, and now my new one works too.

So, instead of `--profile service` in my assume command, I simply used `--profile mainProfile`.

For anyone else using CircleCI, here is my full build step:

```
- aws-cli/setup:
          profile-name: mainProfile
      - run:
          name: Manual AWS config
          command: |
            aws configure set role_arn $AWS_ASSUMED_ROLE_ARN --profile service
            aws configure set source_profile mainProfile --profile service
            ASSUMED_ROLE=$(aws sts assume-role --role-arn $AWS_ASSUMED_ROLE_ARN --role-session-name service --profile mainProfile --output json)
            export AWS_ACCESS_KEY_ID=$(echo $ASSUMED_ROLE | jq -r .Credentials.AccessKeyId)
            export AWS_SECRET_ACCESS_KEY=$(echo $ASSUMED_ROLE | jq -r .Credentials.SecretAccessKey)
            export AWS_SESSION_TOKEN=$(echo $ASSUMED_ROLE | jq -r .Credentials.SessionToken)
```

Thanks for the support,
Owen

**Comment by aBurmeseDev** [comment] 2022-10-06 20:23
Glad to hear that it's working for you now and thank you for sharing your build steps as well! I'm going to close this issue now and if you have any other questions, please feel free to contact us again!

Best,
John

**Closed by aBurmeseDev** 2022-10-06 20:23 UTC
Labels: bug, assume-role, response-requested, iam

**Comment by omerfarukabaci** [comment] 2024-03-12 17:02
I think the problem here is that IAM roles are no longer implicitly trust themself. For anyone having the same problem like me, you may read the following blog post.

https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
