### ISSUE TITLE
Ability to open AWS console in web browser from aws-cli, using cli credentials

### ISSUE THREAD

**Issue by ottokruse** [aws/aws-cli#5885] opened 2021-01-21 09:21 UTC
This gist shows how easy it is to do this: https://gist.github.com/ottokruse/1c0f79d51cdaf82a3885f9b532df1ce5

```shell
aws-console --profile myprofile
# :tada: Your browser opens and you are signed in into the AWS console
```

Add to AWS ClI?

Edit: and please include an option to echo the signed URL to `stdout` so users can paste it into a browser tab of their choice (e.g. one for a different AWS account, in a multi-account container)

**Comment by kdaily** [comment] 2021-01-22 19:38
Thanks! Marking as a feature request. We currently have the ability already to open a browser for SSO login in the AWS CLI v2.

**Comment by strannik19** [comment] 2021-01-25 14:38
would be really great to have the ability to customize which browser (or just which cmd to use) for each profile. especially important when working with multiple environments.

**Comment by arjitj2** [comment] 2022-03-03 19:53
@kdaily I'm unable to find this, how do you open the browser for SSO login?

**Comment by aviflat** [comment] 2022-03-30 23:29
[aws-vault](https://github.com/99designs/aws-vault) has this feature and I use it regularly. Now that I’m switching to SSO I probably won’t be using `aws-vault` much going forward, so I’d love to see this added to `aws`.

**Comment by seanogor** [comment] 2022-04-11 13:24
@strannik19 this script above with https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ should get you there

**Comment by benkehoe** [comment] 2022-05-13 23:27
I believe this is a duplicate of #4642.

**Comment by mblakesley** [comment] 2022-09-13 23:34
> Thanks! Marking as a feature request. We currently have the ability already to open a browser for SSO login in the AWS CLI v2.

Are you stating the obvious here or actually giving useful info? Yes, `aws sso login` "opens a browser" but only in the narrowest sense possible. That flow doesn't log users into the Web Console, and if they go to the Web Console URL, it will say they're not logged in. Or am I missing something?

**Comment by tim-finnigan** [comment] 2022-09-14 17:38
As mentioned earlier this appears to be a duplicate of https://github.com/aws/aws-cli/issues/4642 so I'm resolving this issue. There are a few tools/workarounds mentioned there for those who are interested.

**Closed by tim-finnigan** 2022-09-14 17:38 UTC
Labels: feature-request
