### ISSUE TITLE
Content-Type not correctly stored for tar.gz files when uploading with CLI vs Console

### ISSUE THREAD

**Issue by alanwill** [aws/aws-cli#5228] opened 2020-05-22 00:50 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`Content-Type` isn't accurately applied when copying `tar.gz` files to S3 using the CLI. Works as expected from the Console

**Platform/OS/Hardware/Device**
Reproduced on both Linux and macOS
aws-cli/2.0.10 Python/3.8.2 Darwin/19.4.0 botocore/2.0.0dev14

**To Reproduce (observed behavior)**
`aws s3 cp somefile.tar.gz s3://mybucket`

**Expected behavior**
I'd expect the Content-Type to be `application/x-gzip` but instead it's `application/x-tar`

**Comment by KaibaLopez** [comment] 2020-05-27 18:07
Hi @alanwill ,
Thanks for pointing this out, I'll mark this as a bug since it is inconsistent behavior. On the mean time though and just in case this is blocking you in some way, you can manually set the content-type on you aws s3 cp call:
`aws s3 cp <LocalPath> <s3Uri> --content-type <string>`

**Comment by alanwill** [comment] 2020-05-27 18:28
Thanks @KaibaLopez yes that's what I've been doing as a workaround.

**Comment by Slapy06** [comment] 2021-12-16 10:53
Hello,
I'm going to use the workaround too (aws s3 cp <LocalPath> <s3Uri> --content-type <string>) but a date with a bug fix would be appreciated :-)

**Comment by kdaily** [comment] 2021-12-16 18:15
Hi @alanwill,

I'm reviewing this issue. This is the behavior of the Python standard library `mimetypes`, which is used to guess the type and encoding. I confirmed that this is the case on Mac and Linux. I don't think we would make a change to this specific content type as this would not be backwards compatible.

There is another older issue regarding how to account for custom mimetypes (https://github.com/aws/aws-cli/issues/1249) with more history, but no clear implementation decision. I'm going to close this and link it there, and mark the other issue for further review.

**Closed by kdaily** 2021-12-16 18:15 UTC
Labels: bug
