### ISSUE TITLE
`asw ecr get-login` includes deprecated Docker flag

### ISSUE THREAD

**Issue by drewandersen** [aws/aws-cli#2743] opened 2017-08-01 17:45 UTC
Execute `aws ecr get-login --region=us-west-2` and receive the following error:

```
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
```
The email flag was removed in release 17.06.0-ce: https://github.com/docker/cli/pull/143

**Comment by joguSD** [comment] 2017-08-01 20:12
You can remove that by specifying the `--no-include-email` flag. We default to including the email so we don't break customers still relying on it.

Duplicate of #2732, #2694, #2691, #2676, and a few others

**Closed by joguSD** 2017-08-01 20:12 UTC
Labels: duplicate
