### ISSUE TITLE
SQS fails to send in private network with custom endpoint

### ISSUE THREAD

**Issue by mwisnicki** [aws/aws-cli#5966] opened 2021-02-22 03:21 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
`aws sqs send-message` does not work in private network with sqs endpoint.

**SDK version number**
aws-cli/1.18.147 Python/2.7.18 Linux/4.14.214-160.339.amzn2.x86_64 botocore/1.18.6

**Platform/OS/Hardware/Device**
EC2 Ami Linux 2

**To Reproduce (observed behavior)**
1. Create VPC without internet access
2. Add SQS endpoint with private DNS names enabled
3. Invoke
```
aws sqs send-message --queue-url "https://sqs.us-east-1.amazonaws.com/${ACCOUNT_ID}/${QUEUE}" --message-body="test
```
4. Wait forever until it times out connecting to https://queue.amazonaws.com/

**Expected behavior**
Message is sent. Similar setup works for SNS.

**Logs/output**
```
2021-02-22 03:20:31,710 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): queue.amazonaws.com:443
```

**Additional context**
Works correctly with `--endpoint-url` but I would like to avoid it. That's the whole point of Private DNS names on endpoint, isn't it?

**Comment by mwisnicki** [comment] 2021-02-22 03:22
STS has similar problem but has a workaround in a form of `export AWS_STS_REGIONAL_ENDPOINTS=regional` but I couldn't find anything similar for SQS

**Comment by stobrien89** [comment] 2021-02-23 03:33
Hi @mwisnicki, 

Thanks for writing in!  From what I've seen so far, it looks you must specify an `endpoint-url` to make sqs calls, but I'm going to look into this further, as a few things seem unclear.

**Comment by stobrien89** [comment] 2021-02-23 23:53
Hi @mwisnicki,

Thanks for your patience.  I've confirmed that an `endpoint-url` must be specified in this scenario for all services other than STS.  We actually have an [open feature request](https://github.com/aws/aws-cli/issues/1270) related to this, which does provide some options for workarounds.

**Comment by mwisnicki** [comment] 2021-03-04 18:11
> Hi @mwisnicki,
> 
> Thanks for your patience. I've confirmed that an `endpoint-url` must be specified in this scenario for all services other than STS. We actually have an [open feature request](https://github.com/aws/aws-cli/issues/1270) related to this, which does provide some options for workarounds.

@stobrien89  Doesn't that go against the idea of Private DNS names in endpoints. Per [documentation](https://docs.aws.amazon.com/vpc/latest/privatelink/verify-domains.html):

> the service provider can configure a private DNS name so consumers can access the service using an existing DNS name without making changes to their applications

This is clearly not working with SDK/CLI

**Comment by stobrien89** [comment] 2021-03-04 19:38
Hi @mwisnicki,

I definitely see what you're saying, which is why we're considering implementing a per-service configuration of `endpoint-url`, but the SDKs/CLI as clients do not currently have a way of automatically determining which endpoints to make calls to in private networks (aside from the STS implementation we've discussed).  

Another possible workaround for the time being would be configuring an alias similar to something like this: 

`alias awssqs='aws sqs --endpoint-url <endpoint url>'`

Hope this helps!

**Comment by mwisnicki** [comment] 2021-03-04 22:39
How come? The endpoints are standardized per region so at most you should require configuration of region and on AWS that can be obtained from instance metadata unless I'm missing something.

**Comment by stobrien89** [comment] 2021-03-05 20:31
Hi @mwisnicki,

After taking a second look at the [documentation](https://docs.aws.amazon.com/vpc/latest/privatelink/vpce-interface.html#vpce-private-dns): 

> The hosted zone contains a record set for the default DNS name for the service (for example, ec2.us-east-1.amazonaws.com) that resolves to the private IP addresses of the endpoint network interfaces in your VPC.

I apologize for any confusion, but I've misidentified the issue here.  That being said, it looks like there are some issues with resolving the private IP addresses (with SQS and a few other services) that I'm going to look into.  I was able to find another [issue](https://github.com/aws/aws-sdk-net/issues/1225) related to this, so my guess would be that the record set was potentially not updated for these services, as one user reported it was working when using a legacy endpoint.  

I'm going to re-open this and take a further look— I should hopefully have more information by the middle of next week!

**Comment by stobrien89** [comment] 2021-03-09 19:49
Hi again @mwisnicki,

I appreciate your patience throughout all of our back-and-forth.  One question I realized I should have asked you earlier was, when specifying the `--endpoint-url`, were you providing the url to the VPC endpoint itself,  or the service endpoint (i.e. `https://sqs.us-east-1.amazonaws.com`) ?

**Comment by mwisnicki** [comment] 2021-03-15 18:55
It works when I provide default regional endpoint url (`https://sqs.us-east-1.amazonaws.com/`)

**Comment by stobrien89** [comment] 2021-03-16 00:19
Hi @mwisnicki, 

After doing some digging, it looks like the problem here is that the CLI v1 still uses the legacy endpoint (for example, `https://us-west-2.queue.amazonaws.com/`).  If there's any way you can upgrade your CLI version on your instance (S3 bucket perhaps) to V2, you shouldn't have to specify the `--endpoint-url`, as V2 has the updated endpoints. 

 I was able to test this with a few other services last week (namely Cloudformation and EC2) and verified that no `--endpoint-url` needs to be provided when api calls are being made to the correct default service endpoint.  Hope this helps!

**Comment by mwisnicki** [comment] 2021-03-16 02:47
I was using what came preinstalled with latest Amazon Linux AMI at the time. Don't need to fix it anymore but good to know I can expect it to work out of the box in the future.

**Closed** 2021-03-16 02:48 UTC
Labels: guidance, investigating, sqs

**Comment by stobrien89** [comment] 2021-03-16 17:51
Hi @mwisnicki, 

I believe the pre-installed version for Amazon Linux AMI is 1.14, which is definitely a bit older, but I'm glad you were able to find a solution.  Sorry it took me so long to get this one figured out!
