### ISSUE TITLE
aws-cli/1.19.112 crash when moving files to s3 bucket.

### ISSUE THREAD

**Issue by peycho** [aws/aws-cli#6625] opened 2021-12-23 12:02 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x ] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
We have a simple bash script that uses awscli to upload gzipped files from Linux machine ebs disk to s3 bucket location using the following example command:

```
timeout 20 /usr/local/bin/aws s3 mv /mnt/path/local-data s3://bucket-name/path/something --recursive --region=us-east-1
```
The files are pretty small, nothing above 1 MB.
The timeout command is in case the request get stuck for some reason(it happens sometimes), to exit the command and start the loop again.

However, in some cases we see awscli crashes for some reason when executing the command above. The issue is not frequent, but it happens more often on our more loaded servers.

Here is what I was able to extract from one of the core files. I can provide the core file itself if that's necessary.
https://gist.github.com/peycho/2676ee07d1e68780fbc1fe9131614e49

**SDK version number**
The awscli is installed via pip
```
aws-cli/1.19.112 Python/2.7.17 Linux/5.3.0-1035-aws botocore/1.20.112
```

**Platform/OS/Hardware/Device**
```
Ubuntu 18.04 server / aws ec2 instance c5.2xlarge (8 cores / 16 Gb ram)
Linux 5.3.0-1035-aws #37-Ubuntu SMP Sun Sep 6 01:17:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**To Reproduce (observed behavior)**
I can't provide steps because the command is pretty simple and it happens only sometimes. Daily, we upload a lot of files in s3 using that method. Probably millions.

**Expected behavior**
Not to crash.

**Logs/output**
N/A

**Additional context**
N/A

**Comment by stobrien89** [comment] 2021-12-23 23:36
Hi @peycho,

Sorry to hear about the issues.  This will be difficult to troubleshoot without a consistently reproduce-able example, but I'll see if I'm able to review with the team to get their thoughts.  In the meantime, would it be possible for you to get an exit code on the next occurence? Thanks!

**Comment by peycho** [comment] 2021-12-29 06:58
Hi @stobrien89
I check the exit code of the command and it is: 139

**Comment by peycho** [comment] 2021-12-31 06:48
I will migrate awscli installation with python3.6 and see if this crash still occur. We suspect that this is something related to python2 libraries.

**Comment by amerixan** [comment] 2021-12-31 10:46
Looking at the debug logs, it definitely looks like a Python 2 issue.  Looking
at the [awscli PyPi](https://pypi.org/project/awscli/) repository, it doesn't look
like Python 2 is even supported.

**Comment by peycho** [comment] 2021-12-31 11:55
Hi @amerixan

The reported version does support Python2. https://pypi.org/project/awscli/1.19.112/
After that support for python2 is dropped.
I'll leave my test work with python3.6 for several days, if that fix my problem I'll report back that the problem is solved.

Thanks.

**Comment by peycho** [comment] 2022-01-04 06:47
Hi.

Unfortunately the python3 crashes as well.
aws-cli/1.22.26 Python/3.6.9 Linux/5.3.0-1035-aws botocore/1.23.26

Here is additional gdb output. https://gist.github.com/peycho/39b9cfda34697b24422bfcb4396baa1a

Let me know how I can assist with resolving this problem.
Thanks.

**Comment by stobrien89** [comment] 2022-01-04 20:02
Hi @peycho,

My apologies for the delay.  We reviewed this as a team today and think this may be an issue with openssl— Would you be able to share the version of openssl you're running on the ec2 instance?  Thanks!

**Comment by peycho** [comment] 2022-01-05 06:05
Hi.

Here is what I see with dpkg:
```
sudo dpkg -l | grep openssl
ii  libxmlsec1-openssl:amd64          1.2.25-1build1                      amd64        Openssl engine for the XML security library
ii  openssl                           1.1.1-1ubuntu2.1~18.04.14           amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64       3build1                             amd64        version compatibility baseline for Perl OpenSSL packages
ii  python3-openssl                   17.5.0-1ubuntu1                     all          Python 3 wrapper around the OpenSSL library

```
Thanks.

**Comment by stobrien89** [comment] 2022-01-08 02:33
Hi @peycho,

Thanks for the confirmation.  I thought initially that this may have been related to https://github.com/openssl/openssl/issues/2260, but that doesn't appear to be the case.  

I know you mentioned this was happening intermittently with 2.7— is it occurring any more or less frequently with 3.6?  It also came up that this could be a Python bug, but I haven't found anything that matches this situation exactly.

**Comment by peycho** [comment] 2022-01-10 05:49
Hi. @stobrien89 
I can't really say where the event occur more often because our production uses python2.7 and I have upgraded only my test server with python3.6.

It is not really frequent (~once per day) but when you have 200+ instances with this issue it becomes a problem.

**Comment by peycho** [comment] 2022-01-17 06:47
Hi.

I removed the timeout command and added `--cli-read-timeout 20 --cli-connect-timeout 20` as replacement just to check if the problem is from the timeout command.

However the awscli is still crashing.
```
aws-cli/1.22.26 Python/3.6.9 Linux/5.4.0-1030-aws botocore/1.23.26
```

**Comment by kdaily** [comment] 2022-01-20 00:26
Hi @peycho,

Thanks for the information. I'm not sure what the issue could be. I'm reviewing to see if there are any Python or OpenSSL bug reports, but I haven't found anything else yet. I understand the difficulty in capturing them, but having debug logs to see what the CLI is doing would be helpful here.

Are you using a public Ubuntu Linux AMI, or have an AMI that you can somehow share with us to try and reproduce the environment?

**Comment by peycho** [comment] 2022-01-20 06:24
Hi.

The AMI is the standard Ubuntu 18.04 Linux. The servers are bootstrapped by user_data.

Here is debug output of awscli just before one of the crashes: https://gist.github.com/peycho/3b949a1630698d43933bc527b267aded

**Comment by kdaily** [comment] 2022-04-13 19:21
Hi @peycho,

I've not been able to reproduce this issue on the Ubuntu 18.04 AMI. I'm going to mark it as a bug but keep `needs-reproduction` on it to see if anyone else comes across this and we can identify something in common.

I know you've confirmed that this occurs with Python 3.6 as well as Python 2, but it might be worth upgrading to a more recent version of Python as well, if possible. I tried it with Python 3.6, 3.7, and 3.8 and could not get this to occur.

**Comment by peycho** [comment] 2022-04-14 05:39
We moved to awscli v2 and the issue was resolved.

**Comment by tim-finnigan** [comment] 2022-11-09 22:55
Since this issue was resolved by upgrading and the team couldn't reproduce the issue I'm going to close this. If anyone would like to revisit this please let us know here or consider creating a new issue.

**Closed by tim-finnigan** 2022-11-09 22:55 UTC
Labels: bug, s3, needs-reproduction
