### ISSUE TITLE
--tag-specifications option seems to be a new option, but cannot find it in the changelog

### ISSUE THREAD

**Issue by batmat** [aws/aws-cli#2977] opened 2017-11-22 09:20 UTC
Hello!

I spent a bit of time trying to understand why my previously working command was failing:

```
$ aws ec2 run-instances \
          --image-id  ami-524eab28 \
          --count 1 \
          --instance-type r4.large \
          --key-name the-key \
          ...
          --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=windows-agent}]' \
          --block-device-mapping '[ { "DeviceName": "/dev/sda1", "Ebs": { "VolumeSize": 100 } } ]'
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: --tag-specifications, ResourceType=instance,Tags=[{Key=Name,Value=windos-agent}]
```

Apparently, this works on `aws-cli/1.12.0 Python/2.7.14 Linux/4.13.12-200.fc26.x86_64 botocore/1.8.0` but does not aws cli 1.12, but does not on some older version (sorry, unfortunately don't have that data anymore since I twiddled in the meantime and didn't store it :-().

Anyway, no big deal because I'm now up and running, but could you please update the changelog so that one finds when it was introduced?

Grepping https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst for "tag-specifications" does not yield anything.

Thank you!

**Comment by batmat** [comment] 2017-11-22 09:48
I'm not sure since I removed it, but seems like the version that was not knowing this was `1.10.38`.

**Comment by joguSD** [comment] 2017-11-22 23:03
Sorry you had some trouble with this. This is more of a systemic issue than a failure to update the changelog to include that this parameter was added. The issue is that (in general) the operations and parameters exposed via the CLI are generated automatically based on a model of the service's API. Whenever these models change, so do the available commands and arguments in the CLI. What we would need is something to translate these changes in the model file to a changelog of how it impacts the exposed interface and behavior of the CLI, which is a pretty hefty task.

Marking as a documentation enhancement.

**Comment by kdaily** [comment] 2021-02-08 18:29
This would be very useful! I've opened a tracking issue at #5926 as this one is kind of buried. Linking for context and closing.

**Closed by kdaily** 2021-02-08 18:29 UTC
Labels: documentation, enhancement

**Comment by kdaily** [comment] 2021-04-21 18:52
As of version `1.19.27`, there are more details on changes in the changelog entries:

https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#11927

_Originally posted by @kdaily in https://github.com/aws/aws-cli/issues/5926#issuecomment-824282410_
