### ISSUE TITLE
ecr get-login makes travis builds hang

### ISSUE THREAD

**Issue by MatTheCat** [aws/aws-cli#3256] opened 2018-04-11 09:37 UTC
Now that Docker 18.04 is available on Travis a prompt is required to login, which makes builds hang.

```
docker login -u AWS -p password repository
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Are you sure you want to proceed? [y/N] 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by pierrre** [comment] 2018-04-11 09:40
Probably caused by https://github.com/docker/docker-ce/commit/72976c8bb61ea6c06491cf912e79cf433b2299f1

**Comment by stealthycoin** [comment] 2018-04-11 20:54
Maybe i'm not understanding, that looks like the docker command is hanging, what does this have to do with the AWS CLI? You can just echo `y` into it if you want to answer that first question as yes. Though if it changes you may be answering yes to something you don't mean to.

**Comment by MatTheCat** [comment] 2018-04-12 05:25
The AWS CLI is triggering that behavior by using the `password` option.

Indeed this can be solved by piping `yes` to `aws ecr get-login` but if you still plan of keeping things this way this should be documented.

**Comment by RO-29** [comment] 2018-04-12 13:12
Do you guys accept PR's? 

this needs to be changed here https://github.com/aws/aws-cli/blob/58ee1ee50ff2c9f2585571803ca8fa2e96138333/awscli/customizations/ecr.py#L79

**Comment by MatTheCat** [comment] 2018-04-12 22:09
Woops my phone likes to unlock itself in my pocket.

**Comment by mythz** [comment] 2018-04-14 02:40
Please change this tool to use Docker's recommended password input strategy so it doesn't cause existing deployment scripts to hang. 

It's currently breaking all my AWS CLI deployment scripts which I prefer not to have to individually update.

**Comment by mythz** [comment] 2018-04-19 00:10
Can we get this expedited please? My AWS deploy scripts on Travis CI are still breaking, I'd very much like to avoid changing my (many) deploy scripts in order to be able to deploy again, and then having to go through and change everything back when this ultimately gets resolved.

**Comment by MatTheCat** [comment] 2018-04-27 22:02
@stealthycoin is there an intent to do anything?

**Comment by mythz** [comment] 2018-04-28 03:06
Agreed, this wait is annoying for a such a critical tool that's breaking existing builds of paying AWS Customers. 

Either resolve the issue by adopting Dockers recommended strategy, or close the issue with the reason for why you wont. At least blocked Customers will know that we need to manually update all the build scripts of our deployed systems and that it's going to be a wasted effort when you eventually decide to resolve the issue.

**Comment by justnance** [comment] 2018-10-04 23:27
@mythz and @MatTheCat - Thank you for your feedback and patience.  I am labeling this as a feature request pending further investigation.

**Comment by rpnguyen** [comment] 2020-02-27 05:54
`ecr get-login` is now deprecated, please see aws/containers-roadmap#735 for guidance on using the new command [`ecr get-login-password`](https://docs.aws.amazon.com/cli/latest/reference/ecr/get-login-password.html) which will enable the usage of the recommended `--pasword-stdin` flag for docker login

**Comment by MatTheCat** [comment] 2020-02-27 08:26
I guess this issue can be closed then?

**Comment by stealthycoin** [comment] 2020-02-27 22:43
Thanks @rpnguyen  closing.

**Closed by stealthycoin** 2020-02-27 22:43 UTC
Labels: feature-request
