### ISSUE TITLE
AWS_ROLE_SESSION_NAME doesn't set role_session_name

### ISSUE THREAD

**Issue by mjuarez** [aws/aws-cli#4878] opened 2020-01-25 01:24 UTC
## Problem
The aws-cli does not seem to respond to the `AWS_ROLE_SESSION_NAME` environment variable. When using a profile configured to use role assumption, the `AWS_ROLE_SESSION_NAME` environment variable does not override role_session_name. If role_session_name is not specified, `AWS_ROLE_SESSION_NAME` does not override either.

Per the [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)
>AWS_ROLE_SESSION_NAME
>Specifies a name to associate with the role session. This value appears in CloudTrail logs for commands performed by the user of this profile.
>
>If defined, this environment variable overrides the value for the profile setting role_session_name. You can't specify a role session name as a command line parameter.

## Example
With `role_session_name` set for profile
```
# from ~/.aws/credentials
[test1]
region         = us-east-1
role_arn       = arn:aws:iam::<sanitized>:role/TestRole
role_session_name = apple
source_profile = default
```
```
$ AWS_ROLE_SESSION_NAME=banana aws sts get-caller-identity --profile test1
{
    "Account": "<sanitized>", 
    "UserId": "<sanitized>:apple", 
    "Arn": "arn:aws:sts::<sanitized>:assumed-role/TestRole/apple"
}
```

Without `role_session_name` set for profile
```
# from ~/.aws/credentials
[test2]
region         = us-east-1
role_arn       = arn:aws:iam::<sanitized>:role/TestRole
source_profile = default
```
```
$ AWS_ROLE_SESSION_NAME=banana aws sts get-caller-identity --profile test2
{
    "Account": "<sanitized>", 
    "UserId": "<sanitized>:botocore-session-1579914611", 
    "Arn": "arn:aws:sts::<sanitized>:assumed-role/TestRole/botocore-session-1579914611"
}
```

## Desired Functionality
`AWS_ROLE_SESSION_NAME` environment variable will set the name of the session for the assumed role profile.

## Environment
```
$ aws --version
aws-cli/1.17.9 Python/2.7.17 Linux/5.3.7-050307-generic botocore/1.14.9
```

**Comment by klaytaybai** [comment] 2020-01-28 21:09
Thanks for alerting us to this.

**Comment by reegnz** [comment] 2020-04-21 12:55
What's the ETA for this feature?
Do you need help with this?

**Comment by reegnz** [comment] 2020-04-21 12:57
I checked the go SDK, it's a bit more advanced than botocore in this regard: https://github.com/aws/aws-sdk-go/blob/9c9db07028aeb7d607e54b2b5aa97bbbbebcbbfd/aws/session/env_config.go#L255

**Comment by Eymerich-mr** [comment] 2020-04-28 09:49
Still happening in:
```
$ aws --version
aws-cli/1.18.47 Python/2.7.16 Linux/4.14.173-137.229.amzn2.x86_64 botocore/1.15.47
```

**Comment by reegnz** [comment] 2020-05-18 10:57
I would like to enforce role session names as described in a recent announcement: https://aws.amazon.com/about-aws/whats-new/2020/04/now-easily-identify-the-identity-responsible-for-the-actions-performed-using-iam-roles/

It would be much easier if a user could set their username as an environment variable, instead of having to put it into each and every profile in the `~/.aws/config` file.

**Comment by reegnz** [comment] 2020-05-18 11:16
My current workaround for the issue is to set my username for every profile like this:
```sh
<~/.aws/config awk -F'[][ ]' '/\[profile/{print $3}' \
| xargs -t -n 1 -I{} aws configure --profile {} set role_session_name $USER
```
But then this is not really a portable way of doing things...

**Comment by joaopenteado** [comment] 2021-04-09 20:44
No ETA or updates for this one yet? It's been more than a year!

**Comment by kdaily** [comment] 2021-04-09 22:03
@reegnz's comment is correct:

> However this seems intentional for now (probably introduced with WEB_IDENTITY_TOKEN_FILE):
> https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-oidc
>
> >    These environment variables currently apply only to the assume role with web identity provider. They don't apply to the general assume role provider configuration.

I'm checking to see why this is the case. Since this is known and currently intentional, marking as a feature request. Just as a note, this functionality was moved to `botocore`. Leaving the issue here for easier tracking and updates.

**Comment by mjuarez** [comment] 2021-04-09 22:12
I'm fine if you want to make this into a feature request, but I would like to at least ask that a bug be filed for discrepancies in the docs I linked to. The reference @reegnz provided is only in the "[Assume role with web identity](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html#cli-configure-role-oidc)" docs. When I was originally implementing this, I was use reading the "[Environment Variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)". There should be a clear caveat that this only applies to web identity.

**Comment by kdaily** [comment] 2021-08-16 22:24
Hi @mjuarez,

Thanks for calling that out - I apologize if converting to a feature request seemed like downgrading, but it was not my intent!

There has been a note added to the [environment variables documentation page](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) that reads the same:

> Note
> This environment variable only applies to an assumed role with web identity provider it does not apply to the general assume role provider configuration.

**Closed** 2021-08-16 22:24 UTC
Labels: feature-request, assume-role, configuration

**Comment by akloss-cibo** [comment] 2023-05-18 19:28
FWIW, if this was there when I was working with this, it escaped my notice and I ended up here.
 
> Note
> This environment variable only applies to an assumed role with web identity provider it does not apply to the general assume role provider configuration.

**Comment by yermulnik** [comment] 2024-09-03 12:18
Is there an option to inherit `role_session_name` from the profile specified by `source_profile`?
