### ISSUE TITLE
Errors performing "aws emr create-cluster" after upgrading from 1.6.x to 1.7.16 (or 1.7.17)

### ISSUE THREAD

**Issue by erond** [aws/aws-cli#1251] opened 2015-03-27 10:24 UTC
**Scenario**:

aws-cli version: ```aws-cli/1.7.17 Python/2.7.6 Linux/3.13.0-48-generic```

I have a Ruby script that I use to:

1. in order to get temporary credentials, call:

 ```
aws sts assume-role --profile test-account-user --role-arn arn:aws:iam::123456789012:role/deploy-on-prod --role-session-name deploy-myapp-on-prod
```

2. use such temporary credentials (exporting as env vars) to call:

 ```
aws emr create-cluster ... [cluster description]
```

**Problem**:

Whereas this command always worked with 1.6.x AWS CLI versions, now that I updated to the latest available I get:

```
You must specify a region. You can also configure your region by running "aws configure".
```

The region is set in ~/.aws/config for the user invoking the ```assumeRole```, but I don't specify any profiles (hence regions) when calling the ```aws emr create-cluster ...```, since I just ```export``` the obtained credentials as environment variables.

**Final notes**:

- the very same commands works fine on these 2 different workstations with:

 ```
aws-cli/1.6.9 Python/2.7.6 Darwin/14.1.0
aws-cli/1.6.5 Python/2.7.3 Linux/3.2.0-4-686-pae
```

 Plus, with the above aws-cli versions, the ```aws emr create-cluster ...``` command used to work also when, **by mistake**, I invoked it keeping ```--profile test-account-user```: it seemed the the previous aws-cli versions were able to give the priority to the AWS credentials set up as environment variables, whereas the latest aws-cli gives the priority to an eventually specified --profile . I was able to test this behaviour since, if I invoke ```aws emr create-cluster --profile test-account-user ...``` with the latest aws-cli after exporting the temporary credentials I get:

 ```
A client error (AccessDeniedException) occurred when calling the RunJobFlow operation: User: arn:aws:iam::123123123123:user/test-account-user is not authorized to perform: elasticmapreduce:RunJobFlow
```

 that is reasonable, since "test-account-user" by itself (read: without assuming the _deploy-myapp-on-prod_ role) doesn't have the permissions to perform a ```RunJobFlow```.

**Comment by erond** [comment] 2015-03-27 15:08
The issue still occurs with:

```
aws-cli/1.7.18 Python/2.7.6 Linux/3.13.0-48-generic
```

**Comment by erond** [comment] 2015-03-27 15:42
The issue still occurs if I add the ```--region us-east-1``` in the ```aws sts assume-role ... ``` command

**Comment by mtdowling** [comment] 2015-11-19 23:10
I tried to reproduce this by removing my ~/.aws/credentials file and by just using `--region <region-name>` along with exporting `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`. Not being able to find a `--region` when no profile is set and no AWS_REGION environment variable can be found makes sense because the CLI needs to know which region to connect to.

> The issue still occurs if I add the --region us-east-1 in the aws sts assume-role ... command

Specifying a --region when assuming a role to create credentials would not influence later requests that use those credentials. You'd still need to either export AWS_REGION or provide a `--region` option per/request.

> it seemed the the previous aws-cli versions were able to give the priority to the AWS credentials set up as environment variables, whereas the latest aws-cli gives the priority to an eventually specified --profile 

`--profile` overriding environment variables was a long standing feature request -- makes sense really because having an environment variable take precedence over an option a user provides doesn't make sense because you wouldn't be able to ever change the value. You can find the related discussion and resolution here: https://github.com/aws/aws-cli/issues/113

I'll go ahead and close this issue. Let me know if you are still having issues after proving `--region` or exporting `AWS_REGION`.

**Closed by mtdowling** 2015-11-19 23:10 UTC
Labels: bug
