### ISSUE TITLE
"Member must satisfy regular expression pattern: [^!#/\s]+" in codeartifact list-package-versions for scoped packages

### ISSUE THREAD

**Issue by chbiel** [aws/aws-cli#5633] opened 2020-10-13 06:58 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I have a package created in code artifact with the naming (like) "@scope/package"
When using `aws codeartifact list-package-versions --domain somedomain --repository somerepo--package "@scope/package" --format npm` I get the error `Member must satisfy regular expression pattern: [^!#/\s]+` for the package argument.

As per the official npm documentation scoped packages are part of the standard: https://docs.npmjs.com/using-npm/scope.html and the names will contain at least `/`. So that error should not occure.

**SDK version number**
1.18.157

**Platform/OS/Hardware/Device**
Linux

**To Reproduce (observed behavior)**
1. Create a repo in code artifact, name it "@scope/package"
2. Try to list it's versions via CLI

**Expected behavior**
That no error occures and the versions are listed correctly.

**Comment by kdaily** [comment] 2020-10-13 16:29
Hi @chbiel ,

Thanks for reporting. I think this is a duplicate of #5501.

**Comment by chbiel** [comment] 2020-10-14 12:33
yes its a duplicate of the above. thanks for the reference

**Closed** 2020-10-14 12:33 UTC
Labels: closing-soon, duplicate

**Comment by kdaily** [comment] 2021-04-29 16:04
@chbiel - reposting here to make sure you see it:

> Hi all, as @zobzn and @guoliang have noted, using the `--namespace` option is the current solution here. Here is the documentation page that describes this behavior:
> 
> https://docs.aws.amazon.com/codeartifact/latest/ug/list-packages.html#list-packages-npm
> 
> Thanks both of you for identifying this. I confirmed this with the CodeArtifact team as well. They are considering some enhancements to help this scenario, from automatically parsing the syntax with the namespace as part of the package name, or a better error message letting you know to use the `--namespace` argument. I don't have any information on when or if either of those things might be implemented.
> 
> _Originally posted by @kdaily in https://github.com/aws/aws-cli/issues/5501#issuecomment-829366025_
