### ISSUE TITLE
Release 1.19.80 errors on CentOS 7

### ISSUE THREAD

**Issue by andrew-glenn** [aws/aws-cli#6190] opened 2021-05-26 16:40 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

**SDK version number**

**Platform/OS/Hardware/Device**
CentOS 7

**To Reproduce (observed behavior)**
`pip install awscli` for v `1.19.80` doesn't work.

**Expected behavior**
It works.

## 1.19.80 errors out.

```
[root@ip-10-0-130-49 log]# pip install awscli==1.19.80
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting awscli==1.19.80
  Using cached awscli-1.19.80.tar.gz (1.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jR6k9F/awscli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jR6k9F/awscli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rKjlcQ
         cwd: /tmp/pip-install-jR6k9F/awscli/
    Complete output (3 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in awscli setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## 1.19.79 works.

```
[root@ip-10-0-130-49 log]# pip install awscli==1.19.79
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting awscli==1.19.79
  Using cached awscli-1.19.79-py2.py3-none-any.whl (3.6 MB)
Requirement already satisfied: colorama<0.4.4,>=0.2.5 in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (0.4.3)
Requirement already satisfied: rsa<=4.5.0,>=3.1.2; python_version == "2.7" in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (4.5)
Requirement already satisfied: s3transfer<0.5.0,>=0.4.0 in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (0.4.2)
Requirement already satisfied: PyYAML<5.5,>=3.10 in /usr/lib64/python2.7/site-packages (from awscli==1.19.79) (3.10)
Requirement already satisfied: botocore==1.20.79 in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (1.20.79)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (0.15.2)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python2.7/site-packages (from rsa<=4.5.0,>=3.1.2; python_version == "2.7"->awscli==1.19.79) (0.4.8)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.7" in /usr/lib/python2.7/site-packages (from s3transfer<0.5.0,>=0.4.0->awscli==1.19.79) (3.3.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/lib/python2.7/site-packages (from botocore==1.20.79->awscli==1.19.79) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/lib/python2.7/site-packages (from botocore==1.20.79->awscli==1.19.79) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/lib/python2.7/site-packages (from botocore==1.20.79->awscli==1.19.79) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.20.79->awscli==1.19.79) (1.9.0)
Installing collected packages: awscli
Successfully installed awscli-1.19.79
[root@ip-10-0-130-49 log]#
```

**Comment by nateprewitt** [comment] 2021-05-26 17:27
Hey @andrew-glenn,

Thanks for reaching out! This appears to be a duplicate of #6064, #6092, and #6094. The setup.py in the AWS CLI requires a semi-recent version of setuptools (within the last 7 years) but it appears you're using one that is from 2014 or earlier. We have the exact requirements documented [here](https://github.com/aws/aws-cli#installation).

Nothing around this setup changed between 1.19.79 and 1.19.80, it's been in place since 1.19.40. There are a couple of interesting pieces of information from your logs that point to the issue though.

The lines your version of setuptools is unhappy with are [here](https://github.com/aws/aws-cli/blob/develop/setup.py#L32-L33). This chooses different requirements for rsa depending on the version of Python you're using. We know this worked on your system at one point, because the cached installation of awscli==1.19.79 has this line:

```
Requirement already satisfied: rsa<=4.5.0,>=3.1.2; python_version == "2.7" in /usr/lib/python2.7/site-packages (from awscli==1.19.79) (4.5)
```

So it was able to properly parse the installation requirements when you first installed 1.19.79. We'd recommend making sure your system is using setuptools>=36.2.0 to ensure things work consistently.

It may also be important to note we're ~6 weeks away from [end of support for Python 2.7](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-python-2-7-in-aws-sdk-for-python-and-aws-cli-v1/) in the CLI.

**Closed** 2021-05-26 23:06 UTC
Labels: duplicate, guidance, installation
