### ISSUE TITLE
Incorrect documentation for downloading RDS logs

### ISSUE THREAD

**Issue by cbandy** [aws/aws-cli#1835] opened 2016-03-07 17:07 UTC
Since #1617, the documentation indicates that the following command will download an entire RDS log file. However, it errors without downloading anything.

```
$ aws --version
aws-cli/1.10.8 Python/2.7.10 Darwin/15.3.0 botocore/1.3.28

$ aws rds download-db-log-file-portion --db-instance-identifier myinstance \
--starting-token 0 --log-file-name error/postgresql.log.2016-02-29-00 \
--output text

Bad starting token: 0
```

**Comment by rayluo** [comment] 2016-03-07 17:48
I haven't tried to reproduce this yet. But it sounds like relevant to our recent change to CLI pagination token. Perhaps @JordonPhillips can take a look.

**Comment by cbandy** [comment] 2016-03-07 18:32
I just found a workaround:

```
$ aws rds download-db-log-file-portion --db-instance-identifier myinstance \
--cli-input-json '{ "Marker": "0" }' --log-file-name error/postgresql.log.2016-02-29-00 \
--output text
```

**Comment by kyleknap** [comment] 2016-03-14 19:14
Yeah this is a regression due to pagination change. We are looking into how to handle these cases.

**Comment by gorandev** [comment] 2016-03-28 17:37
@cbandy Tried your workaround but it just spits 65M and the file ends with "[Your log message was truncated]"

**Comment by JordonPhillips** [comment] 2016-03-28 22:32
@gorandev @cbandy I just merged in a fix, it'll be available in the next release.

**Closed by JordonPhillips** 2016-03-28 22:32 UTC
Labels: bug

**Comment by JordonPhillips** [comment] 2016-03-28 22:33
In the meantime, using `--marker '0'` should do the trick.

**Comment by gorandev** [comment] 2016-03-28 23:35
@JordonPhillips The --marker '0' doesn't work, guess I'll have to wait for next release! :)
