### ISSUE TITLE
--profile option not prioritised when AWS_PROFILE is invalid profile name

### ISSUE THREAD

**Issue by LomaxOnTheRun** [aws/aws-cli#5333] opened 2020-07-02 07:04 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**

The `AWS_PROFILE` env var overrides the `--profile` option when `AWS_PROFILE` is set to a non-existent profile.

**SDK version number**

`aws-cli/2.0.25 Python/3.7.3 Linux/5.4.0-37-generic botocore/2.0.0dev29`

**Platform/OS/Hardware/Device**
What are you running the cli on?

Ubuntu 20.04 LTS laptop

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

1. Unset `AWS_PROFILE`
2. Run a command with `--profile` set (expected success)
3. Set `AWS_PROFILE` to a valid profile name
4. Run the command with `--profile` set to a valid value (expected success)
5. Set `AWS_PROFILE` to an invalid profile name
6. Run the command with `--profile` set to a valid value (unexpected failure)

**Expected behavior**

The `--profile` option should override the `AWS_PROFILE` env var, even if the env var points to a non-existent profile.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

```
$ unset AWS_PROFILE
$ aws configure list-profiles
default
user1
$ export AWS_PROFILE=user1
$ aws configure list-profiles --profile=default
default
user1
$ export AWS_PROFILE=user2
$ aws configure list-profiles --profile=default --debug

The config profile (user2) could not be found
```

**Additional context**

I have the profile defined in `~/.aws/credentials`, and it doesn't matter if it's also defined in `~/.aws/config` (unexpected failure if it's defined or not).

**Comment by kdaily** [comment] 2020-07-10 17:31
Hi @LomaxOnTheRun,

Thanks for the report. The [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-precedence) on this state:

> Command line options – Overrides settings in any other location. You can specify --region, --output, and --profile as parameters on the command line.

So it looks like this is unexpected behavior!

**Comment by kdaily** [comment] 2020-07-10 17:33
A related issue for behavior in the v1 client: #5248

**Comment by stobrien89** [comment] 2021-03-26 22:50
Closing, as this is a duplicate of #5016.

**Closed by stobrien89** 2021-03-26 22:50 UTC
Labels: bug, configuration
