### ISSUE TITLE
built-in help not properly formatting - probably missing a formatting code

### ISSUE THREAD

**Issue by buchs** [aws/aws-cli#7562] opened 2023-01-03 22:58 UTC
### Describe the issue

Installed the lastest version, as of today: 

```bash
$ aws --version
aws-cli/2.9.12 Python/3.9.11 Linux/5.15.0-56-generic exe/x86_64.ubuntu.22 prompt/off
$ aws help config-vars

# output to stderr:
<string>:450: (ERROR/3) Unknown interpreted text role "doc".

# output to stdout:
WS CLI CONFIGURATION VARIABLES()            AWS CLI CONFIGURATION VARIABLES()



NAME
       AWS CLI Configuration Variables -

       Configuration values for the AWS CLI can come from several sources:

.  .  .

GENERAL OPTIONS
       The AWS CLI has a few general options:

       center; |l|l|l|l|l|.  _ T{ Variable T}   T{ Option T}   T{ Config Entry
       T}   T{  Environment  Variable  T}   T{  Description  T}  _  T{ profile
       T}   T{ --profile T}   T{ N/A T}   T{ AWS_PROFILE T}   T{ Default  pro-
       file  name  T}  _  T{  region  T}   T{  --region T}   T{ region T}   T{
       AWS_DEFAULT_REGION T}   T{ Default AWS Region T} _  T{  output  T}   T{
       --output T}   T{ output T}   T{ AWS_DEFAULT_OUTPUT T}   T{ Default out-
       put style T} _ T{ cli_timestamp_format T}   T{  N/A  T}   T{  cli_time-
       stamp_format  T}   T{  N/A  T}   T{ Output format of timestamps T} _ T{
       ca_bundle T}   T{ --ca-bundle T}   T{ ca_bundle  T}   T{  AWS_CA_BUNDLE
       T}   T{  CA Certificate Bundle T} _ T{ parameter_validation T}   T{ N/A
       T}   T{ parameter_validation T}   T{ N/A T}   T{ Toggles parameter val-
       idation T} _ T{ tcp_keepalive T}   T{ N/A T}   T{ tcp_keepalive T}   T{
       N/A T}   T{ Toggles TCP Keep-Alive T} _  T{  max_attempts  T}   T{  N/A
       T}   T{  max_attempts  T}   T{ AWS_MAX_ATTEMPTS T}   T{ Number of total
       requests T} _ T{ retry_mode  T}   T{  N/A  T}   T{  retry_mode  T}   T{
       AWS_RETRY_MODE  T}   T{  Type  of  retries  performed T} _ T{ cli_pager
       T}   T{ --no-cli-pager T}   T{ cli_pager T}   T{ AWS_PAGER T}   T{  Re-
       direct/Disable output to pager T} _
```

### Links

built-in documentation

**Comment by tim-finnigan** [comment] 2023-01-04 00:21
Hi @buchs thanks for reporting this. I could also reproduce this issue on v2.9.6. 

It looks like only `aws help config-vars` is affected by this, unless there are other examples you could find. Specifically the [General Options](https://github.com/aws/aws-cli/blob/develop/awscli/topics/config-vars.rst#general-options) and [Credentials](https://github.com/aws/aws-cli/blob/develop/awscli/topics/config-vars.rst#credentials) tables are affected (the tables display fine in GitHub but are broken in terminal output). This seems to be caused by an issue with the Sphinx docs generation process.

The table formatting in the [raw config-vars.rst file](https://raw.githubusercontent.com/aws/aws-cli/develop/awscli/topics/config-vars.rst) looks fine per the [Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#tables). But more investigation is needed into the `Unknown interpreted text role "doc".` error. I'll share instances of `:doc:` in files here for our reference:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/87778557/210461999-e0839edc-d245-4ead-8ad3-1e551dcfc1c8.png">

**Comment by tim-finnigan** [comment] 2023-01-04 18:42
I brought this up for discussion with the team and a colleague noted that this was a duplicate issue: https://github.com/aws/aws-cli/issues/6296. 

There is also a PR associated linked to that issue would need to get prioritized for review. Thanks again for reporting this but I'm going to close this issue in favor of tracking in the original issue.

**Closed by tim-finnigan** 2023-01-04 18:42 UTC
Labels: bug, documentation, needs-review, p2
