### ISSUE TITLE
Add arguments for waiter retry count and delay

### ISSUE THREAD

**Issue by luiselizondo** [aws/aws-cli#2237] opened 2016-10-18 08:07 UTC
The `aws ecs wait` command tries for 10 minutes to wait for the condition to be satisfied. However, this sometimes is not enough time for the job to finish, it would be better to have a flag to set how many times to wait until the script throws an error.

**Comment by JordonPhillips** [comment] 2016-10-20 19:17
This would definitely be useful, marking as a feature request!

**Comment by ASayre** [comment] 2018-02-06 10:29
Good Morning!

We're closing this issue here on GitHub, as part of our migration to [UserVoice](https://aws.uservoice.com/forums/598381-aws-command-line-interface) for feature requests involving the AWS CLI.

This will let us get the most important features to you, by making it easier to search for and show support for the features you care the most about, without diluting the conversation with bug reports.

As a quick UserVoice primer (if not already familiar): after an idea is posted, people can vote on the ideas, and the product team will be responding directly to the most popular suggestions.

We’ve imported existing feature requests from GitHub - Search for this issue there!

And don't worry, this issue will still exist on GitHub for posterity's sake.  As it’s a text-only import of the original post into UserVoice, we’ll still be keeping in mind the comments and discussion that already exist here on the GitHub issue.

GitHub will remain the channel for reporting bugs.  

Once again, this issue can now be found by searching for the title on: https://aws.uservoice.com/forums/598381-aws-command-line-interface 

-The AWS SDKs & Tools Team

**Comment by jamesls** [comment] 2018-04-06 20:17
Based on community feedback, we have decided to return feature requests to GitHub issues.

**Comment by rubenfonseca** [comment] 2018-04-11 20:02
Great! Is it possible to wait longer then? I'm having this problem too were 10 minutes is not enough, specially with fargate tasks.

**Comment by Puneeth-n** [comment] 2018-10-11 08:13
@rubenfonseca The way I tackle it now is by sleeping for extra minutes that I'm sure the service won't be stable. Hack but a workaround.

**Comment by tim-finnigan** [comment] 2021-11-08 17:58
This looks like a duplicate of https://github.com/aws/aws-cli/issues/1295. They are also requesting parameters to modify the delay and max attempts in wait commands so I think we should close this issue in favor of that one.

**Closed by tim-finnigan** 2021-11-08 17:58 UTC
Labels: duplicate, feature-request, ecs
