### ISSUE TITLE
s3api list-parts --starting-token does not accept input from CLI

### ISSUE THREAD

**Issue by superboum** [aws/aws-cli#6666] opened 2022-01-20 15:03 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The `--starting-token` parameter of `aws s3api list-parts` parses its value as a `string` and fails to assign it to the `PartNumberMarker` field of the request object that expects an `int`. 

```
Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: 40, type: <class 'str'>, valid types: <class 'int'>
```

**SDK version number**
**Platform/OS/Hardware/Device**

```
aws-cli/2.3.4 Python/3.9.6 Linux/5.10.90 source/x86_64.nixos.21 prompt/off
```

I am using NixOS 21.11, the exact definition is located here: https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/tools/admin/awscli2/default.nix#L109

This bug has already been reported in a completely different system a year ago:
```
aws-cli/2.1.14 Python/3.7.3 Linux/4.19.121-linuxkit docker/x86_64.amzn.2 prompt/off 
SLES12.4
```

**To Reproduce (observed behavior)**
Run:

```
$ aws s3api list-parts \
  --bucket my-bucket \
  --key 'multipart/01' \
  --upload-id fRtDYU0WWCCcH43C3WFbkRONycyCpTJJvxu2i5GYkZljF.Yxwh6XG7WfS2vC4to6HiV6Yjlx.cph0gtNBtJ8P3URCSbB7rjxI5iEwVDmgaXZOGgkk5nVTW16HOQ5l0R \
  --starting-token 40

Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: 40, type: <class 'str'>, valid types: <class 'int'>
```

**Expected behavior**

A listing containing parts of a given upload greater than the specified part number (in my previous example, all parts strictly above 40).

Example:

```
        {
              "Owner": {
                  "DisplayName": "aws-account-name",
                  "ID": "100719349fc3b6dcd7c820a124bf7aecd408092c3d7b51b38494939801fc248b"
              },
              "Initiator": {
                  "DisplayName": "username",
                  "ID": "arn:aws:iam::0123456789012:user/username"
              },
              "Parts": [
                  {
                      "LastModified": "2015-06-02T18:07:35.000Z",
                      "PartNumber": 41,
                      "ETag": "\"e868e0f4719e394144ef36531ee6824c\"",
                      "Size": 5242880
                  },
                  {
                      "LastModified": "2015-06-02T18:07:42.000Z",
                      "PartNumber": 42,
                      "ETag": "\"6bb2b12753d66fe86da4998aa33fffb0\"",
                      "Size": 5242880
                  },
                  {
                      "LastModified": "2015-06-02T18:07:47.000Z",
                      "PartNumber": 43,
                      "ETag": "\"d0a0112e841abec9c9ec83406f0159c8\"",
                      "Size": 5242880
                  }
              ],
              "StorageClass": "STANDARD"
          }
```

**Logs/output**

```
2022-01-20 15:54:29,696 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.3.4 Python/3.9.6 Linux/5.10.90 source/x86_64.nixos.21
2022-01-20 15:54:29,696 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3api', 'list-parts', '--bucket', 'x', '--key', 'x', '--upload-id', 'x', '--starting-token', '40']
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7f79b0957d30>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7f79b0b1f3a0>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f79b0bb4c10>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7f79b0b44b80>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7f79b096a700>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7f79b0aed160>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2022-01-20 15:54:29,708 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7f79b0960940>
2022-01-20 15:54:29,708 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/data/cli.json
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7f79b0a2ca60>
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7f79b0a2d5e0>
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7f79b0a2d550>
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7f79b0a2d700>
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7f79b0a2d670>
2022-01-20 15:54:29,712 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7f79b0885740>
2022-01-20 15:54:29,713 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.3.4 Python/3.9.6 Linux/5.10.90 source/x86_64.nixos.21 prompt/off
2022-01-20 15:54:29,713 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3api', 'list-parts', '--bucket', 'x', '--key', 'x', '--upload-id', 'x', '--starting-token', '40']
2022-01-20 15:54:29,713 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7f79b095b3a0>
2022-01-20 15:54:29,713 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7f79b0e29310>
2022-01-20 15:54:29,713 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7f79b08c7ca0>
2022-01-20 15:54:29,713 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7f79b0e20670>
2022-01-20 15:54:29,713 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f79b0e02dc0>
2022-01-20 15:54:29,716 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2022-01-20 15:54:29,718 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7f79b0aed040>
2022-01-20 15:54:29,718 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7f79b0b1c280>
2022-01-20 15:54:29,729 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/data/s3/2006-03-01/service-2.json
2022-01-20 15:54:29,749 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7f79b0960940>
2022-01-20 15:54:29,760 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/data/s3/2006-03-01/waiters-2.json
2022-01-20 15:54:29,761 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('bucket', <awscli.arguments.CLIArgument object at 0x7f79abdf1b80>), ('key', <awscli.arguments.CLIArgument object at 0x7f79abdf1b20>), ('max-parts', <awscli.arguments.CLIArgument object at 0x7f79abdf1af0>), ('part-number-marker', <awscli.arguments.CLIArgument object at 0x7f79abdf1ac0>), ('upload-id', <awscli.arguments.CLIArgument object at 0x7f79abdf1cd0>), ('request-payer', <awscli.arguments.CLIArgument object at 0x7f79abdf1d00>), ('expected-bucket-owner', <awscli.arguments.CLIArgument object at 0x7f79abdf1d60>)])
2022-01-20 15:54:29,761 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.list-parts: calling handler <function add_streaming_output_arg at 0x7f79b095b670>
2022-01-20 15:54:29,761 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.list-parts: calling handler <function add_cli_input_json at 0x7f79b0e0c5e0>
2022-01-20 15:54:29,762 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.list-parts: calling handler <function add_cli_input_yaml at 0x7f79b0e0c820>
2022-01-20 15:54:29,762 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.list-parts: calling handler <function unify_paging_params at 0x7f79b0b1f9d0>
2022-01-20 15:54:29,772 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/data/s3/2006-03-01/paginators-1.json
2022-01-20 15:54:29,773 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListParts
2022-01-20 15:54:29,773 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.list-parts: calling handler <function add_generate_skeleton at 0x7f79b0a2c040>
2022-01-20 15:54:29,773 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.list-parts: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f79abdf1e20>>
2022-01-20 15:54:29,773 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.list-parts: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f79abdf1e50>>
2022-01-20 15:54:29,773 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.list-parts: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f79abd8d1f0>>
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.s3api.list-parts: calling handler functools.partial(<function check_should_enable_pagination at 0x7f79b0b1faf0>, ['part-number-marker', 'max-parts'], {}, OrderedDict([('bucket', <awscli.arguments.CLIArgument object at 0x7f79abdf1b80>), ('key', <awscli.arguments.CLIArgument object at 0x7f79abdf1b20>), ('max-parts', <awscli.arguments.CLIArgument object at 0x7f79abdf1af0>), ('part-number-marker', <awscli.arguments.CLIArgument object at 0x7f79abdf1ac0>), ('upload-id', <awscli.arguments.CLIArgument object at 0x7f79abdf1cd0>), ('request-payer', <awscli.arguments.CLIArgument object at 0x7f79abdf1d00>), ('expected-bucket-owner', <awscli.arguments.CLIArgument object at 0x7f79abdf1d60>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f79abdf1e20>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f79abdf1e50>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x7f79abdf1fa0>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x7f79abdf1ee0>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x7f79abd8d130>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f79abd8d1f0>)]))
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.bucket: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.list-parts: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f79b0e4a940>
2022-01-20 15:54:29,775 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'x' for parameter "bucket": 'x'
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.list-parts: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f79b0e4a940>
2022-01-20 15:54:29,775 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'x' for parameter "key": 'x'
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.max-parts: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,775 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.part-number-marker: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.upload-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.list-parts: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7f79b0e4a940>
2022-01-20 15:54:29,776 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'x' for parameter "upload_id": 'x'
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.request-payer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.expected-bucket-owner: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.list-parts.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7f79b0056100>
2022-01-20 15:54:29,776 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.list-parts: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x7f79abdf1e20>>
2022-01-20 15:54:29,777 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.list-parts: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x7f79abdf1e50>>
2022-01-20 15:54:29,777 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.list-parts: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7f79abd8d1f0>>
2022-01-20 15:54:29,777 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.list-parts: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x7f79b0b1fee0>, ['PartNumberMarker', 'MaxParts'])
2022-01-20 15:54:29,777 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2022-01-20 15:54:29,777 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2022-01-20 15:54:29,777 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2022-01-20 15:54:29,777 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2022-01-20 15:54:29,777 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2022-01-20 15:54:29,778 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2022-01-20 15:54:29,778 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/data/endpoints.json
2022-01-20 15:54:29,790 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f79b1915310>
2022-01-20 15:54:29,793 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f79b1943c10>
2022-01-20 15:54:29,793 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f79b19439d0>
2022-01-20 15:54:29,794 - MainThread - botocore.regions - DEBUG - Creating a regex based endpoint for s3, garage
2022-01-20 15:54:29,798 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2022-01-20 15:54:29,800 - MainThread - botocore.paginate - DEBUG - Attempting to fall back to old starting token parser. For token: 40
2022-01-20 15:54:29,800 - MainThread - botocore.paginate - DEBUG - Attempting to fall back to old starting token parser. For token: 40
2022-01-20 15:54:29,800 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.s3.ListParts: calling handler <function base64_decode_input_blobs at 0x7f79b08ca430>
2022-01-20 15:54:29,801 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListParts: calling handler <function validate_bucket_name at 0x7f79b18b35e0>
2022-01-20 15:54:29,801 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListParts: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f79ab9b4bb0>>
2022-01-20 15:54:29,801 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListParts: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f79ab9b4c10>>
2022-01-20 15:54:29,801 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListParts: calling handler <function generate_idempotent_uuid at 0x7f79b18b3430>
2022-01-20 15:54:29,801 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/clidriver.py", line 459, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/clidriver.py", line 594, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/clidriver.py", line 770, in __call__
    return self._operation_caller.invoke(
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/clidriver.py", line 903, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/clidriver.py", line 925, in _display_response
    formatter(command_name, response, stream)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/formatter.py", line 82, in __call__
    response_data = response.build_full_result()
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/client.py", line 569, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/client.py", line 617, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/nix/store/76v1mf5dgkmzmg3bs0zfvvh4r0bgp6rs-awscli2-2.3.4/lib/python3.9/site-packages/awscli/botocore/validate.py", line 337, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: 40, type: <class 'str'>, valid types: <class 'int'>

Parameter validation failed:
Invalid type for parameter PartNumberMarker, value: 40, type: <class 'str'>, valid types: <class 'int'>
```

**Additional context**

This issue has been previously signaled as #5841 but incorrectly closed by OP.

**Comment by tim-finnigan** [comment] 2022-01-20 20:26
Hi @superboum thanks for reaching out. I think [this comment](https://github.com/aws/aws-cli/issues/5841#issuecomment-751356467) from the issue you linked to is relevant:


> The starting token for the above example doesn't look like what I would expect in a multi-part upload. Reading the [pagination documentation for S3](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html), I would be looking for a token like `eyJNYXJrZXIiOiBudWxsLCAiYm90b190cnVuY2F0ZV9hbW91bnQiOiAxfQ==` rather than `1`.


So the starting token should look more like what is mentioned above. In the `list-parts` [documentation](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-parts.html) it notes that `--starting-token` is the `NextToken` from a previously truncated response.

There isn’t a CLI parameter for `PartNumberMarker` because the API has a paginator as explained in [another comment](https://github.com/aws/aws-cli/issues/5841#issuecomment-751844732). I hope that helps, please let me know if you have any other questions.

**Comment by kdaily** [comment] 2022-01-21 00:30
Hi @superboum,

What @tim-finnigan wrote above is correct! The error message is somewhat obfuscating the solution, or why it's occuring.

The Python/CLI pagination system allows for different services and operations to have the same interface to paginate. It was written in a backwards-compatible way, and to support users who were manually performing pagination. The error in your case is caused by providing a value for a `starting-token` that can't be parsed into the appropriate service side parameters. Instead, it is being passed on as is, as a string (which is the improper type for the `PartNumberMarker`). To using `starting-token` properly, you need to look for the `NextToken` attribute in the output of the command. 

For example, calling `aws s3api list-parts` gives back this:

```
{
    "Parts": [
        {
            "PartNumber": 2,
            "LastModified": "2022-01-20T23:36:26.000Z",
            "ETag": "\"9901d739c680d617bf4ea54d9cff479a\"",
            "Size": 10000000
        }
    ],
    "Initiator": {
        "ID": "arn:aws:sts::12345678910:assumed-role/Admin/its-me",
        "DisplayName": "its-me"
    },
    "Owner": {
        "DisplayName": "its-me",
        "ID": "4daedb........"
    },
    "StorageClass": "STANDARD",
    "NextToken": "eyJQYXJ0TnVtYmVyTWFya2VyIjogbnVsbCwgImJvdG9fdHJ1bmNhdGVfYW1vdW50IjogMn0="
}
```

In my next call, I would do:

```
aws s3api list-parts .... --starting-token eyJQYXJ0TnVtYmVyTWFya2VyIjogbnVsbCwgImJvdG9fdHJ1bmNhdGVfYW1vdW50IjogMn0=
```

Most users prefer to use the standardized pagination system, and having the other pagination-related parameters (like `part-number-marker` for this operation) listed alongside the generalized system would be confusing. If you want to do it all yourself, you can still use the `--part-number-marker` parameter, it's just not documented in the AWS CLI documentation pages.

I'm not sure what we can do with respect to making the error message more helpful, but we'll look into it. Thanks!

**Comment by superboum** [comment] 2022-01-21 10:22
Thanks a lot for your reply and explanations. It makes sense now. 

Could I suggest some points to make the tool and the documentation more user friendly?
  - The [ListParts](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListParts.html) documentation does not mention NextToken.
  - [awscli list-parts](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-parts.html) documentation does not mention "NextToken" as part of its example (and as you mentioned `--part-number-marker` is not documented).
  - The `--starting-token` logic is not stable across 
  - The error message should not mention PartNumberMarker as it is misleading for people trying to follow the documentation and set the "PartNumberMarker" field. From your example, it seems that your opaque token is in fact the following base64 encoded json `{"PartNumberMarker": null, "boto_truncate_amount": 2}`. Failing to deserialize this token might be the reason that awscli complains about "PartNumberMarker". But it is quite strange that the command leaks the implementation of something which is considered opaque. I would suggest documenting these opaque tokens or hiding totally their implementation.

**Comment by kdaily** [comment] 2022-01-21 16:58
Thanks for the suggestions and feedback!

Linking to the [pagination documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html), specifically, "How to use the --starting-token parameter", on operations that are paginated might be useful.

I don't think we can standardize any further on how `--starting-token` works, as this is dependent on each AWS service. Services were introduced at different times, and need to maintain backwards compatibility. The abstraction that exists allows for older services to continue working.

Another thing that is confusing but not easy to control is that the [description section](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-parts.html#description) in the CLI documentation comes from the API and is the same across all AWS SDKs. Because of this, it talks about this service's pagination with the original API parameters. We don't have a way to redact or remove this text or otherwise indicate the CLI works differently.

However, on each page we could try to highlight more clearly that pagination here works differently and why it's better. We could also make it more clear that you can check the AWS API documentation page for the original parameters. I'm not sure what an appendix would look like, but that might be possible as well.

I think I can close this issue, but I'll open up another tracking issue to suggest improvements to how pagination is documented, and link to your suggestions here. 

Thanks again!

**Closed by kdaily** 2022-01-21 16:58 UTC
Labels: documentation, feature-request, s3api
