### ISSUE TITLE
GitHub API /releases only shows one aws-cli release

### ISSUE THREAD

**Issue by peterwwillis** [aws/aws-cli#6232] opened 2021-06-17 15:36 UTC
**Describe the bug**

GitHub API is only returning one release of this project, even though the [tags](https://api.github.com/repos/aws/aws-cli/tags) endpoint shows all the tags.

**To Reproduce (observed behavior)**
 - Look at https://api.github.com/repos/aws/aws-cli/releases
 - Then look at https://github.com/aws/aws-cli/releases

**Expected behavior**
Multiple releases returned by the releases API endpoint. (example: [Versent/saml2aws/releases](https://api.github.com/repos/Versent/saml2aws/releases))

**Additional context**
I was trying to query aws-cli releases using the GitHub API, and it looks like only one release is being returned. If you look at any other project (e.g. https://api.github.com/repos/Versent/saml2aws/releases) there's plenty of releases shown.

**Comment by peterwwillis** [comment] 2021-06-17 15:39
Haha... I just realized what's happening. There *is* only one release. I got confused by the `/releases` list in the UI, as it's showing the tags rather than releases.

You might want to delete that one release just to prevent confusion?

**Comment by kdaily** [comment] 2021-06-17 16:40
Hello @peterwwillis,

Thanks for the comment! I totally agree with you, and this has been requested previously. It will require some changes to internal builds to accomplish.

I'm going to close this as a duplicate of #5471, so please follow along there and 👍🏻 the original post to indicate your support for the feature.

**Closed** 2021-06-17 16:40 UTC
Labels: duplicate, feature-request, installation
