### ISSUE TITLE
aws-cli v2 ecr-login results with 400 Bad Request

### ISSUE THREAD

**Issue by johnny-fuse** [aws/aws-cli#5950] opened 2021-02-17 22:31 UTC
aws-cli v2 ecr-login not working

According to the documentation I am trying to run:

```
docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_REGION=$AWS_REGION --rm -it amazon/aws-cli:latest --region $AWS_REGION ecr get-login-password \
          | docker login \
              --username AWS \
              --password-stdin 816841120843.dkr.ecr.$AWS_REGION.amazonaws.com
```
              
All environment variables are configured correctly, and still getting:

`Error response from daemon: login attempt to https://816841120843.dkr.ecr.us-east-2.amazonaws.com/v2/ failed with status: 400 Bad Request`

**Platform/OS/Hardware/Device**
Mac/CircleCI agent

**Comment by stobrien89** [comment] 2021-02-18 20:26
Hi @johnny-fuse,

Thanks for writing in!  I think this may be a duplicate of [#4962](https://github.com/aws/aws-cli/issues/4962).  I'd have a look there to see if you find any useful info.  Let us know either way—If not, we'll be happy to look into this further!

**Closed** 2021-02-24 00:02 UTC
Labels: docker, duplicate, ecr
