### ISSUE TITLE
ecr get-login returns invalid docker login

### ISSUE THREAD

**Issue by kpitzen** [aws/aws-cli#2803] opened 2017-08-31 17:43 UTC
As of 2017/08/29, docker has removed the -e argument from docker login [https://github.com/docker/cli/pull/143](https://github.com/docker/cli/pull/143).  To properly use aws ecr get-login as a tool to generate docker logins, that should be removed from the returned string as well.

**Comment by kpitzen** [comment] 2017-08-31 17:50
![image](https://user-images.githubusercontent.com/4128006/29937386-f619c2fc-8e4a-11e7-8910-6325a9391fbd.png)

**Comment by joguSD** [comment] 2017-08-31 19:15
You can remove that by specifying the `--no-include-email` flag. We default to including the email so we don't break customers still relying on it.

Duplicate of #2753, #2743, #2732, #2694, #2691, #2676, and a few others

**Closed by joguSD** 2017-08-31 19:15 UTC
Labels: duplicate
