### ISSUE TITLE
`aws s3 cp` fails on GitHub action for large file (~40MB) on awscli 2.2.1

### ISSUE THREAD

**Issue by bertrand-caron** [aws/aws-cli#6154] opened 2021-05-10 07:15 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I can upload a small file (6 Bytes) to S3 from a GitHub runner, but not a larger one (~40MB).

**SDK version number**
2.2.1

**Platform/OS/Hardware/Device**
GitHub Action (`ubuntu-latest`)

**To Reproduce (observed behavior)**
Try uploading a large file to an S3 bucket with `aws s3 cp ...`.

**Expected behavior**
The file will upload.

**Logs/output**

NB: Actual bucket name has been anonymised (replaced with `***`).

```
2021-05-10T06:40:49.4062012Z ##[group]Run aws s3 cp --debug android/app/build/outputs/apk/release/app-release.apk s3://${BUCKET_NAME}/app-87.apk
2021-05-10T06:40:49.4063176Z [36;1maws s3 cp --debug android/app/build/outputs/apk/release/app-release.apk s3://${BUCKET_NAME}/app-87.apk[0m
2021-05-10T06:40:49.4444864Z shell: /usr/bin/bash -e {0}
2021-05-10T06:40:49.4445241Z env:
2021-05-10T06:40:49.4446144Z   AWS_ACCESS_KEY_ID: ***
2021-05-10T06:40:49.4446957Z   AWS_SECRET_ACCESS_KEY: ***
2021-05-10T06:40:49.4447777Z   BUCKET_NAME: ***
2021-05-10T06:40:49.4448552Z ##[endgroup]
2021-05-10T06:40:50.1034690Z 2021-05-10 06:40:50,103 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.1 Python/3.8.8 Linux/5.4.0-1046-azure exe/x86_64.ubuntu.20
2021-05-10T06:40:50.1039456Z 2021-05-10 06:40:50,103 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', '--debug', 'android/app/build/outputs/apk/release/app-release.apk', 's3://***/app-87.apk']
2021-05-10T06:40:50.1253241Z 2021-05-10 06:40:50,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x7fd3dd0c74c0>
2021-05-10T06:40:50.1256624Z 2021-05-10 06:40:50,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x7fd3dd285280>
2021-05-10T06:40:50.1261743Z 2021-05-10 06:40:50,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2021-05-10T06:40:50.1266848Z 2021-05-10 06:40:50,125 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fd3dd2a7a60>
2021-05-10T06:40:50.1268958Z 2021-05-10 06:40:50,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x7fd3dd2afb80>
2021-05-10T06:40:50.1271368Z 2021-05-10 06:40:50,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x7fd3dd0cdee0>
2021-05-10T06:40:50.1274009Z 2021-05-10 06:40:50,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x7fd3dd24d0d0>
2021-05-10T06:40:50.1277351Z 2021-05-10 06:40:50,126 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2021-05-10T06:40:50.1280425Z 2021-05-10 06:40:50,127 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x7fd3dd0cd160>
2021-05-10T06:40:50.1282677Z 2021-05-10 06:40:50,127 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.2.1/dist/awscli/data/cli.json
2021-05-10T06:40:50.1316860Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x7fd3dd17f0d0>
2021-05-10T06:40:50.1321811Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x7fd3dd17fc10>
2021-05-10T06:40:50.1323736Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x7fd3dd17fb80>
2021-05-10T06:40:50.1326902Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x7fd3dd17fd30>
2021-05-10T06:40:50.1331117Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x7fd3dd17fca0>
2021-05-10T06:40:50.1334575Z 2021-05-10 06:40:50,131 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x7fd3dcfed7c0>
2021-05-10T06:40:50.1336298Z 2021-05-10 06:40:50,132 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.2.1 Python/3.8.8 Linux/5.4.0-1046-azure exe/x86_64.ubuntu.20 prompt/off
2021-05-10T06:40:50.1338484Z 2021-05-10 06:40:50,132 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'cp', '--debug', 'android/app/build/outputs/apk/release/app-release.apk', 's3://***/app-87.apk']
2021-05-10T06:40:50.1341797Z 2021-05-10 06:40:50,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x7fd3dd0c7af0>
2021-05-10T06:40:50.1343383Z 2021-05-10 06:40:50,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x7fd3ddb68dc0>
2021-05-10T06:40:50.1345167Z 2021-05-10 06:40:50,132 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x7fd3dd034940>
2021-05-10T06:40:50.1346674Z 2021-05-10 06:40:50,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x7fd3ddb66280>
2021-05-10T06:40:50.1348242Z 2021-05-10 06:40:50,133 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fd3ddac5a60>
2021-05-10T06:40:50.1349626Z 2021-05-10 06:40:50,133 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-10T06:40:50.1365466Z 2021-05-10 06:40:50,135 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x7fd3dd24af70>
2021-05-10T06:40:50.1367241Z 2021-05-10 06:40:50,136 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x7fd3dd283160>
2021-05-10T06:40:50.1368981Z 2021-05-10 06:40:50,136 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7fd3dd0cd160>
2021-05-10T06:40:50.1374265Z 2021-05-10 06:40:50,136 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1376770Z 2021-05-10 06:40:50,137 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3_cp: calling handler <function add_waiters at 0x7fd3dd0cd160>
2021-05-10T06:40:50.1404915Z 2021-05-10 06:40:50,139 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.paths: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1423787Z 2021-05-10 06:40:50,139 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.dryrun: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1437111Z 2021-05-10 06:40:50,139 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1440361Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.quiet: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1442805Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1445084Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1447305Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.acl: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1449720Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.follow-symlinks: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1452125Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1455519Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1458003Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1461075Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1464387Z 2021-05-10 06:40:50,140 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1468672Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-kms-key-id: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1471503Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1475152Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source-key: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1480151Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.storage-class: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1483090Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.grants: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1487451Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.website-redirect: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1491650Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-type: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1494061Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.cache-control: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1496566Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-disposition: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1499120Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-encoding: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1501832Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-language: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1504412Z 2021-05-10 06:40:50,141 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expires: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1506872Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.source-region: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1509443Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.only-show-errors: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1511893Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1514173Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1516475Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1518984Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.ignore-glacier-warnings: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1521496Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1523979Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.force-glacier-transfer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1526459Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1528787Z 2021-05-10 06:40:50,142 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.request-payer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1531120Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1533423Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.copy-props: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1535709Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fd3e0e755b0>
2021-05-10T06:40:50.1538122Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata-directive: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1540811Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expected-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1543234Z 2021-05-10 06:40:50,143 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x7fd3dc7afee0>
2021-05-10T06:40:50.1545266Z 2021-05-10 06:40:50,143 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-05-10T06:40:50.1546510Z 2021-05-10 06:40:50,145 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2021-05-10T06:40:50.1547999Z 2021-05-10 06:40:50,147 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "PUT /latest/api/token HTTP/1.1" 400 11
2021-05-10T06:40:50.1549144Z 2021-05-10 06:40:50,147 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
2021-05-10T06:40:50.1549809Z Traceback (most recent call last):
2021-05-10T06:40:50.1550341Z   File "awscli/clidriver.py", line 459, in main
2021-05-10T06:40:50.1550959Z   File "awscli/customizations/commands.py", line 197, in __call__
2021-05-10T06:40:50.1551645Z   File "awscli/customizations/commands.py", line 191, in __call__
2021-05-10T06:40:50.1552464Z   File "awscli/customizations/s3/subcommands.py", line 710, in _run_main
2021-05-10T06:40:50.1553222Z   File "awscli/customizations/s3/subcommands.py", line 480, in _run_main
2021-05-10T06:40:50.1553965Z   File "awscli/customizations/s3/factory.py", line 50, in create_client
2021-05-10T06:40:50.1554642Z   File "botocore/session.py", line 783, in create_client
2021-05-10T06:40:50.1555272Z   File "botocore/session.py", line 832, in _resolve_region_name
2021-05-10T06:40:50.1555923Z   File "botocore/session.py", line 236, in get_config_variable
2021-05-10T06:40:50.1556627Z   File "botocore/configprovider.py", line 301, in get_config_variable
2021-05-10T06:40:50.1557341Z   File "botocore/configprovider.py", line 398, in provide
2021-05-10T06:40:50.1557951Z   File "awscli/utils.py", line 103, in provide
2021-05-10T06:40:50.1558553Z   File "awscli/utils.py", line 108, in _get_instance_metadata_region
2021-05-10T06:40:50.1559180Z   File "awscli/utils.py", line 152, in retrieve_region
2021-05-10T06:40:50.1559729Z   File "awscli/utils.py", line 161, in _get_region
2021-05-10T06:40:50.1560316Z   File "botocore/utils.py", line 308, in _fetch_metadata_token
2021-05-10T06:40:50.1561413Z botocore.utils.BadIMDSRequestError: <botocore.awsrequest.AWSRequest object at 0x7fd3dc7d78e0>
2021-05-10T06:40:50.1562230Z 
2021-05-10T06:40:50.1562835Z <botocore.awsrequest.AWSRequest object at 0x7fd3dc7d78e0>
2021-05-10T06:40:50.2120257Z ##[error]Process completed with exit code 255.
```

**Additional context**
N/A

**Comment by stobrien89** [comment] 2021-05-11 21:56
Hi @bertrand-caron,

Sorry to hear about the issues.  I'm sure you noticed this from the debug logs, but it looks like the imds (instance metadata service) is returning a 400.  Looking further into this.

**Comment by stobrien89** [comment] 2021-05-12 14:35
Hi @bertrand-caron,

Thanks for the update!  It looks like this is a duplicate of [#5234](https://github.com/aws/aws-cli/issues/5234) and #5749. 
 Basically, azure has its own IMDS service, which uses the same non-routable IP address as AWS and they're not compatible.  

You should be able to either set a region, _or_ set the `EC2_METADATA_DISABLED` environment variable to `true` to work around this.  Hope this helps!

**Closed by stobrien89** 2021-05-12 14:35 UTC
Labels: duplicate, guidance, s3
