### ISSUE TITLE
aws s3api wait make the number of retries and time between retried configurable

### ISSUE THREAD

**Issue by twitu** [aws/aws-cli#6157] opened 2021-05-11 03:49 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

`aws s3api wait` provides a fantastic set of commands to check certain s3 conditions (like bucket exists or object exists) before performing some actions. HOWEVER the number of times it polls is fixed to 20 and the time between polls is fixed at 5 seconds. This limits it's application in a variety of use cases.

**Describe the solution you'd like**

Adding to parameters like
* `--polls` - number of times it will poll
* `--wait` - seconds it will wait before each poll

**Describe alternatives you've considered**

There does not appear to be an alternative. Fail the job and retry myself.

**Additional context**

An example -

I have a codebuild job that runs some tests (about 10-15 mins) and exports the output to s3. The job is triggered whenever commits are made to `dev` branch of a codecommit repo. When the developer makes a PR from `dev` to `master` a codebuild job is triggered that fetches reports from the s3 buckets, does some validation adds comments to the PR, makes approvals etc.

However right now, it's possible for me to create the PR before the test suite has completed. In this case the PR codebuild job fails because it cannot find the object. This can be resolved by allowing me to configure the wait and timeout for `aws s3api wait`

**Comment by kdaily** [comment] 2022-02-16 19:43
As @tim-finnigan noted, this is a duplicate of #1295. Closing this! Please 👍🏻 the original post in #1295 to indicate your support for this feature, and add any other comments or use cases there as well.

**Closed by kdaily** 2022-02-16 19:43 UTC
Labels: feature-request, waiter
