### ISSUE TITLE
Using ecs create-service --generate-cli-skeleton with output fails

### ISSUE THREAD

**Issue by GriffinMeyer** [aws/aws-cli#3995] opened 2019-03-08 21:32 UTC
Running ```aws ecs create-service``` with any configuration and ```--generate-cli-skeleton output``` results in the failure: ```Parameter validation failed:
Invalid type for parameter service.taskSets[0].scale.value, value: None, type: <class 'NoneType'>, valid types: <class 'float'>, <class 'decimal.Decimal'>, <class 'int'>```

Example (From the docs): ```aws ecs create-service --service-name ecs-simple-service --task-definition ecs-demo --desired-count 10 --generate-cli-skeleton output```

**Comment by swetashre** [comment] 2019-03-13 17:40
Thank you for reporting the behavior.  I was able to reproduce the issue and confirmed it as a bug. 

It looks like the same bug as this one : [#2337](https://github.com/aws/aws-cli/issues/2337)  . Let's track the progress on the linked GitHub issue. Closing this issue as a duplicate.

**Closed** 2019-03-15 17:28 UTC
Labels: bug, duplicate
