### ISSUE TITLE
CLI should unset LD_LIBRARY_PATH before running external aliases

### ISSUE THREAD

**Issue by krschwab** [aws/aws-cli#6416] opened 2021-09-22 15:00 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When you add an alias to the ~/.aws/cli/aliases file that runs an external command, it runs that command with the LD_LIBRARY_PATH environment variable set to something that causes issues with some external commands.   In my setup, it sets LD_LIBRARY_PATH to /usr/local/aws-cli/v2/2.2.38/dist.

This creates issues with some external commands.   For me, for example, I get this message on stderr when running an external python command that is linked to libz:

`python3: /usr/local/aws-cli/v2/2.2.38/dist/libz.so.1: no version information available (required by python3)`

I see other shared libs in there for sqlite, libbz2, libffi, liblzma, etc.  So while my error was mostly just an annoyance, I could see it creating bigger issues in other cases. 

**SDK version number**
2.2.38 

**Platform/OS/Hardware/Device**
Linux under Microsoft Windows WSL.

**To Reproduce (observed behavior)**
Add this alias:
```
[toplevel]
dumpenv=!env
```
Now, run this command:
`$ aws dumpenv|grep LD_LIBRARY_PATH`

You'll see that LD_LIBRARY_PATH is being set

**Expected behavior**
LD_LIBRARY_PATH should not be set.

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
You can work around this by unsetting LD_LIBRARY_PATH in the alias, like this:
```
[toplevel]
foo=!unset LD_LIBRARY_PATH;/bin/somecommand
```
But that's not an ideal solution.

**Comment by kdaily** [comment] 2021-09-23 16:46
Hi @krschwab,

Thanks for your post and sorry to hear you're having an issue.

This is related to how the CLI is built using PyInstaller and was added for other feature support (https://github.com/aws/aws-cli/pull/4964). It's causing the same issue (https://github.com/aws/aws-cli/issues/5506) with the `credential_process` which also uses a subprocess to run, like an external alias.

I'm going to link this issue to #5506 and close this as a duplicate since it's for the same underlying problem. Thanks again for reporting it!

**Comment by kdaily** [comment] 2021-09-23 16:46
Closing as a duplicate of #5506, please add any other comments there. Thank you!

**Closed by kdaily** 2021-09-23 16:46 UTC
Labels: bug, duplicate
