### ISSUE TITLE
VirusTotal reports a virus

### ISSUE THREAD

**Issue by uli-heller** [aws/aws-cli#6259] opened 2021-07-03 04:47 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
[VirusTotal.com](htttps://virustotal.com) reports a virus for "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip".
It doesn't report a virus for the github downloads

**Versions**
2.2.15, 2.2.14 and 2.2.5 - I didn't checl the other ones

**To Reproduce (observed behavior)**
1. Download the ZIP from https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip or https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.2.5.zip
2. Upload the ZIP to [VirusTotal.com](htttps://virustotal.com)
3. Wait and see

![image](https://user-images.githubusercontent.com/1677414/124343190-f1688380-dbc9-11eb-8367-1bd856310013.png)

**NOT To Reproduce**
1. Specify the download URL within [VirusTotal.com](htttps://virustotal.com)
2. Wait and see

![image](https://user-images.githubusercontent.com/1677414/124343215-1b21aa80-dbca-11eb-9cd1-4e18ca5c01ab.png)

**Additional info**

I am concerned about two issues actually. First (the obvious one): I'm scared about the virus warning. Second (the less obvious one): I'm scared about the different results. Does VirusTotal.com get a different ZIP than myself? 

Sorry for not using the template, I think it doesn't fit because I'm not reporting a bug within awscli but within the packaging.

**Comment by stobrien89** [comment] 2021-07-06 18:35
Hi @uli-heller,

Thanks for reaching out!  I'm not certain why there would be different results reflected from the link as opposed to uploading the zip directly, but it's safe to say that this is a false positive.  We had a similar issue with our Windows executables earlier this year.  The main problem is that we sign the zipfiles with a PGP detached signature, and because it's detached, there is no way to associate it with the artifact that we upload.  At this time, there isn't a great alternative.

**Comment by joguSD** [comment] 2021-07-06 18:59
Also, if you are concerned about the integrity of the file you're downloading you can use the instructions here: 

https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html#v2-install-linux-validate

To verify that the artifact matches the PGP signature we upload alongside the artifact to guarantee the integrity of your download.

**Comment by uli-heller** [comment] 2021-07-07 04:35
Hi @stobrien89 ,

thx for explaining. I don't have anything to complain about detached signatures, I just didn't know that they exist for awscli. Now I do understand that you (the team) assume it is a false positive and since I'm trusting you (the team) that's probably the best I can get.

Many thx to @joguSD as well for pointing me to the validation instructions. I followed them and all my 3 downloads seem to be OK:

```
uli@ulicsl:~/Downloads$ LANG=C gpg --verify awscli-exe-linux-x86_64-2.2.5.zip.sig awscli-exe-linux-x86_64-2.2.5.zip
gpg: Signature made Fri May 14 23:26:02 2021 CEST
gpg:                using RSA key FB5DB77FD5C118B80511ADA8A6310ACC4672475C
gpg: Good signature from "AWS CLI Team <aws-cli@amazon.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FB5D B77F D5C1 18B8 0511  ADA8 A631 0ACC 4672 475C
uli@ulicsl:~/Downloads$ LANG=C gpg --verify awscli-exe-linux-x86_64-2.2.15.zip.sig awscli-exe-linux-x86_64-2.2.15.zip
gpg: Signature made Tue Jun 29 22:54:34 2021 CEST
gpg:                using RSA key FB5DB77FD5C118B80511ADA8A6310ACC4672475C
gpg: Good signature from "AWS CLI Team <aws-cli@amazon.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FB5D B77F D5C1 18B8 0511  ADA8 A631 0ACC 4672 475C
uli@ulicsl:~/Downloads$ LANG=C gpg --verify awscli-exe-linux-x86_64-2.2.14.zip.sig awscli-exe-linux-x86_64-2.2.14.zip
gpg: Signature made Thu Jun 24 23:33:45 2021 CEST
gpg:                using RSA key FB5DB77FD5C118B80511ADA8A6310ACC4672475C
gpg: Good signature from "AWS CLI Team <aws-cli@amazon.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: FB5D B77F D5C1 18B8 0511  ADA8 A631 0ACC 4672 475C
```

So I cannot do more related to this although false positives aren't great ;)

Related to the difference between URL and file scanning,  I've found a [faq@virustotal](https://support.virustotal.com/hc/en-us/articles/115002092509-Some-URL-scanner-detects-a-given-URL-but-its-corresponding-antivirus-solution-does-not-detect-the-downloaded-file-or-vice-versa) but the explanation is not very convincing. Basically it says "can happen". So probably nothing to be discussed here.

The last topic: Above, I see "uli-heller added the needs-triage label 4 days ago:

![image](https://user-images.githubusercontent.com/1677414/124700658-60591b80-deed-11eb-9ff0-62154ed4becf.png)

I think i did **not** add the label!

Very last topic: Shall we close the issue?

**Comment by stobrien89** [comment] 2021-07-08 17:54
Hi @uli-heller,

Unfortunately, this isn't the first time we've received a false positive from that particular vendor.  We've attempted to contact them previously with no response.  

The `needs-triage` label is automatically added when an issue is created 😄.  I'll leave this open for the time being, or at least until we can confirm we're not getting flagged in subsequent releases.  Thanks again for letting us know!

**Comment by stobrien89** [comment] 2021-07-13 15:25
Hi @uli-heller,

I discussed this with the team and since there's nothing we can do about this right now and this is a confirmed false positive, I'll be closing this. Thanks once more for letting us know!

**Closed by stobrien89** 2021-07-13 15:25 UTC
Labels: guidance, installation
