### ISSUE TITLE
Can not get multible statistics (Average, Sum,...) in cloudwatch get-metrics-statistics

### ISSUE THREAD

**Issue by AlexanderThaller** [aws/aws-cli#342] opened 2013-09-10 13:57 UTC
I'm trying to pull multiple statistics from a single metric with following command:

> `aws cloudwatch get-metric-statistics --namespace AWS/EBS --metric-name VolumeQueueLength --period 300 --start-time 2013-09-09T11:46:36+0000 --end-time 2013-09-10T11:41:36+0000 --statistics SampleCount,Average,Sum,Minimum,Maximum --dimension Name=VolumeId,Value=vol-8694a3d3`

I just get the following error:
> A client error (InvalidParameterValue) occurred: The parameter Statistics.member.1 must be a value in the set [Sum, Maximum, Minimum, SampleCount, Average].

I tried different separators like `␣|␣`, or `␣` but no change.

Im using the following version:
> `aws-cli/1.0.0 Python/2.7.3 Linux/3.2.0-53-generic-pae`

**Comment by mickm** [comment] 2015-01-14 20:38
I just ran into this migrating some scripts that use the Java cli tool, which wants a comma delimited list.

It turns out aws-cli wants spaces: e.g. `--statistics Foo Bar Baz` (no quotes)

It's in the docs here: http://docs.aws.amazon.com/cli/latest/reference/cloudwatch/get-metric-statistics.html

**Comment by jamesls** [comment] 2015-01-15 21:35
Thanks for the clarification.  Looks like the CLI is working as intended.  Closing out issue.

**Closed by jamesls** 2015-01-15 21:35 UTC
Labels: question
