### ISSUE TITLE
EC2 create-snapshot error after Python Update

### ISSUE THREAD

**Issue by shanemarsh28** [aws/aws-cli#2980] opened 2017-11-23 01:04 UTC
Previously, executing the following CLI command has been working perfectly until I ran a disto upgrade today.

`aws ec2 create-snapshot --volume-id [VOLUME ID] --description "Backup"`

The upgrade command I ran was: 
`sudo apt-get update && time sudo apt-get dist-upgrade`

This upgraded Python3 to the latest version and installed any dependencies.

However now I receive the following error upon executing the create-snapshot command. It simply returns:
> AWSHTTPSConnection' object has no attribute 'ssl_context'

AWS Version output:
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1041-aws botocore/1.4.70

OS Version: 
Ubuntu 16.04.3 LTS

Please let me know if more information is required. Sensitive data omitted.

**Comment by shanemarsh28** [comment] 2017-11-23 22:12
Just to update, it appears all ec2 funtions are affected. This is the latest output from our automated systems:

`------------ DESCRIBE ---------- 
/usr/bin/aws ec2 describe-snapshots --filters Name='volume-id',Values='vol-xxxxxxxxxxxxx' Name='description',Values='backup'NULL 

'AWSHTTPSConnection' object has no attribute 'ssl_context' `

**Comment by joguSD** [comment] 2017-11-24 19:12
Duplicate of https://github.com/boto/botocore/issues/1258

There are some workarounds listed in that thread, but the root cause is that the debian package maintainers are unvendoring requests from our package which causes unforeseen issues. 

Closing in favor of the above issue.

**Closed by joguSD** 2017-11-24 19:12 UTC
