### ISSUE TITLE
Assume a role from IAM role configuration

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-cli#2924] opened 2017-10-26 13:08 UTC
From an IAM role on my EC2, I'm trying to assume a role **role/Example** and it just returns **'aws_access_key_id'**, which I'm going to assume means it didn' t work.

```
~$ aws --version
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-1022-aws botocore/1.4.70
ubuntu@ip-10-0-0-168:~$ curl http://169.254.169.254/latest/meta-data/iam/info
{
  "Code" : "Success",
  "LastUpdated" : "2017-10-26T12:52:27Z",
  "InstanceProfileArn" : "arn:aws:iam::407461997746:instance-profile/ecsInstanceRole",
  "InstanceProfileId" : "AIPAIJSC55LUFNN24KQAM"
ubuntu@ip-10-0-0-168:~$ cat ~/.aws/config
[default]
region = ap-southeast-1

[profile to]
role_arn = arn:aws:iam::407461997746:role/Example
source_profile = default
ubuntu@ip-10-0-0-168:~$ aws --profile to s3 ls

'aws_access_key_id'

```

So how do I assume a role without setting AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY ? I.e. leveraging the IAM role?

**Comment by JordonPhillips** [comment] 2017-10-26 15:51
This isn't something we currently support, though it is something we'd like to support sooner rather than later.

Duplicate of #1390

**Closed** 2017-10-26 15:52 UTC
Labels: duplicate
