### ISSUE TITLE
aws gives no output on windows

### ISSUE THREAD

**Issue by tenpn** [aws/aws-cli#4504] opened 2019-09-18 08:31 UTC
I've been using aws cli on this laptop for a while to interact with s3 buckets. Suddenly, the tool has stopping printing any output whatsoever:

    C:\>aws

    C:\>aws --debug

    C:\>aws --help

    C:\>where aws
    C:\Users\Andrew\AppData\Roaming\Python\Python37\Scripts\aws
    C:\Users\Andrew\AppData\Roaming\Python\Python37\Scripts\aws.cmd

This is in an administrator command prompt, but it's the same in an admin powershell prompt. Windows version 10.0.18362 Build 18362 - I took the anniversary update a few weeks ago but am not sure if it's correlated or not.

aws cli on my other (Win 10, anniversary update) machine, using the same authentication, works fine.

I've tried straight-up uninstalling and reinstalling aws cli, but to the same effect. no command I try will produce output.

Any ideas? Any more information I can give you?

**Comment by tun3r** [comment] 2019-09-18 19:31
I'm seeing the same issue as well. It was working fine at least last week. I ran pip3 awscli upgrade but that didn't help.

**Comment by tenpn** [comment] 2019-09-23 08:31
...maybe there's some cached data somewhere, and if we removed that when we uninstalled/reinstalled aws, everything would start working again?

**Comment by joguSD** [comment] 2019-10-01 23:01
Hmm, it looks like you're installing via `pip`? Is that correct?

I might suggest uninstalling the CLI install you have now and trying the [MSI Installer](https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#install-msi-on-windows) if you haven't already. Let me know if that helps.

**Comment by tenpn** [comment] 2019-10-03 08:42
yeah, `pip uninstall awscli` then using the msi fixed it. but I'd prefer to be on pip, so it would be good to understand why things broke and how to fix it.

**Comment by kdaily** [comment] 2020-08-13 21:22
Hi @tenpn, does this still persist for you when installing via `pip`? I could not reproduce either on Windows 10.

**Comment by tun3r** [comment] 2020-08-14 01:46
At some point some time ago it started magically working again. I can no longer reproduce it, too.

**Comment by kdaily** [comment] 2020-09-25 21:11
Thanks for updating. Closing this for now, but if it should reoccur, re-open an issue. Thanks!

**Closed by kdaily** 2020-09-25 21:11 UTC
Labels: guidance, needs-reproduction

**Comment by conan19842002** [comment] 2021-03-02 10:26
Hello, I've got the same issue even after reinstalling awscli via msi. Any help please?
