### ISSUE TITLE
'aws apigateway get-method help' does not work

### ISSUE THREAD

**Issue by edmundcraske** [aws/aws-cli#2786] opened 2017-08-22 11:04 UTC
If I run 'aws apigateway get-method help' to see the help for the get-method command for apigateway, instead of getting the documentation for the command, I get the following:

`<string>:8: (WARNING/2) Duplicate explicit target name: "aws cli".`

I then have to press ctrl-c to get back to the command prompt.

Environment: Mac OS X El Capitan, awscli installed from homebrew, version 1.11.137.

**Comment by edmundcraske** [comment] 2017-08-22 11:07
Having read the contributing guide, I realise I didn't include the output of `aws --version`...

`$ aws --version
aws-cli/1.11.137 Python/2.7.10 Darwin/15.6.0 botocore/1.6.4`

**Comment by cwgem** [comment] 2017-08-22 14:50
Looks like the issue is there are as stated two AWS CLI targets:

```
`AWS CLI <http://docs.aws.amazon.com/cli/latest/reference/apigateway/get-method-response.html>`_ 
```

```
`AWS CLI <http://docs.aws.amazon.com/cli/latest/reference/apigateway/get-integration.html>`_ 
```

While I still find out odd that you would need to CTRL+C out (it should just show the warning but still give you content) I'm filed boto/botocore#1268 to hopefully get rid of the warning for this and potentially other duplicate target warnings.

**Comment by JordonPhillips** [comment] 2017-08-22 16:04
Looks like the change is related to a recent change we made to make all links explicit so that we could have duplicates. Turns out that rst wants you to put two underscores after explicit hyperlinks to make them "anonymous". Sphinx will render what you would expect, but throw a warning.

**Comment by JordonPhillips** [comment] 2017-08-22 16:04
Closing out here to track on the botocore issue

**Closed by JordonPhillips** 2017-08-22 16:04 UTC
Labels: bug, documentation
