### ISSUE TITLE
Appflow Error on ValidationException

### ISSUE THREAD

**Issue by gtjones73** [aws/aws-cli#6073] opened 2021-04-07 17:30 UTC
The command behaves inconsistent with my reading of the documentation.

FAILS
aws appflow list-flows  --profile qaedp --region us-east-2
An error occurred (ValidationException) when calling the ListFlows operation: The request object must be non-null

WORKS
aws appflow list-flows  --profile qaedp --region us-east-2 --max-result 1
{
    "flows": [
        {...

**Comment by stobrien89** [comment] 2021-04-08 18:27
Hi @gtjones73, 

Thanks for the report!  I was able to reproduce— It appears this error extends to other appflow list and describe operations as well.  Taking a further look into this.

**Comment by stobrien89** [comment] 2021-04-08 19:58
Marking this as a bug.  Like the error message says, it looks like a null request object is being sent for list and describe operations when no arguments (pertaining to the service/operation itself) are provided. Tested on another SDK to verify.  

Thanks for pointing this out @gtjones73!

**Comment by stobrien89** [comment] 2021-04-13 20:58
V347232734

**Comment by stobrien89** [comment] 2021-09-20 19:18
The Appflow team has rolled out a fix, which appears to be available in the latest CLI versions.  Closing, but let us know if you have any additional questions!

**Closed by stobrien89** 2021-09-20 19:18 UTC
Labels: bug, service-api, appflow
