### ISSUE TITLE
The latest docker login command don't support -e argument

### ISSUE THREAD

**Issue by Leorowe** [aws/aws-cli#2804] opened 2017-09-01 06:52 UTC
Hi,

My Docker version is 17.06.1-ce, build 874a737.
My aws cli version is aws-cli/1.11.144 Python/2.7.5 Linux/3.10.0-514.el7.x86_64 botocore/1.7.2
Using command  `$(aws ecr get-login) ` to login ECR will fail, because of the -e argument is deprecated.

e.g.:
 $(aws ecr get-login)
output:
unknown shorthand flag: 'e' in -e
See 'docker login --help'.

**Comment by cwgem** [comment] 2017-09-01 12:16
Duplicate of #1926 . Use the `--no-include-email` parameter to avoid this error. I take it that making this the default might be a little weird because scripts that expect the opposite would break.

**Comment by joguSD** [comment] 2017-09-01 16:34
As @cwgem said, you need to add the `--no-include-email` flag. We won't be able to change the default for a while as we need to maintain backwards compatibility.

**Closed by joguSD** 2017-09-01 16:34 UTC
