### ISSUE TITLE
aws cli cp or sync should copy the source metadata without extra params or caveats of multipart upload

### ISSUE THREAD

**Issue by akotranza** [aws/aws-cli#2809] opened 2017-09-03 04:54 UTC
We want nice things. Stop screwing around with wholefoods and give us a decent developer UX.

**Comment by cwgem** [comment] 2017-09-05 15:37
We want nice issues. Stop screwing around with the issue tracker and gives us a decent issue report.

**Comment by JordonPhillips** [comment] 2017-09-05 16:41
Closing as duplicate of #1145

**Closed by JordonPhillips** 2017-09-05 16:41 UTC
Labels: duplicate

**Comment by akotranza** [comment] 2017-09-05 17:12
It is a real issue. AWS CLI cp and sync do not preserve metadata. This is well documented in issues since 2013. Since you guys have no interest in listening to real customer issues (this is what our 100K/yr USD spend on AWS gets us, go figure), I wasted half a day to write a script that syncs and preserves metadata.

Here, maybe someone will find it useful in four years when AWS CLI has still not fixed the original problem

https://gist.github.com/akotranza/51f452f975469e1fa78c2748dd115c87

**Comment by cwgem** [comment] 2017-09-05 19:35
So here's the thing, AWS is a large set of services, what you consider a serious issue is but one of many potential issue they have to work with on a daily basis. When you sign up for any service, not just AWS, you have to deal with a certain amount of tech risk. You have to acknowledge you'll need to deal with work arounds. 

In my daily work experience, I have to at any point work with any part of the AWS ecosystem. Not just EC2, not just S3, not just DynamoDB, but any potential service is up for grabs. In doing so I hit limitations and have to figure out how to deal with them. Sometimes I spend days, sometimes I spend weeks. At the end of the day I still have to deal with this. Azure and Google Cloud would give me similar experiences.

Sure, I could got vent my frustration on the services I use, as a lot more money is involved. Instead here I am under no obligation to do so volunteering my time helping out with `aws-cli` triaging and really any of the projects I work with as time permits. Why? Because it helps move things along. 

Now here I am taking the time, trying to help when I'm under no obligation and now you come along filing an issue with, to be quite blunt, very unjustified behavior, and one that you've clearly stated you know already existed. Now that's less time I get to spend moving things along, actually helping. Reconsider your choices.

Now then off to work on AWS stuff. Good luck on your journey.

**Comment by akotranza** [comment] 2017-09-05 20:25
You clearly have a ton of empathy for developers. Redirecting some of that empathy to customers might aid you in your future career path.

**Comment by cwgem** [comment] 2017-09-05 22:14
I don't consider a customer and a developer two separate things. Been on both sides for better and for worse. Working on both documentation and code I look towards helping both sides. Unfortunately time and prioritization means I can't solve all the problems at once.

Also using your logic, what about other customers? Suddenly the world revolves around your needs and your needs alone? Other customer needs are suddenly out of the way now? Heck I'm an AWS customer as well, and a rather large one at that. If you want to take spend and size into account I have just as much pull if not more than you. Not only that but who do you think a large portion of AWS customers are? Developers.
