### ISSUE TITLE
[v2] aws configure sso should support more parameters

### ISSUE THREAD

**Issue by trondhindenes** [aws/aws-cli#5064] opened 2020-03-14 14:40 UTC
This command currently is very interactive, making it hard to use it efficiently. Even tho the actual credential stuff that happens in the browser must take place there, the rest of the flow can be made substantially more efficient.
`aws configure sso` should take the following optional options:
`--sso-start-url`
`--sso-region`
`--acount-id`
`--role-name`

This would allow me to run `aws configure sso`, complete the browser sign-in, and then be done with, without further prompting/dialogues.

On subsequent logins, some of these are persisted to `~/.aws/config`. We need a way to avoid prompting for these - maybe that should be the default and then a user could override that behavior with another parameter or something.

The goal overall should be to make the `aws configure sso` as painless as possible, as users will run this MANY times to grab updated shortlived credentials. Right now its way too quirky.

**Comment by KaibaLopez** [comment] 2020-03-18 23:25
Hi @trondhindenes ,
So, I'm not completely sold on this idea, we have 2 ways to configure sso profiles, the "interactive" [automatic way](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-auto) with command prompts and the [manual way](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-manual) using the config file.
From the way the issue is explained it sounds like the manual way would be an even more direct and less interactive than what you're describing so in that case I'd suggesting using that.
That being said, am I missing something?

**Comment by trondhindenes** [comment] 2020-03-23 10:39
I think you're missing something. `aws configure sso` does a lot more than just populating a file, it talks to the AWS SSO service to get an updated session credential. It can't be completed simply by editing a config file. It is very different from `aws configure`. 

My proposal is that, on subsequent runs, `aws configure sso` performs no prompts and instead uses values supplied by previous executions (against the same profile)

**Comment by KaibaLopez** [comment] 2020-03-24 20:07
Hi @trondhindenes ,
oh, so are you maybe looking for:
`aws sso login --profile <your-profile-name>`
This command should log you in with the sso profile saved in .aws/config by the configure call, with no extra prompting.

**Comment by trondhindenes** [comment] 2020-03-26 07:51
that is incorrect. `aws sso login --profile <your-profile-name>` prompts for sso start url, sso region (both have defaults from previous session, but still). It also prompts for aws account if the aws sso identity has more than one role in one or more accounts. This is the flow I'd like to be completely prompt-less when possible.

**Comment by KaibaLopez** [comment] 2020-03-27 16:10
That should not be the case, at least I can't reproduce that from my side.
`aws sso login --profile <profile name>` just reads the profile info provided and opens the browser for login shouldn't prompt anthing which is where my confusion comes from, it could be a bug. 
I'll dig a little deeper on this.

**Comment by KaibaLopez** [comment] 2020-03-27 20:27
Alright @trondhindenes ,
I did some more digging and asking around, got a couple things for you:
* First one is good news of sorts, there is already a plan to support the passing of the prompted arguments as command parameters.
* Second, I'm still not sure what's going on with your sso login, it should not prompt anything and sso login should be what you use once the sso profile is configured for easy access... so kind of lost there, does the prompting also happens if you are using a unique profile name? Anything you can tell me about your setup so I can reproduce this behavior?

For now I'll label this as a feature request to bring more visibility.

**Comment by trondhindenes** [comment] 2020-04-02 06:51
hi, you're completely correct. I did not know that `aws configure sso` is only meant to be used for first-time setups. Subsequent logins should use `aws sso login`. That explains it.

**Comment by kdaily** [comment] 2021-02-19 19:34
I'm marking this as a duplicate in favor of #5200 which would do what you want on the initial configuration. Thanks again!

**Closed by kdaily** 2021-02-19 19:34 UTC
Labels: feature-request, sso, v2
