### ISSUE TITLE
aws-cli v2 bash auto_completer does not suggest `--cli-auto-prompt` as an option

### ISSUE THREAD

**Issue by ehammond** [aws/aws-cli#4949] opened 2020-02-12 01:14 UTC
The aws-cli v2 bash completion does not suggest `--cli-auto-prompt` as an option.

```
$ aws dynamodb delete-table --cli-<TAB><TAB>
--cli-connect-timeout  --cli-input-json       --cli-read-timeout

$ aws --version
aws-cli/2.0.0 Python/3.7.3 Linux/5.0.0-37-generic botocore/2.0.0dev4

$ echo $SHELL
/bin/bash
```

**Comment by joguSD** [comment] 2020-02-12 18:24
Confirmed. Marking this as a bug until we can generate a new autocompletion index that includes this.

**Comment by thimslugga** [comment] 2020-02-14 16:09
You can still install the aws-cli v2 with pip by specifying the github repo and v2 branch. I tested this on a a1 instance and it worked fine.

`
sudo su -
yum groupinstall -y "Development Tools"
yum install -y python3 python3-devel libffi-devel

python3 -m venv /opt/aws-cliv2/env --prompt aws-cliv2
source /opt/aws-cliv2/env/bin/activate

pip install git+https://github.com/boto/botocore.git@v2 --upgrade
pip install git+https://github.com/aws/aws-cli.git@v2 --upgrade

deactivate

test -f /usr/local/bin/aws && ln -s /opt/aws-cliv2/env/bin/aws /usr/local/bin/aws
test -f /usr/local/bin/aws_bash_completer && ln -s /opt/aws-cliv2/env/bin/aws_bash_completer /usr/local/bin/aws_bash_completer

aws --version
 aws-cli/2.0.0 Python/3.7.4 Linux/4.14.165-131.185.amzn2.aarch64 botocore/2.0.0dev4
`

**Comment by stealthycoin** [comment] 2020-02-27 22:57
Looks like this has been resolved

```
➜  aws dynamodb delete-table --cli-<TAB><TAB>
--cli-auto-prompt      --cli-binary-format    --cli-connect-timeout  --cli-input-json       --cli-input-yaml       --cli-read-timeout
```

**Closed by stealthycoin** 2020-02-27 22:57 UTC
Labels: bug, v2
