### ISSUE TITLE
Copying between S3 regions throws signature error on specific filename

### ISSUE THREAD

**Issue by mikeedw** [aws/aws-cli#1671] opened 2015-12-08 12:33 UTC
`aws-cli/1.9.11 Python/2.7.10 Linux/4.1.10-17.31.amzn1.x86_64 botocore/1.3.11`

Steps to reproduce:

Create bucket1 in eu-west-1
Create bucket2 in eu-central-1
Create a file in bucket1 called "#test  test" (note there are 2 spaces in the middle)

`aws s3 cp "s3://bucket1/#test  test" s3://bucket2/ --region eu-central-1 --source-region eu-west-1`

This results in the following error:

`A client error (SignatureDoesNotMatch) occurred when calling the CopyObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method`

If you remove the "#" and/or the extra space the command works.

I tried setting the default S3 signature version in the config but this had no effect.

**Comment by kyleknap** [comment] 2015-12-08 18:42
I can confirm. This looks like an issue with our signature version 4 signer. Specifically, something is probably going wrong with the signing of the ``x-amz-copy-source`` header where we are not properly handling the ``#`` or the spaces correctly.

**Comment by jamesls** [comment] 2016-02-27 00:51
Closing out issue, this is now fixed as of the latest version of the CLI:

```
$ aws s3 cp 's3://source-bucket/issue1671/#test  test' s3://dest-eu-central-1/ --region eu-central-1 --source-region us-west-2
copy: s3://source-bucket/issue1671/#test  test to s3://dest-eu-central-1/#test  test
```

**Closed by jamesls** 2016-02-27 00:51 UTC
Labels: bug, confirmed, sigv4
