### ISSUE TITLE
Post install: Cannot open PyInstaller archive from executable (/usr/local/aws-cli/v2/2.7.35/dist/aws) 

### ISSUE THREAD

**Issue by jauyzed** [aws/aws-cli#7314] opened 2022-09-30 19:00 UTC
### Describe the bug

The install however was successful but after cli was installed on RHEL8 machine. 

```
$ aws --version
[9441] Cannot open PyInstaller archive from executable (/usr/local/aws-cli/v2/2.7.35/dist/aws) or external archive (/usr/local/aws-cli/v2/2.7.35/dist/aws.pkg)
```

### Expected Behavior

$ aws --version to spit out the version of aws cli

### Current Behavior

```
$ aws --version
[9441] Cannot open PyInstaller archive from executable (/usr/local/aws-cli/v2/2.7.35/dist/aws) or external archive (/usr/local/aws-cli/v2/2.7.35/dist/aws.pkg)


$  which python3
/usr/bin/python3

$ pip install pyinstaller
Requirement already satisfied: pyinstaller in ./.local/lib/python3.6/site-packages (4.10)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in ./.local/lib/python3.6/site-packages (from pyinstaller) (2022.0)
Requirement already satisfied: importlib-metadata in ./.local/lib/python3.6/site-packages (from pyinstaller) (4.8.3)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from pyinstaller) (39.2.0)
Requirement already satisfied: altgraph in ./.local/lib/python3.6/site-packages (from pyinstaller) (0.17.3)
Requirement already satisfied: typing-extensions>=3.6.4 in ./.local/lib/python3.6/site-packages (from importlib-metadata->pyinstaller) (4.1.1)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.6/site-packages (from importlib-metadata->pyinstaller) (3.6.0)
```

### Reproduction Steps

Followed the uninstall guide to remove aws cli: https://docs.aws.amazon.com/cli/latest/userguide/uninstall.html

Then installed it

### CLI version used

2.7.35

### Environment details (OS name and version, etc.)

RHEL8: 4.18.0-372.26.1.el8_6.x86_64

**Comment by tim-finnigan** [comment] 2022-09-30 23:45
Hi @jauyzed thanks for reaching out. We tried to reproduce this issue a RHEL8 EC2 instance but weren't able to. (There was another recent issue related to pyinstaller that just came in as well, not sure if these are related: https://github.com/aws/aws-cli/issues/7318.) Were you able to install previous versions such as [2.7.29](https://github.com/aws/aws-cli/blob/804a179e9edd49031711f81ef339e7690e9e9c75/CHANGELOG.rst#L121) before PyInstaller was upgraded to 5.3? And did you have PyInstaller installed previously in your environment before installing the AWS CLI v2?

**Comment by jauyzed** [comment] 2022-10-03 18:49
@tim-finnigan I'm not particularly sure if a previous version pyinstaller was installed or not but I was trying to upgrade from 2.6.x which was working normally and I was suggested to follow the uninstall document to install/upgrade the new version. The aws cli install however was successful but I keep getting the same error with broken aws cli.

**Comment by jauyzed** [comment] 2022-10-04 22:03
I have a issue with pyinstaller provider: https://github.com/pyinstaller/pyinstaller/issues/7130

**Comment by jauyzed** [comment] 2022-10-04 23:26
Not sure why the ownership of this: /usr/local/aws-cli/v2/2.8.0/dist/and its subdirectories were all set to root. Moreover the pyinstaller error was rather misleading and didnt mention anything about permissions. 

Setting all the files/directories to a non-root user resolved the issue

**Comment by tim-finnigan** [comment] 2022-10-06 23:24
Hi @jauyzed I've been tracking the corresponding internal ticket for this and it sounds like it was confirmed as a permissions issue with root. Please let us know if there's anything you want to add or clarify regarding that, otherwise feel free to close this issue if you think it is resolved.

**Comment by jauyzed** [comment] 2022-10-07 19:40
Hello @tim-finnigan I had to add read permissions to dist level directories under `/usr/local/aws-cli/v2/2.8.0/`
So basically ran: `root$ chmod -R 755 dist`

**Comment by tim-finnigan** [comment] 2022-10-07 22:57
Thanks for following up and noting the solution! Since that resolves the issue I'll go ahead and close this. If you had any other feedback or questions please let us know.

**Closed by tim-finnigan** 2022-10-07 22:57 UTC
Labels: bug, response-requested, installation, pyinstaller
