### ISSUE TITLE
[v2] Source build doesn't work on Windows

### ISSUE THREAD

**Issue by kellertk** [aws/aws-cli#7037] opened 2022-06-14 20:10 UTC
### Describe the bug

Building from source doesn't work on Windows. There are 2 dependency issues: PyInstaller <4.4 doesn't properly work on case insensitive filesystems, and ruamel < 0.16.0 seems to have problems building a C-native extension even though the platform doesn't support it.

### Expected Behavior

Build works.

### Current Behavior

Build no works.

### Reproduction Steps

1) Install a fresh Python 3.10 on windows
2) Try to do a source build of v2
3) fail

### Possible Solution

The issues seem to be fixed in ruamel 0.16.0 and PyInstaller 4.4. A quick update to setup.cfg and requirements-build.txt fixes this.

### CLI version used

Source

### Environment details (OS name and version, etc.)

Python 3.10, Windows 10

**Comment by kdaily** [comment] 2022-06-17 21:46
Hi @kellertk,

Thanks for the post. We're tracking this here, as support for Python 3.10 is not available yet:

https://github.com/aws/aws-cli/issues/7004

There are a number of open PRs that we're still testing out, including updating the pin for `ruamel.yaml`:

https://github.com/aws/aws-cli/pull/6995

While your request is specific to the source distribution, adding official support for Python 3.10 will solve this as well. Marking this as a duplicate of #7004, but noting the need to update PyInstaller as well! Thanks.

**Closed by kdaily** 2022-06-17 21:46 UTC
Labels: duplicate, feature-request

**Comment by kdaily** [comment] 2022-06-17 21:48
Another thing to note about `ruamel.yaml` is the C library supporting it was moved to a separate package (`ruamel.yaml.clib`) in the 0.16 update. In our tests, this posed issues in Windows environments that were previously only pulling source distributions, which then required a C compiler to install. If you can continue to get wheels, then this still works ok!
