### ISSUE TITLE
Tag latest GitHub Releases with latest.

### ISSUE THREAD

**Issue by pratikpc** [aws/aws-cli#5957] opened 2021-02-19 17:35 UTC
**Describe the solution you'd like**
The latest GitHub Release should be tagged with latest like [AWS SAM CLI](https://github.com/aws/aws-sam-cli)

Advantages:-

![image](https://user-images.githubusercontent.com/28534575/108540005-b21a5400-7306-11eb-8f76-68b9ca165e5a.png)
Looks nicer

**Comment by kdaily** [comment] 2021-02-19 18:07
Thanks for the request, and I agree! It requires a change to our release process. 

This is a duplicate of #5471, closing. Please add your comments there.

**Closed by kdaily** 2021-02-19 18:07 UTC
Labels: duplicate, feature-request
