### ISSUE TITLE
Invalid length for parameter when running aws iam create-access-key  --generate-cli-skeleton output

### ISSUE THREAD

**Issue by SergeyDo** [aws/aws-cli#2338] opened 2016-12-21 18:56 UTC
Hello everyone, 

When Im running 
```
aws iam create-access-key  --generate-cli-skeleton output
```

Im getting error:
```
2016-12-21 18:50:27,901 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 197, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 333, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 482, in __call__
    parsed_globals=parsed_globals
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 579, in _emit_first_non_none_response
    name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 687, in emit_first_non_none_response
    responses = self._events.emit(event_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/generatecliskeleton.py", line 100, in generate_json_skeleton
    parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 622, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/generatecliskeleton.py", line 134, in _make_client_call
    stubber.add_response(method_name, fake_response)
  File "/usr/local/lib/python2.7/dist-packages/botocore/stub.py", line 227, in add_response
    self._add_response(method, service_response, expected_params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/stub.py", line 241, in _add_response
    self._validate_response(operation_name, service_response)
  File "/usr/local/lib/python2.7/dist-packages/botocore/stub.py", line 370, in _validate_response
    validate_parameters(response, output_shape)
  File "/usr/local/lib/python2.7/dist-packages/botocore/validate.py", line 47, in validate_parameters
    if report.has_errors():
ParamValidationError: Parameter validation failed:
Invalid length for parameter AccessKey.AccessKeyId, value: 11, valid range: 16-inf
2016-12-21 18:50:27,902 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

I believe this is happening because `AccessKey` has min size of 16 characters https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/service-2.json#L6020  
But `AccessKeyId`  is only 11 characters.

```
ipdb> n
> /usr/local/lib/python2.7/dist-packages/botocore/validate.py(47)validate_parameters()
     45     import ipdb; ipdb.set_trace()
     46     report = validator.validate(params, shape)
---> 47     if report.has_errors():
     48         raise ParamValidationError(report=report.generate_report())
     49

ipdb> p params
OrderedDict([(u'AccessKey', OrderedDict([(u'UserName', u'UserName'), (u'AccessKeyId', u'AccessKeyId'), (u'Status', u'Status'), (u'SecretAccessKey', u'SecretAccessKey'), (u'CreateDate', datetime.datetime(1970, 1, 1, 0, 0))]))])
```

**Comment by jamesls** [comment] 2016-12-22 00:53
Yep, seeing that as well.  Dupe of: https://github.com/aws/aws-cli/issues/2337

**Closed by jamesls** 2016-12-22 00:53 UTC
