### ISSUE TITLE
aws wellarchitected list-milestones fails with validation error

### ISSUE THREAD

**Issue by yossi2cohen** [aws/aws-cli#5858] opened 2021-01-09 19:28 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
The wellarchitected service fails on attempt to list all milestones (for a workload, which has two saved milestones).
It generates this error message:
"An error occurred (ValidationException) when calling the ListMilestones operation: [Validation] [Unknown error parsing request body]"

**SDK version number**
aws-cli/2.1.17 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

**Platform/OS/Hardware/Device**
What are you running the cli on?
aws-cli/2.1.17 Python/3.7.9 Windows/10 exe/AMD64 prompt/off
**To Reproduce (observed behavior)**
Steps to reproduce the behavior
1. Create a workload in AWS Well-Architected-Tool with all LENS included
2. answer a few questions and save-and-exit
3. save a milestone
4. Type in the following CLI command:
aws wellarchitected list-milestones --workload-id <your-workload-id>

**Expected behavior**
returns a list of milestones for the specified workload in json format as defined in here:
https://docs.aws.amazon.com/cli/latest/reference/wellarchitected/list-milestones.html

**Logs/output**
contains sensitive information.

**Additional context**

**Comment by kdaily** [comment] 2021-01-12 21:42
Hi @yossi2cohen, I can reproduce. Relevant logs that show request and response. Request body is empty:

```
2021-01-12 10:03:26,489 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListMilestones) with params: {'url_path': '/workloads/ZZZZZZZZ/milestonesSummaries', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'aws-cli/2.1.17 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off command/wellarchitected.list-milestones'}, 'body': b'', 'url': 'https://wellarchitected.us-west-2.amazonaws.com/workloads/ZZZZZZZZ/milestonesSummaries', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7fd6cfe2b210>, 'has_streaming_input': False, 'auth_type': None}}
```

Response:

```
2021-01-12 10:03:26,490 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://wellarchitected.us-west-2.amazonaws.com/workloads/ZZZZZZZZ/milestonesSummaries, headers={'User-Agent': b'aws-cli/2.1.17 Python/3.7.4 Darwin/19.6.0 exe/x86_64 prompt/off command/wellarchitected.list-milestones', 'X-Amz-Date': b'20210112T180326Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AKIA1234567890/20210112/us-west-2/wellarchitected/aws4_request, SignedHeaders=host;x-amz-date, Signature=0066af0560d65dcaf764e5b64a0eb6781279fbb4ec8088c3c52fe5f2caa007bc', 'Content-Length': '0'}>
2021-01-12 10:03:26,491 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): wellarchitected.us-west-2.amazonaws.com:443
2021-01-12 10:03:26,650 - MainThread - urllib3.connectionpool - DEBUG - https://wellarchitected.us-west-2.amazonaws.com:443 "POST /workloads/ZZZZZZZZ/milestonesSummaries HTTP/1.1" 400 64
2021-01-12 10:03:26,651 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Tue, 12 Jan 2021 18:03:26 GMT', 'Content-Type': 'application/json', 'Content-Length': '64', 'Connection': 'keep-alive', 'x-amzn-RequestId': 'ef7d6280-5816-4c06-b85f-68e80e25207d', 'x-amzn-ErrorType': 'ValidationException', 'x-amz-apigw-id': 'ZDChSHxfPHcFbIA=', 'X-Amzn-Trace-Id': 'Root=1-5ffde46e-183b135c4440ea4646c2980a'}
2021-01-12 10:03:26,651 - MainThread - botocore.parsers - DEBUG - Response body:
b'{"Message": "[Validation] [Unknown error parsing request body]"}'
```

**Comment by kdaily** [comment] 2021-01-12 21:50
@yossi2cohen, the issue is the range specified for `MaxResults` is 1-50. If it is left unspecified in the CLI, 0 is sent. A workaround now is to set a `MaxResults` value. I will raise this with the service team to address.

**Comment by kdaily** [comment] 2021-02-15 18:02
Hi @yossi2cohen, this should be addressed with a recent version of the AWS CLI. Can you confirm for me?

**Comment by stobrien89** [comment] 2021-04-01 19:35
Closing, as this has been addressed in a recent CLI version.

**Closed by stobrien89** 2021-04-01 19:35 UTC
Labels: bug, closing-soon, response-requested, service-api, wellarchitected
