### ISSUE TITLE
put-metric-data may hang

### ISSUE THREAD

**Issue by random930** [aws/aws-cli#4875] opened 2020-01-24 19:38 UTC
I'm running an EC2 Instance of Ubuntu:
`Linux ip-172-16-7-143 4.15.0-1057-aws #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

I have a cron tab reports two customer metrics every minute:
`/snap/bin/aws cloudwatch put-metric-data --metric-name chunk-count --dimensions Instance=i-094d6037d48328910 --namespace "Custom" --value $(ls -latr /home/ubuntu/streamdelayer/chunks | wc -l)
OLDEST_FILE=$(find /home/ubuntu/streamdelayer/chunks -type f -printf '%C@+ \n' | sort -n | head -n 1 | sed 's/\..*//')
AGE_OF_OLDEST_FILE=$(($(date +%s) - OLDEST_FILE))
/snap/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace "Custom" --value $AGE_OF_OLDEST_FILE`

A few hours into doing this, all of the aws CLI calls begin to hang:
`root       813  0.0  0.2  31748  2940 ?        Ss   15:03   0:00 /usr/sbin/cron -f
root     20136  0.0  0.3  59232  3300 ?        S    19:10   0:00  \_ /usr/sbin/CRON -f
ubuntu   20137  0.0  0.0   4628   860 ?        Ss   19:10   0:00  |   \_ /bin/sh -c . $HOME/.profile; /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh >> /home/ubuntu/streamdelayer/report.log 2>&1
ubuntu   20138  0.0  0.0   4628   772 ?        S    19:10   0:00  |       \_ /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh
ubuntu   20727  3.1  4.2 108084 42556 ?        R    19:19   0:15  |           \_ /snap/aws-cli/151/usr/bin/python3 /snap/aws-cli/151/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace Custom --value 63582
root     20197  0.0  0.3  59232  3300 ?        S    19:11   0:00  \_ /usr/sbin/CRON -f
ubuntu   20198  0.0  0.0   4628   856 ?        Ss   19:11   0:00  |   \_ /bin/sh -c . $HOME/.profile; /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh >> /home/ubuntu/streamdelayer/report.log 2>&1
ubuntu   20199  0.0  0.0   4628   820 ?        S    19:11   0:00  |       \_ /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh
ubuntu   20780  3.2  3.5  95668 35528 ?        R    19:20   0:14  |           \_ /snap/aws-cli/151/usr/bin/python3 /snap/aws-cli/151/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace Custom --value 63639
root     20249  0.0  0.3  59232  3300 ?        S    19:12   0:00  \_ /usr/sbin/CRON -f
ubuntu   20250  0.0  0.0   4628   856 ?        Ss   19:12   0:00  |   \_ /bin/sh -c . $HOME/.profile; /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh >> /home/ubuntu/streamdelayer/report.log 2>&1
ubuntu   20251  0.0  0.0   4628   816 ?        S    19:12   0:00  |       \_ /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh
ubuntu   20846  3.2  3.2  92292 32304 ?        R    19:22   0:12  |           \_ /snap/aws-cli/151/usr/bin/python3 /snap/aws-cli/151/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace Custom --value 63705
root     20302  0.0  0.3  59232  3300 ?        S    19:13   0:00  \_ /usr/sbin/CRON -f
ubuntu   20303  0.0  0.0   4628   768 ?        Ss   19:13   0:00  |   \_ /bin/sh -c . $HOME/.profile; /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh >> /home/ubuntu/streamdelayer/report.log 2>&1
ubuntu   20304  0.0  0.0   4628   816 ?        S    19:13   0:00  |       \_ /bin/sh /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh
ubuntu   20892  3.2  2.9  88084 30112 ?        R    19:22   0:11  |           \_ /snap/aws-cli/151/usr/bin/python3 /snap/aws-cli/151/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace Custom --value 63733`

Even an AWS version call hangs and I need to CTRL-C it:
`aws --version
^CTraceback (most recent call last):
  File "/snap/aws-cli/151/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/snap/aws-cli/151/lib/python3.5/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/snap/aws-cli/151/lib/python3.5/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/snap/aws-cli/151/lib/python3.5/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/snap/aws-cli/151/lib/python3.5/site-packages/botocore/compat.py", line 26, in <module>
    from urllib3 import exceptions
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/connection.py", line 40, in <module>
    from .util.ssl_ import (
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/util/__init__.py", line 7, in <module>
    from .ssl_ import (
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 10, in <module>
    from .url import IPV4_RE, BRACELESS_IPV6_ADDRZ_RE
  File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/util/url.py", line 71, in <module>
    SUBAUTHORITY_RE = re.compile(SUBAUTHORITY_PAT, re.UNICODE | re.DOTALL)
  File "/snap/aws-cli/151/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 540, in compile
    code = _code(p, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 525, in _code
    _compile(code, p.data, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 144, in _compile
    _compile(code, av[1], flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 185, in _compile
    _compile(code, av, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 144, in _compile
    _compile(code, av[1], flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 185, in _compile
    _compile(code, av, flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 133, in _compile
    _compile(code, av[2], flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 144, in _compile
    _compile(code, av[1], flags)
  File "/snap/aws-cli/151/usr/lib/python3.5/sre_compile.py", line 78, in _compile
    for op, av in pattern:
KeyboardInterrupt`

Only way around this I currently have is restarting the system. This system is managed by SSM

**Comment by klaytaybai** [comment] 2020-01-29 00:02
Is this a frequently occurring problem for you?  Are you able to share some code samples from your cron scripts?

**Comment by random930** [comment] 2020-01-29 14:49
Yes, every time I turn this on, within hours it starts happening.

This is the code:
`# cat /home/ubuntu/streamdelayer/report_cloudwatch_metrics.sh`

`/snap/bin/aws cloudwatch put-metric-data --metric-name chunk-count --dimensions Instance=i-094d6037d48328910 --namespace "Custom" --value $(ls -latr /home/ubuntu/streamdelayer/chunks | wc -l)`

`OLDEST_FILE=$(find /home/ubuntu/streamdelayer/chunks -type f -printf '%C@+ \n' | sort -n | head -n 1 | sed 's/\..*//')`

`AGE_OF_OLDEST_FILE=$(($(date +%s) - OLDEST_FILE))`

`/snap/bin/aws cloudwatch put-metric-data --metric-name oldest-chunk-age --dimensions Instance=i-094d6037d48328910 --namespace "Custom" --value $AGE_OF_OLDEST_FILE
`

Keep in mind the instance is a t2.micro in EC2. I don't know if that has something to do with it.

**Comment by joguSD** [comment] 2020-02-11 21:47
Hm. I'm pretty stumped as to why this would be hanging. For what it's worth it seems to be hanging at import time so the CLI isn't even running yet.

```
File "/snap/aws-cli/151/lib/python3.5/site-packages/urllib3/util/url.py", line 71, in <module> SUBAUTHORITY_RE = re.compile(SUBAUTHORITY_PAT, re.UNICODE | re.DOTALL)
```
Happens during the initial import resolution. The other thing I noticed is this is a snap of the CLI? We don't actually maintain or distribute that and I don't know if something about the snap version of this might be causing issues that would cause this to hang

**Comment by random930** [comment] 2020-02-12 14:22
So is there something I could do to provide more information, or are you
thinking it's unrelated to the AWS CLI?

**Comment by stealthycoin** [comment] 2020-02-24 20:49
We would need to know the installation method to be able to provide any further assistance. As it looks like something messed up in your environment (since its hanging at import time the CLI hasn't started yet). If you're using a snap those aren't supported so we would recommend you use a supported installation method.

**Comment by random930** [comment] 2020-02-26 02:43
Ok, I uninstalled the snap and used the exact method from the AWS
documentation. Issue is still happening. I verified that if I turn off the
cron these issues don't happen. Is it possible the AWS CLI uses too many
CPU credits?

**Comment by kdaily** [comment] 2020-08-05 22:58
Hi @random930,

Is this still occurring for you?

One thing that might help us is to rule out the interaction with the other sub-commands that you are running to get the metrics. Can you run in your environment and set constant values (or, as I did below, use the `RANDOM` environment variable) instead of actually computing them?

I'm attempting to reproduce. I'll report back once it's been running for a while, here's what I'm doing also on a `t2.micro` EC2 with Ubuntu 16.04:

```terminal
$aws --version
aws-cli/1.18.113 Python/3.8.5 Linux/4.4.0-1105-aws botocore/1.17.36
$ cat test-cron.sh
#!/usr/bin/env bash
aws cloudwatch put-metric-data --namespace "mynamespace" --metric-name $1 --value $(($RANDOM%100))
```

My `crontab` to run every minute:

```terminal
* * * * * /home/ubuntu/./test-cron.sh FirstMetric >> /tmp/cron.log 2>&1
* * * * * /home/ubuntu/./test-cron.sh SecondMetric >> /tmp/cron.log 2>&1
```

**Comment by random930** [comment] 2020-08-06 00:20
Hi Kenneth,

I've since spun down that EC2 and moved all of the element of my app into
containers running on ECS FARGATE. The commands for generating the values
were very light so I don't think they are the cause.

What could be the cause was that somehow I was using too much CPU and ran
out of credits, causing the underlying AWS infrastructure to limit the CPU
cycles on the machine. The odd part is that without this cron, I had no
issues. So I don't know if aws-cli was using up CPU, or something else was
going on.

Let your machine run for a few days and you should see this beginning to
happen.

**Comment by kdaily** [comment] 2020-09-25 21:21
I left this running for quite a while and didn't encounter this happening. I'm going to close it for now. If it reoccurs, please let us know with a new issue and link to this one. Thanks!

**Closed by kdaily** 2020-09-25 21:21 UTC
Labels: guidance
