### ISSUE TITLE
aws s3 cp silently fails when destination doesn't exist

### ISSUE THREAD

**Issue by mtopolski** [aws/aws-cli#3659] opened 2018-10-17 02:55 UTC
Made the derp of muscle memory-ing a command I use on a different machine. If the target destination of an s3 cp is specified in a nonexistent directory, you get a silent failure. Not sure if this is intended to punish me for the 30 seconds it took to realize I was on a different box with different dirs, but it would have been nice to have been told off by the cli.

(on Mac OS High Sierra)

**Comment by mtopolski** [comment] 2018-11-07 17:52
Thank *you* for reaching out, no worries. I experienced this specifically on Mac OS High Sierra, I haven't tried it with Mojave yet and I'm on Debian now where I get a nice little error.
```aws s3 cp s3://my.stuff.com/file.tar.zstd /nonexistantpath```

**Comment by justnance** [comment] 2018-11-28 09:13
@mtopolski - Thanks for your feedback.  The error returning appears to be expected behavior from the service which the CLI does not control however I can not reproduce the same results to confirm this.  Please rerun the command but a add the `--debug` option at the end followed by posting a sanatize output.  I would like to analyze the CLI version in use, the actual command that is getting passed, and the output in the response body.

**Comment by shabeebk** [comment] 2018-12-08 12:51
@mtopolski @justnance 
I have tried a similar action with the two versions and found this to be working. CLI automatically creates a local folder which was not existing and then copy the file to that location.

Version verified:

shabeeb@Shabeeb-LT:~/workspace/repos/aws-cli$ uname -a
Linux Shabeeb-LT 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
shabeeb@Shabeeb-LT:~/workspace/repos/aws-cli$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
shabeeb@Shabeeb-LT:~/workspace/repos/aws-cli$ aws --version
aws-cli/1.14.44 Python/3.6.7 Linux/4.15.0-42-generic botocore/1.8.48

ubuntu@XXXXXX:~$ uname -a
Linux oscar 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@XXXXXX:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
ubuntu@XXXXXX:~$ aws --version
aws-cli/1.11.170 Python/2.7.6 Linux/3.13.0-119-generic botocore/1.8.13

**However, aws cli failed to print a failure message if it tries to copy the file to a path which is not existing and not owned by the user. Specifically, cli is unable to create the path due to permission issue, but did not print that as a message**

Try the command with sudo, it works and does what did it do in the folder owned by the user.

What needs to be fixed is _print a message if cli fails to cp a file to a folder due to permission issue_

**Comment by shabeebk** [comment] 2018-12-08 13:02
@mtopolski @justnance Please let me know if I can help with implementing this.

**Comment by shabeebk** [comment] 2018-12-14 05:59
@justnance Can you re-open this issue, this looks like a fair one and I have supplied some more information above as I am also facing the same issue.

**Comment by justnance** [comment] 2018-12-27 16:35
@shabeebk - Thanks for your feedback.  I am reopening this issue pending further review and investigation.

**Comment by yigal-weinstein** [comment] 2020-12-15 03:02
Either there was a regression, or this issue was never fixed in AWS CLI 2:

`ubuntu@node1:~$ aws s3 cp s3://<path/toexisting/s3/object> /local_nonexistant_path
download: s3://<path/toexisting/s3/object> to ../local_nonexistant_path
ubuntu@node1:~$ aws --version
aws-cli/2.0.48 Python/3.7.3 Linux/5.4.0-1032-aws docker/x86_64.amzn.2`

file isn't copied to non-existent directory nor are there error messages.

**Comment by debu99** [comment] 2021-08-13 07:12
be careful when you use aws cp in script, when the file is reading from the list and there is extra '\r' or '\n', this issue will get you very confused, as there is no error and you can run the aws cp in command line successfully

**Comment by kdaily** [comment] 2021-08-13 20:15
Looking into this again.

**Comment by kdaily** [comment] 2021-08-13 20:20
@yigal-weinstein and @debu99, I cannot reproduce. If I download a file using the AWS CLI v2 to a path that does not exist, the path is created and the file is copied there. I tested on a Mac:

```
> aws --version
aws-cli/2.2.28 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
```

If this is still an issue for you, please open up a [new bug report](https://github.com/aws/aws-cli/issues/new?assignees=&labels=needs-triage&template=---bug-report.md&title=) using the template and provide the required details and I'll look into it further. Thank you!

**Closed by kdaily** 2021-08-13 20:20 UTC
Labels: bug, s3, needs-review
