### ISSUE TITLE
aws ecr get-login -e flag deprecated

### ISSUE THREAD

**Issue by max3-05** [aws/aws-cli#2732] opened 2017-07-27 16:56 UTC
According to the Docker changeset:

> `-e` and `--email` flags on docker login
> 
> Deprecated In Release: v1.11.0
> Removed In Release: v17.06
> 
> The docker login command is removing the ability to automatically register for an account with the target registry if the given username doesn’t exist. Due to this change, the email flag is no longer required, and will be deprecated.

Please, reflect this changes and remove obsolete `-e` flag from the output of `aws ecr get-login` command

**Comment by JordonPhillips** [comment] 2017-07-27 22:54
You can remove that by specifying the `--no-include-email` flag. We default to including the email so we don't break customers still relying on it.

Duplicate of #2694, #2691, #2676, and a few others

**Closed by JordonPhillips** 2017-07-27 22:54 UTC
Labels: duplicate
