### ISSUE TITLE
Sync missing files

### ISSUE THREAD

**Issue by smxdevst** [aws/aws-cli#3957] opened 2019-02-20 19:23 UTC
Server: `EC2 linux`
Version: `aws-cli/1.16.108 Python/2.7.15 Linux/4.9.62-21.56.amzn1.x86_64 botocore/1.12.98`

After `aws s3 sync` running over 270T of data I lost few GB of files. Sync didn't copy files with special characters at all.

Example of file `/data/company/storage/projects/1013815/3.Company Estimates B. Estimates`

Had to use `cp -R -n`

**Comment by mattjurek** [comment] 2019-02-21 00:51
Please be sure to include debug output from the AWS CLI on such copies so we can see what happened. Add --debug to your command to copy that file.

**Comment by justnance** [comment] 2019-02-21 08:25
@smxdevst - Thank you for reporting this behavior.  It also appears you posted the same feedback on #3273.  I'm not sure yet if this new issue is a duplicate of #3273 yet.  Having the output from the --debug option would help us understand the problem better.  Maybe you can run a test on only one file with special characters using the --debug to avoid running it on several GB of files.  

Also, can you please provide the output after running `locale`? This is what mine looks like:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

Sometimes setting setting the `LC_CTYPE` to `en_US=UTF-8` can help resolve this problem.  Either way I'd like to rule out the problem is related to a locale configuration.

**Comment by hholst80** [comment] 2019-02-22 09:13
How hard can it be to make a mockup data set that mimics this issue? \

If you use python 3 instead, does it work?
```
aws-cli/1.16.104 Python/3.7.2 Linux/4.20.8-arch1-1-ARCH botocore/1.12.94
```

aws s3 sync is not to be trusted for anything important.

**Comment by pingram3030** [comment] 2019-08-01 05:17
related open ticket #3273

**Comment by stobrien89** [comment] 2021-03-30 00:15
Closing, as this is a duplicate of #3273.

**Closed by stobrien89** 2021-03-30 00:15 UTC
Labels: automation-exempt, needs-reproduction, s3sync
