### ISSUE TITLE
ssm send-command --document-name AWS-RunPowerShellScript fails because it won't let me quote files with space

### ISSUE THREAD

**Issue by aw-huit** [aws/aws-cli#5080] opened 2020-03-25 20:12 UTC
```
aws ssm send-command --instance-ids i-066c5683b4e48ac46 --document-name AWS-RunPowerShellScript --parameters commands=["dir 'c:\program files'"]

Error parsing parameter '--parameters': Expected: ',', received: ''' for input:
commands=[dir 'c:\program files']
              ^
```

removing the single quotes around c:\program files results in:

```
"StandardErrorContent": "dir : Cannot find path 'C:\\program' because it does not exist.\r\nAt C:\\ProgramData\\Amazon\\SSM\\InstanceData\\i-066c5683b4e48ac46\\document\\orchestr\r\nation\\9d302c7b-90f6-43d5-a484-cc18de17e4d1\\awsrunPowerShellScript\\0.awsrunPower\r\nShellScript\\_script.ps1:1 char:1\r\n+ dir c:\\program files\r\n+ ~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (C:\\program:String) [Get-ChildIt \r\n   em], ItemNotFoundException\r\n    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCh \r\n   ildItemCommand\r\n \r\n",
```

**Comment by aw-huit** [comment] 2020-03-25 20:58
```
$ aws --version
aws-cli/1.18.29 Python/2.7.16 Linux/4.4.5-15.26.amzn1.x86_64 botocore/1.15.29
```

**Comment by KaibaLopez** [comment] 2020-03-25 22:27
Hi @aw-huit ,
there's a couple ways to get around the space in path for windows command line:
`commands=[dir C:\"program files"]`
Or, on windows command line run this command `dir /X ~1 c:\` that should give you some aliases to use, for Program files for example it'd give you PROGRA~1 which you could then use like:
`commands=[dir C:\PROGRA~1]`
Let me know if these worked for you.

**Comment by aw-huit** [comment] 2020-03-26 12:31
I don't believe that's a good workaround since ~1 can be anything and it gets reused.  You can make "test 1" and "test 2", so ~1 is "test 1", but then you remove "test 1" and mkdir "test 12", now "test 12" is ~1.

Powershell allows quoting of file names so I can't see why it should not be allowed when invoking a command using SSM.

**Comment by KaibaLopez** [comment] 2020-03-26 22:26
@aw-huit ,
Yea, using an alias may not be the best solution all the time as you mention, I was just listing the different options available. 
That being said, while I'm able to reproduce the error with the single quotes, which btw happens because --parameters supports other syntaxis options so using them makes it ambiguous, removing them works just fine for me on V2, is it possible for you to upgrade?

**Comment by aw-huit** [comment] 2020-03-27 14:53
Yes I think I can upgrade.  Is there an official end of life date for V1?

**Comment by KaibaLopez** [comment] 2020-03-27 20:20
Hi @aw-huit ,
I asked around and I'm sorry to say I don't have great news for you, the issue is related to windows string escaping rules; before boto even sees the command the quotes get stripped and so it ends up looking like a list with two elements which causes the error, basically the command has to go through powershell's parsing twice...

Try:
`commands=[""dir ''c:\program files''""]`
 and let me know if this works, otherwise I need to go back to investigating this.

**Comment by aw-huit** [comment] 2020-03-31 17:16
```
$ aws --version
aws-cli/2.0.5 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev9
$ aws  ssm send-command --instance-ids i-066c5683b4e48ac46 --document-name AWS-RunPowerShellScript --parameters commands=[""dir ''c:\program files''""]
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: files], c:program
```

**Comment by ram7348** [comment] 2020-12-03 18:01
I have the same error: Error parsing parameter '--parameters': Expected: ',', received: ''' for input:
I'm trying to use a command like 
aws ssm send-command \
                      --document-name \"AWS-RunShellScript\" \
                      --parameters commands=[\"sudo -u myuser -c \"/softs/git/myrepo/list.sh ${dirName}\"\"]
Can anyone help in resolving this?

**Comment by stobrien89** [comment] 2021-03-26 20:23
In case anyone is still curious— we're working on a few docs improvements related to updating examples  and have found some inconsistent behavior with regard to string escaping in Powershell (and CMD to a certain extent). 

For this scenario, if you're using PS to execute the command, you could try something like this (from OP example):

` --parameters commands='[\"dir c:\program files\"]'`

Or: 

``--parameters commands="[`"dir c:\program files`"]"``

Full disclosure: I have not fully tested this with a running instance, but it appears escaping the quotes for the commands themselves and enclosing the value in quotes deals with the malformed parameter.  Hopefully this gets things moving in the right direction.

**Comment by stobrien89** [comment] 2021-05-25 21:46
Closing, as our [documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-parameters-quoting-strings.html#powershell) has been updated to reflect the variance in Powershell string escaping behavior.

**Closed by stobrien89** 2021-05-25 21:46 UTC
Labels: documentation, windows

**Comment by GaTechThomas** [comment] 2022-07-06 12:45
Posting here in the hope that it saves someone else some pains...

I fought this issue for days in trying to send a command using Azure Pipelines yaml. Even with the change in documentation, it's a brittle approach when the commands themselves can have different quotes inside them. Ultimately, the solution was to move from the AWS CLI and use the [AWS Tools for PowerShell](https://docs.aws.amazon.com/powershell/). The result looks something like the following.

```
    # ${{ parameters.SSMTargets }} and ${{ parameters.CommandToExecute }} are pipeline template parameters
    $commandResults = Send-SSMCommand -DocumentName "AWS-RunPowerShellScript" -Target @(@{${{ parameters.SSMTargets }}}) -Parameter @{ commands = @("${{ parameters.CommandToExecute }}") }

    Write-Host "initial commandResults:"
    Write-Host $commandResults

    # wait
    Start-Sleep -Seconds 10

    $commandInvocations = Get-SSMCommandInvocation -CommandId $commandResults.CommandId -Details $true | Select-Object -ExpandProperty CommandPlugins

    Write-Host "commandInvocations details:"
    Write-Host $commandInvocations
    Write-Host ""
    Write-Host "Command Output:"
    Write-Host $commandInvocations.Output
```
