### ISSUE TITLE
[v2] Support sso defaults

### ISSUE THREAD

**Issue by pcolmer** [aws/aws-cli#4800] opened 2019-12-31 12:28 UTC
At the moment, I can put `sso_start_url` and `sso_region` under `[default]` so that configuring a new profile doesn't require as much typing, but the tool still adds those values, along with `region` and `output` under the new SSO profile.

Would it be better if the SSO profile only had values that differed from any values found in `[default]`? At the moment, if I have the values under `[default]` and remove the SSO values from the SSO profile, trying to login results in an error from `aws2`.

**Comment by kyleknap** [comment] 2020-01-02 20:33
This seems reasonable. If we exposed something like this, it would probably would be more general where a profile can inherit values (not just SSO-specific profiles) from another profile.  I also think we should look into investing in configuration tooling that is able to setup a new profile that is similar to another profile minus a few config values.

**Comment by tim-finnigan** [comment] 2021-11-18 17:20
This looks like a duplicate of https://github.com/aws/aws-cli/issues/5200. I think we should close this in favor of that issue where there is more discussion.

**Closed by tim-finnigan** 2021-11-18 17:20 UTC
Labels: duplicate, feature-request, v2, sso
