### ISSUE TITLE
Feature Request: Handle `--help` argument

### ISSUE THREAD

**Issue by mvastola** [aws/aws-cli#5191] opened 2020-05-10 23:55 UTC
I, like many sysadmins, am very used to using the `--help` argument to commands to get information about it. `aws-cli` provides this information only when adding the word (sans the hyphens) `help` following the service and/or API function name. 

Unfortunately, it appears I don't use the CLI quite often enough to get used to the unusual syntax for this, but I would argue people who don't use the CLI that often are precisely the people who reference the help pages most.

This is a persistent frustration of mine and it would be great if `--help` could be recognized as an alias for `help`.

I considered writing a wrapper script for myself but that seemed like overkill, especially given that I'm sure I'm not the only person to have this frustration.

**Comment by kdaily** [comment] 2020-10-06 20:56
Hi @mvastola,

You are not alone in encountering this! This is a duplicate of #303 and #576. Can you please add your upvote to the original comment and anything further one one of those, please? Thanks!

**Closed** 2020-10-06 20:56 UTC
Labels: duplicate, feature-request
