### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request

### ISSUE THREAD

**Issue by nmadmon** [aws/aws-cli#1136] opened 2015-02-09 15:51 UTC
I'm trying to delete a recordSet from route53 (using boto3), but I'm always getting invalid request error. can you help me?

the following is my code:

	import boto3
	route53 = boto3.client('route53')
	recordValue={'Value':'internal-itzik-wc-rte-elb-2109479642.us-east-1.elb.amazonaws.com'}
	ResourceRecord=[recordValue]
	recordSet={'Name':'itzik-wc-rte-elb.itzik.domain','Type':'CNAME','ResourceRecords':ResourceRecord}
	changes={'Action':'DELETE','ResourceRecordSet':recordSet}
	changeBatch={'Changes':[changes]}
	route53.change_resource_record_sets(HostedZoneId='Z11OYNAE2ZZY5X', ChangeBatch=changeBatch)

the following is the error from the log:
ERROR:
  File "C:\Python34\lib\site-packages\botocore-0.80.0-py3.4.egg\botocore\client.py", line 249, in _api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidInput) when calling the ChangeResourceRecordSets operation: Invalid request

LOG:
2015-02-09 17:43:29,845 - DEBUG - TEST INFO
2015-02-09 17:43:29,862 - DEBUG - Event before-parameter-build.route53.ChangeResourceRecordSets: calling handler <function fix_route53_ids at 0x031BB810>
2015-02-09 17:43:29,862 - DEBUG - HostedZoneId Z11OYNAE2ZZY5X -> Z11OYNAE2ZZY5X
2015-02-09 17:43:29,865 - DEBUG - Making request for <botocore.model.OperationModel object at 0x032BEBD0> (verify_ssl=True) with params: {'query_string': {}, 'method': 'POST', 'headers': {}, 'url_path': '/2013-04-01/hostedzone/Z11OYNAE2ZZY5X/rrset/', 'body': '<ChangeResourceRecordSetsRequest xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><ChangeBatch><Changes><Change><Action>DELETE</Action><ResourceRecordSet><ResourceRecords><ResourceRecord><Value>internal-itzik-wc-rte-elb-2109479642.us-east-1.elb.amazonaws.com</Value></ResourceRecord></ResourceRecords><Name>itzik-wc-rte-elb.itzik.domain</Name><Type>CNAME</Type></ResourceRecordSet></Change></Changes></ChangeBatch></ChangeResourceRecordSetsRequest>'}
2015-02-09 17:43:29,870 - DEBUG - Sending http request: <PreparedRequest [POST]>
2015-02-09 17:43:29,870 - INFO - Starting new HTTPS connection (1): route53.amazonaws.com
2015-02-09 17:43:31,727 - DEBUG - "POST /2013-04-01/hostedzone/Z11OYNAE2ZZY5X/rrset/ HTTP/1.1" 400 259
2015-02-09 17:43:31,729 - DEBUG - Response headers:
{'content-length': '259',
 'content-type': 'text/xml',
 'date': 'Mon, 09 Feb 2015 15:43:30 GMT',
 'nncoection': 'close',
 'x-amzn-requestid': '663bc19f-b072-11e4-a919-8b805de68f02'}
2015-02-09 17:43:31,730 - DEBUG - Response body:
b'<?xml version="1.0"?>\n<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>663bc19f-b072-11e4-a919-8b805de68f02</RequestId></ErrorResponse>'

**Comment by jamesls** [comment] 2015-02-09 19:05
cc @danielgtaylor , who might be able to help.  I would suggest possibly moving this over to boto/boto3 instead of the aws/aws-cli repo,

**Comment by kyleknap** [comment] 2015-02-09 21:05
I believe that the issue is that you are not including a TTL, which is labeled required in route53's api docs: http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html

So you can do that by adding a TTL for the record set:
```
recordSet={'Name':'itzik-wc-rte-elb.itzik.domain','Type':'CNAME','ResourceRecords':ResourceRecord, 'TTL': 60}
```
I am going to close this issue (since the CLI is not being used here). But if you are still having problems, please resubmit the issue to boto3: https://github.com/boto/boto3/issues

**Closed by kyleknap** 2015-02-09 21:05 UTC
