### ISSUE TITLE
sqs help causes internal error

### ISSUE THREAD

**Issue by mikeblas** [aws/aws-cli#4720] opened 2019-12-01 01:57 UTC
The aws2 help for SQS causes an internal documentation engine error and is poorly formatted.

To repro, just use the `aws2 sqs help` command.  After the intro and list of commands are displayed, this output is shown:

```
Docutils System Messages
************************

<SYSTEM MESSAGE: <string>:: (ERROR/3) Anonymous hyperlink mismatch: 1
references but 0 targets. See "backrefs" attribute for IDs.>
```

I'm running on Windows 10:

```
>aws2 --version
aws-cli/2.0.0dev1 Python/3.7.5 Windows/10 botocore/2.0.0dev1
```

**Comment by mikeblas** [comment] 2019-12-01 02:05
Actually, the same issue happens with aws1; same repro steps.

````
>aws --version
aws-cli/1.16.292 Python/3.6.0 Windows/10 botocore/1.13.28
````

**Comment by jamesls** [comment] 2019-12-13 23:09
Seeing that as well, labeling as doc issue.  Thanks for reporting.

**Comment by mikeblas** [comment] 2020-10-15 02:18
Still broken in 2.0:

```
>aws --version
aws-cli/2.0.7 Python/3.7.5 Windows/10 botocore/2.0.0dev11

```

**Comment by kdaily** [comment] 2020-10-15 21:13
This documentation comes from here:

https://github.com/boto/botocore/blob/develop/botocore/data/sqs/2012-11-05/service-2.json#L1523

I'm not immediately seeing an issue with it, but I can confirm that the error still exists (though afterwards the documentation renders OK).

**Comment by stobrien89** [comment] 2021-03-05 02:17
Closing, as this is a duplicate of #3731

**Closed by stobrien89** 2021-03-05 02:17 UTC
Labels: documentation, duplicate
