### ISSUE TITLE
list-identity-providers documentation does not show required params correctly

### ISSUE THREAD

**Issue by TDA** [aws/aws-cli#3926] opened 2019-02-13 19:22 UTC
In the documentation for the [ListIdentityProviders](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListIdentityProviders.html) command,  `MaxResults` needs to be marked as a required field, because when we dont pass it in, it results in

```
aws cognito-idp list-identity-providers --user-pool-id USER_POOL_ID

An error occurred (InvalidParameterException) when calling the ListIdentityProviders operation: 1 validation error detected: Value '0' at 'maxResults' failed to satisfy constraint: Member must have value greater than or equal to 1
```

I believe this happens because it defaults to 0, and that fails validation. If we mark the field as required, this can be avoided.  This happens with both the CLI and the JS SDK, and needs documentation to be fixed at both places.

**Comment by klaytaybai** [comment] 2019-02-14 00:45
Hi @TDA, instead of changing the documentation I think changing the default to the max value of 60 would be a better experience.  This also shouldn't result in any breaking changes for customers.  I'll ask the service team to make the fix.  If I get an update on it, I'll try to remember to let you know.

**Comment by TDA** [comment] 2019-02-14 07:28
@klaytaybai Sounds good, thanks for the update.

**Comment by justnance** [comment] 2019-02-14 15:19
@TDA - This is a duplicate of #3866.  I'm closing this issue so we can use #3866 as the tracking issue.

**Closed by justnance** 2019-02-14 15:19 UTC
Labels: bug, cognito, service-api
