### ISSUE TITLE
`aws organizations [cmd]` fails in latest build

### ISSUE THREAD

**Issue by toddZilla0130** [aws/aws-cli#3552] opened 2018-09-09 12:22 UTC
This is all I'm getting. Have tried complete uninstall/reinstall.
```
bash-4.4$ aws organizations help

'NoneType' object has no attribute 'replace'
bash-4.4$ aws organizations not-valid

'NoneType' object has no attribute 'replace'
bash-4.4$ aws organizations

'NoneType' object has no attribute 'replace'
```

Version:
```
bash-4.4$ aws --version
aws-cli/1.16.10 Python/3.7.0 Darwin/17.7.0 botocore/1.12.0
```

(temporary fix: downgrade to 1.16.0)

**Comment by toddZilla0130** [comment] 2018-09-18 15:34
Wow sorry I got so sidetracked. Here's the debug output:
```
aws --debug organizations help
2018-09-18 11:30:54,053 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.16.15 Python/3.7.0 Darwin/17.7.0 botocore/1.12.5
2018-09-18 11:30:54,053 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'organizations', 'help']
2018-09-18 11:30:54,054 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x1031352f0>
2018-09-18 11:30:54,054 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,054 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x1027f4ea0>
2018-09-18 11:30:54,054 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,054 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x102c55b70>
2018-09-18 11:30:54,054 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,054 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2018-09-18 11:30:54,055 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2018-09-18 11:30:54,055 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,055 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2018-09-18 11:30:54,055 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,055 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2018-09-18 11:30:54,063 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,063 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x102ed8f28>
2018-09-18 11:30:54,064 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,064 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-09-18 11:30:54,064 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2018-09-18 11:30:54,064 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/------/.aws/models/organizations/2016-11-28/service-2.json
2018-09-18 11:30:54,067 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.organizations: calling handler <function register_retries_for_service at 0x102371b70>
2018-09-18 11:30:54,067 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 341, in __call__
    service_parser = self._create_parser()
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 381, in _create_parser
    command_table = self._get_command_table()
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 326, in _get_command_table
    self._command_table = self._create_command_table()
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 348, in _create_command_table
    service_model = self._get_service_model()
  File "/usr/local/lib/python3.7/site-packages/awscli/clidriver.py", line 334, in _get_service_model
    self._service_name, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 540, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 568, in get_service_data
    service_name=service_name, session=self)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/handlers.py", line 283, in register_retries_for_service
    service_event_name = hyphenize_service_id(service_id)
  File "/usr/local/lib/python3.7/site-packages/botocore/utils.py", line 981, in hyphenize_service_id
    return service_id.replace(' ', '-').lower()
AttributeError: 'NoneType' object has no attribute 'replace'
2018-09-18 11:30:54,069 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

'NoneType' object has no attribute 'replace'
```

I deleted `~/.aws/models/**` and `organizations` commands came back.

**Comment by justnance** [comment] 2018-09-26 21:45
@toddZilla0130 - Thanks for your feedback. Glad to hear this is resolved.  The debug indicates it was loading a custom model which appears to have been part of the root cause: 
```
2018-09-18 11:30:54,064 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /Users/------/.aws/models/organizations/2016-11-28/service-2.json
```
Let us know if there are any other questions.

**Comment by toddZilla0130** [comment] 2018-09-27 09:34
Not a clue as to where the custom model may have come from unless it was leftover from the beta/preview days of Organizations. Thanks for checking in - we can close this off. Cheers!

**Comment by justnance** [comment] 2018-09-27 16:34
@toddZilla0130 - Thanks for the feedback.  With this type of issue, we usually recommend to check for custom models left over from beta/preview work.  Closing the issue.

**Closed by justnance** 2018-09-27 16:34 UTC
