### ISSUE TITLE
AWS::Synthetics::Canary Package support for code

### ISSUE THREAD

**Issue by jk2l** [aws/aws-cli#5753] opened 2020-11-25 03:31 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to package code from my local directory similar to AWS::Lambda::Function's Code block

**Describe the solution you'd like**
```
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambda/
    
  Heartbeat:
    Type: AWS::Synthetics::Canary
    Properties:
      Code: lambda/
```
Similar to `AWS::Lambda::Function` in which `aws cloudformation package` can change `Code` block into a file reference in S3. Extend this functionality to `AWS::Synthetics::Canary` Code block

**Describe alternatives you've considered**
CI/CD tool that manually package the file into zip. make a random hash and upload to S3

**Additional context**
All supported package reference can be found here https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html

**Comment by kdaily** [comment] 2020-11-25 17:24
Hi @jk2l, thanks for the feature request. I'll check on this with the CloudFormation team.

**Comment by ConnorKirk** [comment] 2020-12-11 17:43
I think this is a duplicate of issue #5230 
There is an open PR #5569

**Comment by kdaily** [comment] 2020-12-11 18:04
Thanks @ConnorKirk, confirmed. Marking duplicate!

**Closed by kdaily** 2020-12-11 18:04 UTC
Labels: cloudformation package/deploy, customization, feature-request
