### ISSUE TITLE
ImportError: No module named connection

### ISSUE THREAD

**Issue by gworley3** [aws/aws-cli#3606] opened 2018-09-25 00:20 UTC
Started seeing this error after updating to the latest version (awscli-1.16.20-py2.py3-none-any.whl based on what pip outputs).

```
ubuntu@localhost:~$ aws
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 27, in <module>
    import botocore.credentials
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 42, in <module>
    from botocore.utils import InstanceMetadataFetcher, parse_key_val_file
  File "/usr/local/lib/python2.7/dist-packages/botocore/utils.py", line 30, in <module>
    import botocore.awsrequest
  File "/usr/local/lib/python2.7/dist-packages/botocore/awsrequest.py", line 21, in <module>
    from urllib3.connection import VerifiedHTTPSConnection
ImportError: No module named connection
```

**Comment by gworley3** [comment] 2018-09-25 00:31
Also this is ubuntu 14.04.

**Comment by justnance** [comment] 2018-09-28 16:49
@gworley3 - Thanks for reaching out.  I was not able to reproduce this issue.  We sometimes see this issue when there is a problem with the CLI installation.  

Was the CLI installed via PIP or a bundled installer?  
What version of botocore is returning in the output for `aws --version` ?

Botocore has dependencies which are installed with a bundled installer.  One of the dependencies is urllib3 and it appears the urllib3 is running the wrong version:
```
urllib3.connection import VerifiedHTTPSConnection
ImportError: No module named connection
```

**Comment by stealthycoin** [comment] 2018-10-01 19:14
@gworley3 Please show us the output of `pip freeze`. Without that we can't know exactly what is  going on. If you do indeed have urllib3 `1.7.1` in the same environment as the CLI then thats the issue. I's way out of range of the version constraint we have of `>=1.20,<1.24`. 

How exactly did you install the CLI into the environment? If you followed our docs for installing with pip on Linux it says to use the `--upgrade` flag which should have upgraded `urllib3` to a valid version.

In any case install the CLI again through pip following [the docs here](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html) or manually upgrade your `urllib3` to a valid version.

**Comment by Enturk** [comment] 2018-10-01 19:22
I'm not gworley, but in case it's useful, here's my `pip freeze` output:
`BzrTools==2.6.0
Pillow==2.3.0
PyYAML==3.13
SecretStorage==2.0.0
argparse==1.2.1
awscli==1.16.24
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.6.3
boto3==1.9.6
botocore==1.12.14
bzr==2.7.0dev1
certifi==2018.8.24
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
decorator==3.4.0
docker==3.5.0
docker-pycreds==0.3.0
docutils==0.14
duplicity==0.6.23
futures==3.2.0
html5lib==0.999
httplib2==0.8
idna==2.7
ipaddress==1.0.22
ipython==1.2.1
jmespath==0.9.3
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
lockfile==0.8
lpthw.web==1.1
matplotlib==1.3.1
mercurial==2.8.2
numpy==1.8.2
oauth==1.0.1
paramiko==1.10.1
pexpect==3.1
psycopg2==2.7.5
pyasn1==0.4.4
pycrypto==2.6.1
pygobject==3.12.0
pygpgme==0.3
pyparsing==2.0.1
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-dotenv==0.9.1
pytz==2012c
requests==2.2.1
rsa==3.4.2
s3transfer==0.1.13
scipy==0.13.3
simplegeneric==0.8.1
simplejson==3.3.1
six==1.5.2
stevedore==0.14.1
urllib3==1.7.1
virtualenv==1.11.4
virtualenv-clone==0.2.4
virtualenvwrapper==4.1.1
wadllib==1.3.2
websocket-client==0.53.0
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5`

**Comment by gworley3** [comment] 2018-10-01 19:30
After some digging around figured out the issue was that I installed PIP via apt and this was preventing urllib3 (and a few other libraries, but this was the problem here) from being updated. Removing the python-pip package and then reinstalling pip via `easy_install -U pip` I was able to get the right version of urllib3 installed.

**Comment by stealthycoin** [comment] 2018-10-01 19:34
@gworley3 do you have a link to how you figured that out? That's a new one to me I'd like to read it.

**Comment by gworley3** [comment] 2018-10-01 19:48
After playing around with trying to upgrade urllib3 and getting an error message, I copy and pasted it into Google and it turned up this, which pointed me in the right direction:

https://askubuntu.com/questions/644911/unable-to-upgrade-pip

**Comment by stealthycoin** [comment] 2018-10-01 23:57
@gworley3 Interesting. I tried spinning up a fresh ubuntu 18 and did:
```
sudo apt update
sudo apt upgrade
sudo apt install python-pip
pip install -U awscli
```

Which gave me urllib3 1.23 and a working copy of the CLI.

I wonder if at the time you last ran apt update on that machine it had a version of python-pip which was locking urllib3 to a max of 1.7? That's still really annoying because that means you need to update pip through apt then use `pip --upgrade` with no indication that the issue is with the apt vended version of pip.

Sounds like the general advice should be to not get pip through apt...

Thanks for the link! Closing issue as resolved. Hopefully the exact title helps people out in the future.

**Closed by stealthycoin** 2018-10-01 23:57 UTC

**Comment by gworley3** [comment] 2018-10-02 00:05
Yep, I've learned my lesson on installing pip through apt; didn't realize it would create these kind of issues.

I did this on Ubuntu 14.04 so there's a good chance the updates just didn't get backported because they weren't considered important enough, which could be why it works fine in 18.04 (or 18.10 if you used the beta).

**Comment by aryashah278** [comment] 2019-05-23 10:00
Hi @gworley3 I also have python 2.7 and ubuntu 14.04. Can you please let me know which version of urllib3 worked for you?

**Comment by gworley3** [comment] 2019-05-23 17:33
i'm not sure, because i got it to work by not using apt-installed pip and instead installed pip via easy_install because when installed via apt it created a dependency issue because the version of pip in the apt repo also used url3 and made it stuck at the wrong version, unable to get a compatible version for aws-cli. see the link i posted above for details on what to do.
