### ISSUE TITLE
Some 'help' commands hang (macOS Catalina 10.15.4)

### ISSUE THREAD

**Issue by edmundcraske-bjss** [aws/aws-cli#5118] opened 2020-04-08 10:07 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I am finding that some 'help' commands hang, e.g. `aws ec2 describe-instances help`. It might be correlated with the size of the man page? I have tried updating to the latest awscli, both via homebrew and via pip. I've also tried installing the latest groff, but it has made no difference.

**SDK version number**
aws --version
aws-cli/1.18.38 Python/3.8.2 Darwin/19.4.0 botocore/1.15.38

**Platform/OS/Hardware/Device**
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266

system_profiler SPHardwareDataType | grep "Model Identifier"
      Model Identifier: MacBookPro16,1

**To Reproduce (observed behavior)**
Run `aws ec2 describe-instances help` or `aws cloudfront list-distributions help` as two examples.

**Expected behavior**
The man page for those commands appears

**Logs/output**
```aws --debug ec2 describe-instances help
2020-04-08 11:06:28,788 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.18.38 Python/3.8.2 Darwin/19.4.0 botocore/1.15.38
2020-04-08 11:06:28,788 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'ec2', 'describe-instances', 'help']
2020-04-08 11:06:28,788 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10933fca0>
2020-04-08 11:06:28,788 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x108ce5430>
2020-04-08 11:06:28,789 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x108d550d0>
2020-04-08 11:06:28,798 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10920c280>
2020-04-08 11:06:28,802 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/ec2/2016-11-15/service-2.json
2020-04-08 11:06:28,840 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler functools.partial(<function _remove_commands at 0x1092d9ee0>, commands_to_remove=['import-instance', 'import-volume'])
2020-04-08 11:06:28,840 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2020-04-08 11:06:28,840 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2020-04-08 11:06:28,840 - MainThread - botocore.hooks - DEBUG - Event building-command-table.ec2: calling handler <function add_waiters at 0x10934d4c0>
2020-04-08 11:06:28,859 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/ec2/2016-11-15/waiters-2.json
2020-04-08 11:06:28,860 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('filters', <awscli.arguments.ListArgument object at 0x10ba5cee0>), ('instance-ids', <awscli.arguments.ListArgument object at 0x10ba5ceb0>), ('dry-run', <awscli.arguments.BooleanArgument object at 0x10ba5ce80>), ('no-dry-run', <awscli.arguments.BooleanArgument object at 0x10ba7b040>), ('max-results', <awscli.arguments.CLIArgument object at 0x10ba7b070>), ('next-token', <awscli.arguments.CLIArgument object at 0x10ba7b0a0>)])
2020-04-08 11:06:28,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_streaming_output_arg at 0x109347310>
2020-04-08 11:06:28,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function rename_arg.<locals>._rename_arg at 0x109378040>
2020-04-08 11:06:28,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function rename_arg.<locals>._rename_arg at 0x1093780d0>
2020-04-08 11:06:28,861 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler functools.partial(<function pull_up_bool at 0x109347dc0>, event_handler=<botocore.hooks.EventAliaser object at 0x107bc3580>)
2020-04-08 11:06:28,878 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_cli_input_json at 0x108d555e0>
2020-04-08 11:06:28,879 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function unify_paging_params at 0x1092ce9d0>
2020-04-08 11:06:28,898 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/ec2/2016-11-15/paginators-1.json
2020-04-08 11:06:28,899 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeInstances
2020-04-08 11:06:28,899 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.ec2.describe-instances: calling handler <function add_generate_skeleton at 0x1092a9f70>
2020-04-08 11:06:28,900 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10ba5c9a0>>
2020-04-08 11:06:28,900 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.ec2.describe-instances: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10ba7b520>>
2020-04-08 11:06:28,902 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_breadcrumbs of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,903 - MainThread - botocore.hooks - DEBUG - Event doc-title.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_title of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,903 - MainThread - botocore.hooks - DEBUG - Event doc-description.ec2.describe-instances: calling handler <bound method OperationDocumentEventHandler.doc_description of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,903 - MainThread - botocore.hooks - DEBUG - Event doc-description.ec2.describe-instances: calling handler <function add_paging_description at 0x1092ce940>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.filters: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.instance-ids: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.dry-run: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.no-dry-run: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,904 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.starting-token: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.page-size: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.max-items: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.ec2.describe-instances.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_options_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,905 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.filters: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,917 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.filters: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,918 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.instance-ids: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,918 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.instance-ids: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,918 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.dry-run: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,918 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.dry-run: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,919 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.no-dry-run: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,919 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.no-dry-run: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,919 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,919 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.cli-input-json: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,919 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.starting-token: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,920 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.starting-token: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,920 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.page-size: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,920 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.page-size: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,920 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.max-items: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,921 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.max-items: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,921 - MainThread - botocore.hooks - DEBUG - Event doc-option.ec2.describe-instances.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,921 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.ec2.describe-instances.generate-cli-skeleton: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,921 - MainThread - botocore.hooks - DEBUG - Event doc-options-end.ec2.describe-instances: calling handler <bound method OperationDocumentEventHandler.doc_options_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,922 - MainThread - botocore.hooks - DEBUG - Event doc-examples.ec2.describe-instances: calling handler <function add_examples at 0x108d4ab80>
2020-04-08 11:06:28,922 - MainThread - awscli.customizations.addexamples - DEBUG - Looking for example file at: /usr/local/lib/python3.8/site-packages/awscli/examples/ec2/describe-instances.rst
2020-04-08 11:06:28,923 - MainThread - botocore.hooks - DEBUG - Event doc-output.ec2.describe-instances: calling handler <bound method OperationDocumentEventHandler.doc_output of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:28,938 - MainThread - botocore.hooks - DEBUG - Event doc-relateditems-start.ec2.describe-instances: calling handler <bound method CLIDocumentEventHandler.doc_relateditems_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10ba7bd30>>
2020-04-08 11:06:29,185 - MainThread - awscli.help - DEBUG - Running command: ['groff', '-m', 'man', '-T', 'ascii']```

```aws --debug cloudfront list-distributions help
2020-04-08 11:07:12,303 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.18.38 Python/3.8.2 Darwin/19.4.0 botocore/1.15.38
2020-04-08 11:07:12,304 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'cloudfront', 'list-distributions', 'help']
2020-04-08 11:07:12,304 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x102482ca0>
2020-04-08 11:07:12,304 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x101e28430>
2020-04-08 11:07:12,304 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x101e980d0>
2020-04-08 11:07:12,311 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10234f280>
2020-04-08 11:07:12,312 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/cloudfront/2019-03-26/service-2.json
2020-04-08 11:07:12,317 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudfront: calling handler <function _add_sign at 0x1021278b0>
2020-04-08 11:07:12,317 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cloudfront: calling handler <function add_waiters at 0x1024904c0>
2020-04-08 11:07:12,333 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/cloudfront/2019-03-26/waiters-2.json
2020-04-08 11:07:12,334 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('marker', <awscli.arguments.CLIArgument object at 0x10271b0a0>), ('max-items', <awscli.arguments.CLIArgument object at 0x10271b0d0>)])
2020-04-08 11:07:12,334 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudfront.list-distributions: calling handler <function add_streaming_output_arg at 0x10248a310>
2020-04-08 11:07:12,335 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudfront.list-distributions: calling handler <function add_cli_input_json at 0x101e985e0>
2020-04-08 11:07:12,335 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudfront.list-distributions: calling handler <function unify_paging_params at 0x1024119d0>
2020-04-08 11:07:12,351 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/lib/python3.8/site-packages/botocore/data/cloudfront/2019-03-26/paginators-1.json
2020-04-08 11:07:12,351 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListDistributions
2020-04-08 11:07:12,351 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.cloudfront.list-distributions: calling handler <function add_generate_skeleton at 0x1023edf70>
2020-04-08 11:07:12,352 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudfront.list-distributions: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x10271b2b0>>
2020-04-08 11:07:12,352 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.cloudfront.list-distributions: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x10271b610>>
2020-04-08 11:07:12,354 - MainThread - botocore.hooks - DEBUG - Event doc-breadcrumbs.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_breadcrumbs of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,354 - MainThread - botocore.hooks - DEBUG - Event doc-title.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_title of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,354 - MainThread - botocore.hooks - DEBUG - Event doc-description.cloudfront.list-distributions: calling handler <bound method OperationDocumentEventHandler.doc_description of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,354 - MainThread - botocore.hooks - DEBUG - Event doc-description.cloudfront.list-distributions: calling handler <function add_paging_description at 0x102411940>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-start.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudfront.list-distributions.max-items: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudfront.list-distributions.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudfront.list-distributions.starting-token: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudfront.list-distributions.page-size: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-option.cloudfront.list-distributions.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,355 - MainThread - botocore.hooks - DEBUG - Event doc-synopsis-end.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_synopsis_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,356 - MainThread - botocore.hooks - DEBUG - Event doc-options-start.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_options_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,356 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudfront.list-distributions.max-items: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,357 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudfront.list-distributions.max-items: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,357 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudfront.list-distributions.cli-input-json: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,357 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudfront.list-distributions.cli-input-json: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,357 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudfront.list-distributions.starting-token: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,358 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudfront.list-distributions.starting-token: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,358 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudfront.list-distributions.page-size: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,358 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudfront.list-distributions.page-size: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,358 - MainThread - botocore.hooks - DEBUG - Event doc-option.cloudfront.list-distributions.generate-cli-skeleton: calling handler <bound method CLIDocumentEventHandler.doc_option of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,358 - MainThread - botocore.hooks - DEBUG - Event doc-option-example.cloudfront.list-distributions.generate-cli-skeleton: calling handler <bound method OperationDocumentEventHandler.doc_option_example of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,359 - MainThread - botocore.hooks - DEBUG - Event doc-options-end.cloudfront.list-distributions: calling handler <bound method OperationDocumentEventHandler.doc_options_end of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,359 - MainThread - botocore.hooks - DEBUG - Event doc-examples.cloudfront.list-distributions: calling handler <function add_examples at 0x101e8db80>
2020-04-08 11:07:12,359 - MainThread - awscli.customizations.addexamples - DEBUG - Looking for example file at: /usr/local/lib/python3.8/site-packages/awscli/examples/cloudfront/list-distributions.rst
2020-04-08 11:07:12,361 - MainThread - botocore.hooks - DEBUG - Event doc-output.cloudfront.list-distributions: calling handler <bound method OperationDocumentEventHandler.doc_output of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,399 - MainThread - botocore.hooks - DEBUG - Event doc-relateditems-start.cloudfront.list-distributions: calling handler <bound method CLIDocumentEventHandler.doc_relateditems_start of <awscli.clidocs.OperationDocumentEventHandler object at 0x10271ba60>>
2020-04-08 11:07:12,693 - MainThread - awscli.help - DEBUG - Running command: ['groff', '-m', 'man', '-T', 'ascii']```

**Comment by edmundcraske-bjss** [comment] 2020-04-08 10:08
I did take a quick look for previous issues, and found some that looked possibly relevant, but they all seemed to be closed with no fix, due to no updates on them for some time.

**Comment by KaibaLopez** [comment] 2020-04-08 18:41
Hi @edmundcraske-bjss ,
I'm not able to reproduce this error, is there anything special about your setup that you can think of? Also, can you try upgrading to V2?

**Comment by edmundcraske-bjss** [comment] 2020-04-09 10:18
Hi @KaibaLopez I don't know what changed, but my Mac crashed last night, and this morning things are working as expected, both with v1 and v2 of awscli. Given the number of previous issues raised regarding a similar issue, I think that there must be some underlying edge case bug which is worthy of fixing - perhaps e.g. #2509 points developers in the right direction?

**Comment by KaibaLopez** [comment] 2020-04-16 19:38
Hi @edmundcraske-bjss ,
I'm going to be honest, without a way to consistently reproduce the problem this is not going to be prioritized, and since your case was (although mysteriously ) solved... I'm leaning towards closing this issue.
I know this is not the best response but really I can't do much else, sorry about it but glad you at least are no longer facing the problem.

**Closed** 2020-04-17 16:45 UTC
Labels: closing-soon, wontfix
